-- ddro_1w_altera_gpio_2300_qz6qrya.vhd

-- This file was auto-generated from altera_gpio_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 25.1.1 125

library IEEE;
library altera_gpio_core10_ph2_2210;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ddro_1w_altera_gpio_2300_qz6qrya is
	port (
		ck       : in  std_logic                    := '0';             --       ck.export,   In input and output paths, this clock feeds a packed register or DDIO. In bidirectional mode, this clock is the unique clock for the input and output paths if you turn off the Separate input/output Clocks parameter.
		datain_h : in  std_logic_vector(0 downto 0) := (others => '0'); -- datain_h.fragment, TBD
		datain_l : in  std_logic_vector(0 downto 0) := (others => '0'); -- datain_l.fragment, TBD
		dataout  : out std_logic_vector(0 downto 0)                     --  pad_out.export,   Output signal to the pad.Output signal to the pad.
	);
end entity ddro_1w_altera_gpio_2300_qz6qrya;

architecture rtl of ddro_1w_altera_gpio_2300_qz6qrya is
	component altera_gpio_cmp is
		generic (
			SIZE                   : integer := 4;
			PIN_TYPE               : string  := "output";
			REGISTER_MODE          : string  := "sdr";
			HALF_RATE              : string  := "false";
			DDIO_WITH_DELAY        : string  := "false";
			SEPARATE_I_O_CLOCKS    : string  := "false";
			BUFFER_TYPE            : string  := "single-ended";
			PSEUDO_DIFF            : string  := "false";
			ARESET_MODE            : string  := "none";
			SRESET_MODE            : string  := "none";
			OPEN_DRAIN             : string  := "false";
			BUS_HOLD               : string  := "false";
			ENABLE_OE              : string  := "false";
			ENABLE_CKE             : string  := "false";
			ENABLE_TERM            : string  := "false";
			DYNAMIC_PULL_UP_ENABLE : string  := "false"
		);
		port (
			ck                 : in    std_logic                    := 'X';             -- export
			din                : in    std_logic_vector(1 downto 0) := (others => 'X'); -- fragment
			pad_out            : out   std_logic_vector(0 downto 0);                    -- export
			cke                : in    std_logic                    := 'X';             -- export
			ck_in              : in    std_logic                    := 'X';             -- export
			ck_out             : in    std_logic                    := 'X';             -- export
			puen               : in    std_logic_vector(0 downto 0) := (others => 'X'); -- export
			dout               : out   std_logic_vector(1 downto 0);                    -- export
			oe                 : in    std_logic_vector(0 downto 0) := (others => 'X'); -- export
			pad_io             : inout std_logic_vector(0 downto 0) := (others => 'X'); -- export
			pad_io_b           : inout std_logic_vector(0 downto 0) := (others => 'X'); -- export
			pad_in             : in    std_logic_vector(0 downto 0) := (others => 'X'); -- export
			pad_in_b           : in    std_logic_vector(0 downto 0) := (others => 'X'); -- export
			pad_out_b          : out   std_logic_vector(0 downto 0);                    -- export
			terminationcontrol : in    std_logic                    := 'X';             -- export
			aclr               : in    std_logic                    := 'X';             -- export
			aset               : in    std_logic                    := 'X';             -- export
			sclr               : in    std_logic                    := 'X';             -- export
			sset               : in    std_logic                    := 'X'              -- export
		);
	end component altera_gpio_cmp;

	for core : altera_gpio_cmp
		use entity altera_gpio_core10_ph2_2210.altera_gpio;
begin

	core : component altera_gpio_cmp
		generic map (
			SIZE                   => 1,
			PIN_TYPE               => "output",
			REGISTER_MODE          => "ddr",
			HALF_RATE              => "false",
			DDIO_WITH_DELAY        => "false",
			SEPARATE_I_O_CLOCKS    => "false",
			BUFFER_TYPE            => "single-ended",
			PSEUDO_DIFF            => "false",
			ARESET_MODE            => "none",
			SRESET_MODE            => "none",
			OPEN_DRAIN             => "false",
			BUS_HOLD               => "false",
			ENABLE_OE              => "false",
			ENABLE_CKE             => "false",
			ENABLE_TERM            => "false",
			DYNAMIC_PULL_UP_ENABLE => "false"
		)
		port map (
			ck                 => ck,          --       ck.export
			din(0)             => datain_l(0), -- datain_h.fragment
			din(1)             => datain_h(0), --         .fragment
			pad_out            => dataout,     --  pad_out.export
			cke                => '1',         -- (terminated)
			ck_in              => '0',         -- (terminated)
			ck_out             => '0',         -- (terminated)
			puen               => "0",         -- (terminated)
			dout               => open,        -- (terminated)
			oe                 => "0",         -- (terminated)
			pad_io             => open,        -- (terminated)
			pad_io_b           => open,        -- (terminated)
			pad_in             => "0",         -- (terminated)
			pad_in_b           => "0",         -- (terminated)
			pad_out_b          => open,        -- (terminated)
			terminationcontrol => '0',         -- (terminated)
			aclr               => '0',         -- (terminated)
			aset               => '0',         -- (terminated)
			sclr               => '0',         -- (terminated)
			sset               => '0'          -- (terminated)
		);

end architecture rtl; -- of ddro_1w_altera_gpio_2300_qz6qrya
