// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// This is an auto-generated file. Do not edit this file.
// altera_config_stream_endpoint.sv

`timescale 1 ns / 1 ns

package altera_config_stream_endpoint_wpackage;

function integer nonzero;
input integer value;
begin
	nonzero = (value > 0) ? value : 1;
end
endfunction

endpackage

module altera_config_stream_endpoint_wrapper
    import altera_config_stream_endpoint_wpackage::nonzero;
#(
    parameter READY_LATENCY          = 0,
    parameter HAS_URGENT             = 0,
    parameter HAS_STATUS             = 0,
    parameter HAS_STREAM             = 0,
    parameter MAX_SIZE               = 256,
    parameter STREAM_WIDTH           = 64,
    parameter TYPE_NAME              = 0,
    parameter INSTANCE_NAME          = 0,
    parameter CLOCK_RATE_CLK         = 0
) (
    input         clk,
    input         reset,
    output        command_ready,
    input         command_valid,
    input  [32-1:0] command_data,
    input         command_startofpacket,
    input         command_endofpacket,
    output        command_invalid,
    input         response_ready,
    output        response_valid,
    output [32-1:0] response_data,
    output        response_startofpacket,
    output        response_endofpacket,
    output        urgent_ready,
    input         urgent_valid,
    input  [32-1:0] urgent_data,
    output        stream_ready,
    input         stream_valid,
    input  [STREAM_WIDTH-1:0] stream_data,
    output        stream_active
);

	altera_config_stream_endpoint #(
        .READY_LATENCY          (READY_LATENCY),
        .HAS_URGENT             (HAS_URGENT),
        .HAS_STATUS             (HAS_STATUS),
        .HAS_STREAM             (HAS_STREAM),
        .MAX_SIZE               (MAX_SIZE),
        .STREAM_WIDTH           (STREAM_WIDTH),
        .TYPE_NAME              (TYPE_NAME),
        .INSTANCE_NAME          (INSTANCE_NAME),
        .CLOCK_RATE_CLK         (CLOCK_RATE_CLK)
) inst (
        .clk                    (clk),
        .reset                  (reset),
        .command_ready          (command_ready),
        .command_valid          (command_valid),
        .command_data           (command_data),
        .command_startofpacket  (command_startofpacket),
        .command_endofpacket    (command_endofpacket),
        .command_invalid        (command_invalid),
        .response_ready         (response_ready),
        .response_valid         (response_valid),
        .response_data          (response_data),
        .response_startofpacket (response_startofpacket),
        .response_endofpacket   (response_endofpacket),
        .urgent_ready           (urgent_ready),
        .urgent_valid           (urgent_valid),
        .urgent_data            (urgent_data),
        .stream_ready           (stream_ready),
        .stream_valid           (stream_valid),
        .stream_data            (stream_data),
        .stream_active          (stream_active)
	
	);

endmodule

// synthesis translate_off
// Empty module definition to allow simulation compilation.
module altera_config_stream_endpoint
    import altera_config_stream_endpoint_wpackage::nonzero;
#(
    parameter READY_LATENCY          = 0,
    parameter HAS_URGENT             = 0,
    parameter HAS_STATUS             = 0,
    parameter HAS_STREAM             = 0,
    parameter MAX_SIZE               = 256,
    parameter STREAM_WIDTH           = 64,
    parameter TYPE_NAME              = 0,
    parameter INSTANCE_NAME          = 0,
    parameter CLOCK_RATE_CLK         = 0
) (
    input         clk,
    input         reset,
    output        command_ready,
    input         command_valid,
    input  [32-1:0] command_data,
    input         command_startofpacket,
    input         command_endofpacket,
    output        command_invalid,
    input         response_ready,
    output        response_valid,
    output [32-1:0] response_data,
    output        response_startofpacket,
    output        response_endofpacket,
    output        urgent_ready,
    input         urgent_valid,
    input  [32-1:0] urgent_data,
    output        stream_ready,
    input         stream_valid,
    input  [STREAM_WIDTH-1:0] stream_data,
    output        stream_active
);
	
	//for simulation, assign all outputs to zero
	assign command_ready 			= '0;
	assign command_invalid 			= '0;
	assign response_valid 			= '0;
	assign response_data 			= '0;
	assign response_startofpacket 	= '0;
	assign response_endofpacket 	= '0;
	assign urgent_ready 			= '0;
	assign stream_ready 			= '0;
	assign stream_active 			= '0;

endmodule
// synthesis translate_on

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "Jv8lNbjFdP1RG6ZlRGDPQ18y9rK8xNjZPJSXRJP5QnPWfqyqNCZgAFckZeIKAKwNoSPIIpIipc8Lr+b9a/FWzIYgzMxpzrkpOByg+HoJBnaTRP9US7VEnPfzFsP4DZjz4ZfQo3AjGuPZdXoEPcUpMMVVVaUENWSiX6AT97YYkfX+YrBm5cVHUlgFZ8gk9eg+R0Z3hxyPZcAjv5lGd5X5M6DoA6WnB+Wn6k6+/EbGEiQfKTTO6AUyDa0ay/sr1+w4JG5GdFKve9kZ1UAqUxz0Z0Yv9qD3MBUEOmdz0xywt1kbAKxSHLW8fWPQ5BWCDNIo1edr71q5U8UM0g7hv7daiRMZZjGWHwUG905CB8MbUDIR/Un7IMH39bbGcKMqBC3zPnUivDmaqaRMMBOeGEmWtq7imzhcJ0gcEHzTwbffrBSdXNOmHqO8HPFbDxxEKZOsrCx2AHOMNjtVAv9m7b4AD6UgVjPwc5CBbE1r3Ml4s2p1OLdbrSgyTmu9xBOzd/TH4F+DRFwjiNEva0u/htaWHB7OF+ttGpjguGTIXk/2kLPlFoJ1Pk7gMtzE63kN2BNppt6v18U1TBIzzwr4FHZO2xzNj+A3Yct7Z5cQHg50pN6UQ79/dbuKpqi/UCUfe6gWTKN4xy+054HHqQHEltCdgUVEc/gIwpMTAtJVfXhIWx/b1vaG2+8m1WZ8zQpEkiLtDkEPZMW11zPwbFyywYaCFfSeDkF6oY4vE5V5RJ8dq5TtkuTi+zF3AQA2RX7gxtoevP+tgCI0QaLfuXlEJ59XKWvNnuRPiSdJRZdFjJltc3jWy8gh+Ik3q1u86H/lrS12tAT2C/YED35UuYPMpjmWnQ01zgVAT1uyBSlG/6ZH5+SibslQ8qCQ8D05fPIaoaVafKnDKeZm0X/1b5SJknGGH9s7dS8x1DnsAc8yzi5yaZ5dhd+xKbClnGk7iZ9e6+y729bypCkthuzMNpxgU4B4DNJAM9+Na2CW6AYY2PKqFTQ8i5mF0uu9ZffPcX38liv+"
`endif