-- ddro_6w.vhd

-- Generated using ACDS version 25.1.1 125

library IEEE;
library altera_gpio_2300;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ddro_6w is
	port (
		ck        : in  std_logic                    := '0';             --        ck.export,   In input and output paths, this clock feeds a packed register or DDIO. In bidirectional mode, this clock is the unique clock for the input and output paths if you turn off the Separate input/output Clocks parameter.
		datain_h  : in  std_logic_vector(5 downto 0) := (others => '0'); --  datain_h.fragment, TBD
		datain_l  : in  std_logic_vector(5 downto 0) := (others => '0'); --  datain_l.fragment, TBD
		dataout   : out std_logic_vector(5 downto 0);                    --   pad_out.export,   Output signal to the pad.Output signal to the pad.
		pad_out_b : out std_logic_vector(5 downto 0)                     -- pad_out_b.export,   Negative node of the differential output signal to the pad. This port is available if you turn on the Use differential buffer option.
	);
end entity ddro_6w;

architecture rtl of ddro_6w is
	component ddro_6w_altera_gpio_2300_jrsykna_cmp is
		port (
			ck        : in  std_logic                    := 'X';             -- export
			datain_h  : in  std_logic_vector(5 downto 0) := (others => 'X'); -- fragment
			datain_l  : in  std_logic_vector(5 downto 0) := (others => 'X'); -- fragment
			dataout   : out std_logic_vector(5 downto 0);                    -- export
			pad_out_b : out std_logic_vector(5 downto 0)                     -- export
		);
	end component ddro_6w_altera_gpio_2300_jrsykna_cmp;

	for gpio_0 : ddro_6w_altera_gpio_2300_jrsykna_cmp
		use entity altera_gpio_2300.ddro_6w_altera_gpio_2300_jrsykna;
begin

	gpio_0 : component ddro_6w_altera_gpio_2300_jrsykna_cmp
		port map (
			ck        => ck,        --        ck.export
			datain_h  => datain_h,  --  datain_h.fragment
			datain_l  => datain_l,  --  datain_l.fragment
			dataout   => dataout,   --   pad_out.export
			pad_out_b => pad_out_b  -- pad_out_b.export
		);

end architecture rtl; -- of ddro_6w
