-- jesd204b_core_intel_jesd204b_gts_phy_intel_directphy_gts_191_lvsxkwq.vhd

-- Generated using ACDS version 25.1.1 125

library IEEE;
library intel_directphy_gts_900;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity jesd204b_core_intel_jesd204b_gts_phy_intel_directphy_gts_191_lvsxkwq is
	generic (
		num_sys_cop                                   : integer := 1;
		prof0_num_sys_cop                             : integer := 1;
		rcfg_group                                    : string  := "lanes-1";
		num_xcvr_per_sys                              : integer := 1;
		duplex_mode                                   : string  := "rx";
		rx_deskew_en                                  : integer := 0;
		l_num_aib_per_xcvr                            : integer := 1;
		l_sys_xcvrs                                   : integer := 1;
		l_quad_num                                    : integer := 1;
		l_sys_xcvrs_cascade                           : integer := 1;
		l_sys_aibs                                    : integer := 1;
		l_tx_enable                                   : integer := 0;
		l_rx_enable                                   : integer := 1;
		fec_en                                        : integer := 0;
		l_fec_mode                                    : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		l_av1_enable                                  : integer := 0;
		avmm1_readdv_enable                           : integer := 1;
		avmm1_split                                   : integer := 0;
		avmm1_jtag_enable                             : integer := 0;
		l_av1_aib_enable                              : integer := 0;
		l_soft_csr_enable                             : integer := 0;
		l_soft_csr_enable_rphy                        : integer := 0;
		l_num_avmm1                                   : integer := 1;
		l_av1_ifaces                                  : integer := 1;
		l_av1_addr_bits                               : integer := 18;
		l_line_rate_p1ghz                             : integer := 100;
		l_av1_enable_rphy                             : integer := 0;
		avmm1_readdv_enable_rphy                      : integer := 1;
		avmm1_jtag_enable_rphy                        : integer := 0;
		silicon_revision                              : string  := "14nm5bcr3a";
		device_revision                               : string  := "14nm5bcr3a";
		enable_port_latency_measurement               : integer := 0;
		l_rx_deskew_enable                            : integer := 0;
		txparalleldata_width                          : integer := 80;
		txsimpleinterface_enable                      : integer := 0;
		simulation_sip_only                           : integer := 0;
		simulation_only                               : integer := 0;
		prof0_num_xcvr_per_sys                        : integer := 1;
		prof0_fec_en                                  : integer := 0;
		prof0_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		prof0_l_sys_xcvrs                             : integer := 1;
		prof1_num_xcvr_per_sys                        : integer := 1;
		prof1_fec_en                                  : integer := 0;
		prof1_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		prof1_l_sys_xcvrs                             : integer := 1;
		prof2_num_xcvr_per_sys                        : integer := 1;
		prof2_fec_en                                  : integer := 0;
		prof2_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		prof2_l_sys_xcvrs                             : integer := 1;
		prof3_num_xcvr_per_sys                        : integer := 1;
		prof3_fec_en                                  : integer := 0;
		prof3_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		prof3_l_sys_xcvrs                             : integer := 1;
		prof4_num_xcvr_per_sys                        : integer := 1;
		prof4_fec_en                                  : integer := 0;
		prof4_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		prof4_l_sys_xcvrs                             : integer := 1;
		prof5_num_xcvr_per_sys                        : integer := 1;
		prof5_fec_en                                  : integer := 0;
		prof5_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		prof5_l_sys_xcvrs                             : integer := 1;
		prof6_num_xcvr_per_sys                        : integer := 1;
		prof6_fec_en                                  : integer := 0;
		prof6_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		prof6_l_sys_xcvrs                             : integer := 1;
		prof7_num_xcvr_per_sys                        : integer := 1;
		prof7_fec_en                                  : integer := 0;
		prof7_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		prof7_l_sys_xcvrs                             : integer := 1;
		prof8_num_xcvr_per_sys                        : integer := 1;
		prof8_fec_en                                  : integer := 0;
		prof8_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		prof8_l_sys_xcvrs                             : integer := 1;
		prof9_num_xcvr_per_sys                        : integer := 1;
		prof9_fec_en                                  : integer := 0;
		prof9_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		prof9_l_sys_xcvrs                             : integer := 1;
		prof10_num_xcvr_per_sys                       : integer := 1;
		prof10_fec_en                                 : integer := 0;
		prof10_l_fec_mode                             : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		prof10_l_sys_xcvrs                            : integer := 1;
		prof11_num_xcvr_per_sys                       : integer := 1;
		prof11_fec_en                                 : integer := 0;
		prof11_l_fec_mode                             : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
		prof11_l_sys_xcvrs                            : integer := 1;
		bb_f_ehip_rx_fec_enable                       : string  := "RX_FEC_ENABLE_DISABLED";
		bb_f_ehip_tx_fec_enable                       : string  := "TX_FEC_ENABLE_DISABLED";
		bb_f_ehip_xcvr_mode                           : string  := "XCVR_MODE_NRZ";
		bb_f_ehip_xcvr_type                           : string  := "XCVR_TYPE_UX";
		bb_f_ux_tx_tuning_hint                        : string  := "TX_TUNING_HINT_DISABLED";
		bb_f_ux_rx_tuning_hint                        : string  := "RX_TUNING_HINT_DISABLED";
		tx_custom_cadence_enable                      : integer := 0;
		enable_port_tx_cadence_slow_clk_locked        : integer := 0;
		pldif_tx_fifo_mode                            : string  := "phase_comp";
		pldif_tx_double_width_transfer_enable         : integer := 1;
		pldif_rx_double_width_transfer_enable         : integer := 1;
		prof0_tx_custom_cadence_enable                : integer := 0;
		prof0_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
		prof0_pldif_tx_fifo_mode                      : string  := "phase_comp";
		prof0_pldif_tx_double_width_transfer_enable   : integer := 1;
		prof0_pldif_rx_double_width_transfer_enable   : integer := 1;
		prof1_tx_custom_cadence_enable                : integer := 0;
		prof1_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
		prof1_pldif_tx_fifo_mode                      : string  := "phase_comp";
		prof1_pldif_tx_double_width_transfer_enable   : integer := 1;
		prof1_pldif_rx_double_width_transfer_enable   : integer := 1;
		prof2_tx_custom_cadence_enable                : integer := 0;
		prof2_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
		prof2_pldif_tx_fifo_mode                      : string  := "phase_comp";
		prof2_pldif_tx_double_width_transfer_enable   : integer := 1;
		prof2_pldif_rx_double_width_transfer_enable   : integer := 1;
		prof3_tx_custom_cadence_enable                : integer := 0;
		prof3_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
		prof3_pldif_tx_fifo_mode                      : string  := "phase_comp";
		prof3_pldif_tx_double_width_transfer_enable   : integer := 1;
		prof3_pldif_rx_double_width_transfer_enable   : integer := 1;
		prof4_tx_custom_cadence_enable                : integer := 0;
		prof4_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
		prof4_pldif_tx_fifo_mode                      : string  := "phase_comp";
		prof4_pldif_tx_double_width_transfer_enable   : integer := 1;
		prof4_pldif_rx_double_width_transfer_enable   : integer := 1;
		prof5_tx_custom_cadence_enable                : integer := 0;
		prof5_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
		prof5_pldif_tx_fifo_mode                      : string  := "phase_comp";
		prof5_pldif_tx_double_width_transfer_enable   : integer := 1;
		prof5_pldif_rx_double_width_transfer_enable   : integer := 1;
		prof6_tx_custom_cadence_enable                : integer := 0;
		prof6_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
		prof6_pldif_tx_fifo_mode                      : string  := "phase_comp";
		prof6_pldif_tx_double_width_transfer_enable   : integer := 1;
		prof6_pldif_rx_double_width_transfer_enable   : integer := 1;
		prof7_tx_custom_cadence_enable                : integer := 0;
		prof7_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
		prof7_pldif_tx_fifo_mode                      : string  := "phase_comp";
		prof7_pldif_tx_double_width_transfer_enable   : integer := 1;
		prof7_pldif_rx_double_width_transfer_enable   : integer := 1;
		prof8_tx_custom_cadence_enable                : integer := 0;
		prof8_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
		prof8_pldif_tx_fifo_mode                      : string  := "phase_comp";
		prof8_pldif_tx_double_width_transfer_enable   : integer := 1;
		prof8_pldif_rx_double_width_transfer_enable   : integer := 1;
		prof9_tx_custom_cadence_enable                : integer := 0;
		prof9_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
		prof9_pldif_tx_fifo_mode                      : string  := "phase_comp";
		prof9_pldif_tx_double_width_transfer_enable   : integer := 1;
		prof9_pldif_rx_double_width_transfer_enable   : integer := 1;
		prof10_tx_custom_cadence_enable               : integer := 0;
		prof10_enable_port_tx_cadence_slow_clk_locked : integer := 0;
		prof10_pldif_tx_fifo_mode                     : string  := "phase_comp";
		prof10_pldif_tx_double_width_transfer_enable  : integer := 1;
		prof10_pldif_rx_double_width_transfer_enable  : integer := 1;
		prof11_tx_custom_cadence_enable               : integer := 0;
		prof11_enable_port_tx_cadence_slow_clk_locked : integer := 0;
		prof11_pldif_tx_fifo_mode                     : string  := "phase_comp";
		prof11_pldif_tx_double_width_transfer_enable  : integer := 1;
		prof11_pldif_rx_double_width_transfer_enable  : integer := 1
	);
	port (
		i_rx_cdr_refclk_p    : in  std_logic_vector(num_sys_cop-1 downto 0)      := (others => '0'); --    i_rx_cdr_refclk_p.clk,                  The connection made from "Reference and SystemPLL Clocks IP" to this pin will guide Quartus on properly setting clock network.
		i_pma_cu_clk         : in  std_logic_vector(l_quad_num-1 downto 0)       := (others => '0'); --         i_pma_cu_clk.clk,                  The connection made from "Reference and SystemPLL Clocks IP" to this pin will guide Quartus on properly setting clock network.
		i_rx_reset           : in  std_logic_vector(num_sys_cop-1 downto 0)      := (others => '0'); --           i_rx_reset.rx_reset,             RX reset input for RX XCVRs and RX datapath. Must be kept asserted until rx_reset_ack is asserted.
		o_rx_reset_ack       : out std_logic_vector(num_sys_cop-1 downto 0);                         --       o_rx_reset_ack.rx_reset_ack,         RX fully in reset indicator.
		o_rx_ready           : out std_logic_vector(num_sys_cop-1 downto 0);                         --           o_rx_ready.rx_ready,             RX de-skew NOT enabled: Status port to indicate when RX XCVRs and RX datapath are reset successfully and ready for data transfer. RX de-skew enabled: Status port to indicate when RX XCVRs and RX datapath are reset successfully, RX de-skew is done, and ready for data transfer.
		i_rx_coreclkin       : in  std_logic                                     := '0';             --       i_rx_coreclkin.i_rx_coreclkin,       RX parallel clock input.
		o_rx_clkout          : out std_logic;                                                        --          o_rx_clkout.o_rx_clkout,          Clockout ports are driven by word, bond or system pll clocks depending on customer selection for the source.
		i_src_rs_grant       : in  std_logic_vector(l_sys_xcvrs-1 downto 0)      := (others => '0'); --       i_src_rs_grant.src_rs_grant,         Grant Signal
		o_src_rs_req         : out std_logic_vector(l_sys_xcvrs-1 downto 0);                         --         o_src_rs_req.src_rs_req,           Request Signal
		o_refclk_bus_out     : out std_logic;                                                        --     o_refclk_bus_out.refclk_bus_out,       Clkrx refclk fail status
		i_rx_serial_data     : in  std_logic_vector(l_sys_xcvrs-1 downto 0)      := (others => '0'); --     i_rx_serial_data.i_rx_serial_data,     RX serial data port.
		i_rx_serial_data_n   : in  std_logic_vector(l_sys_xcvrs-1 downto 0)      := (others => '0'); --   i_rx_serial_data_n.i_rx_serial_data_n,   Differential pair for RX serial data port. Historically was hidden; however now used in pam4 signal simulation model, hence needs to be connected by user.
		o_rx_is_lockedtodata : out std_logic_vector(l_sys_xcvrs-1 downto 0);                         -- o_rx_is_lockedtodata.o_rx_is_lockedtodata, RX CDR data lock status signal. 1`b0: CDR is not locked to data. 1`b1: CDR is locked to data.
		o_rx_is_lockedtoref  : out std_logic_vector(l_sys_xcvrs-1 downto 0);                         --  o_rx_is_lockedtoref.o_rx_is_lockedtoref,  CDR lock status signal. 1`b1 - CDR is frequency locked to reference clock within the PPM threshold, 1`b0 - CDR is not frequency locked within the PPM threshold.
		o_rx_parallel_data   : out std_logic_vector((l_sys_xcvrs*80)-1 downto 0)                     --   o_rx_parallel_data.o_rx_parallel_data,   RX parallel data.
	);
end entity jesd204b_core_intel_jesd204b_gts_phy_intel_directphy_gts_191_lvsxkwq;

architecture rtl of jesd204b_core_intel_jesd204b_gts_phy_intel_directphy_gts_191_lvsxkwq is
	component jesd204b_core_intel_directphy_gts_900_6idpasa_cmp is
		generic (
			num_sys_cop                                   : integer := 1;
			prof0_num_sys_cop                             : integer := 1;
			rcfg_group                                    : string  := "lanes-1";
			num_xcvr_per_sys                              : integer := 1;
			duplex_mode                                   : string  := "duplex";
			rx_deskew_en                                  : integer := 0;
			l_num_aib_per_xcvr                            : integer := 1;
			l_sys_xcvrs                                   : integer := 1;
			l_quad_num                                    : integer := 1;
			l_sys_xcvrs_cascade                           : integer := 1;
			l_sys_aibs                                    : integer := 1;
			l_tx_enable                                   : integer := 1;
			l_rx_enable                                   : integer := 1;
			fec_en                                        : integer := 0;
			l_fec_mode                                    : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			l_av1_enable                                  : integer := 0;
			avmm1_readdv_enable                           : integer := 1;
			avmm1_split                                   : integer := 0;
			avmm1_jtag_enable                             : integer := 0;
			l_av1_aib_enable                              : integer := 0;
			l_soft_csr_enable                             : integer := 0;
			l_soft_csr_enable_rphy                        : integer := 0;
			l_num_avmm1                                   : integer := 0;
			l_av1_ifaces                                  : integer := 0;
			l_av1_addr_bits                               : integer := 0;
			l_line_rate_p1ghz                             : integer := 0;
			l_av1_enable_rphy                             : integer := 0;
			avmm1_readdv_enable_rphy                      : integer := 1;
			avmm1_jtag_enable_rphy                        : integer := 0;
			silicon_revision                              : string  := "14nm5bcr3a";
			device_revision                               : string  := "14nm5bcr3a";
			enable_port_latency_measurement               : integer := 0;
			l_rx_deskew_enable                            : integer := 1;
			txparalleldata_width                          : integer := 80;
			txsimpleinterface_enable                      : integer := 1;
			simulation_sip_only                           : integer := 0;
			simulation_only                               : integer := 0;
			prof0_num_xcvr_per_sys                        : integer := 1;
			prof0_fec_en                                  : integer := 0;
			prof0_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			prof0_l_sys_xcvrs                             : integer := 1;
			prof1_num_xcvr_per_sys                        : integer := 1;
			prof1_fec_en                                  : integer := 0;
			prof1_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			prof1_l_sys_xcvrs                             : integer := 1;
			prof2_num_xcvr_per_sys                        : integer := 1;
			prof2_fec_en                                  : integer := 0;
			prof2_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			prof2_l_sys_xcvrs                             : integer := 1;
			prof3_num_xcvr_per_sys                        : integer := 1;
			prof3_fec_en                                  : integer := 0;
			prof3_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			prof3_l_sys_xcvrs                             : integer := 1;
			prof4_num_xcvr_per_sys                        : integer := 1;
			prof4_fec_en                                  : integer := 0;
			prof4_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			prof4_l_sys_xcvrs                             : integer := 1;
			prof5_num_xcvr_per_sys                        : integer := 1;
			prof5_fec_en                                  : integer := 0;
			prof5_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			prof5_l_sys_xcvrs                             : integer := 1;
			prof6_num_xcvr_per_sys                        : integer := 1;
			prof6_fec_en                                  : integer := 0;
			prof6_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			prof6_l_sys_xcvrs                             : integer := 1;
			prof7_num_xcvr_per_sys                        : integer := 1;
			prof7_fec_en                                  : integer := 0;
			prof7_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			prof7_l_sys_xcvrs                             : integer := 1;
			prof8_num_xcvr_per_sys                        : integer := 1;
			prof8_fec_en                                  : integer := 0;
			prof8_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			prof8_l_sys_xcvrs                             : integer := 1;
			prof9_num_xcvr_per_sys                        : integer := 1;
			prof9_fec_en                                  : integer := 0;
			prof9_l_fec_mode                              : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			prof9_l_sys_xcvrs                             : integer := 1;
			prof10_num_xcvr_per_sys                       : integer := 1;
			prof10_fec_en                                 : integer := 0;
			prof10_l_fec_mode                             : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			prof10_l_sys_xcvrs                            : integer := 1;
			prof11_num_xcvr_per_sys                       : integer := 1;
			prof11_fec_en                                 : integer := 0;
			prof11_l_fec_mode                             : string  := "IEEE 802.3 BASE-R Firecode (CL 74)";
			prof11_l_sys_xcvrs                            : integer := 1;
			bb_f_ehip_rx_fec_enable                       : string  := "RX_FEC_ENABLE_DISABLED";
			bb_f_ehip_tx_fec_enable                       : string  := "TX_FEC_ENABLE_DISABLED";
			bb_f_ehip_xcvr_mode                           : string  := "XCVR_MODE_NRZ";
			bb_f_ehip_xcvr_type                           : string  := "XCVR_TYPE_UX";
			bb_f_ux_tx_tuning_hint                        : string  := "TX_TUNING_HINT_DISABLED";
			bb_f_ux_rx_tuning_hint                        : string  := "RX_TUNING_HINT_DISABLED";
			tx_custom_cadence_enable                      : integer := 0;
			enable_port_tx_cadence_slow_clk_locked        : integer := 0;
			pldif_tx_fifo_mode                            : string  := "phase_comp";
			pldif_tx_double_width_transfer_enable         : integer := 1;
			pldif_rx_double_width_transfer_enable         : integer := 1;
			prof0_tx_custom_cadence_enable                : integer := 0;
			prof0_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
			prof0_pldif_tx_fifo_mode                      : string  := "phase_comp";
			prof0_pldif_tx_double_width_transfer_enable   : integer := 1;
			prof0_pldif_rx_double_width_transfer_enable   : integer := 1;
			prof1_tx_custom_cadence_enable                : integer := 0;
			prof1_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
			prof1_pldif_tx_fifo_mode                      : string  := "phase_comp";
			prof1_pldif_tx_double_width_transfer_enable   : integer := 1;
			prof1_pldif_rx_double_width_transfer_enable   : integer := 1;
			prof2_tx_custom_cadence_enable                : integer := 0;
			prof2_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
			prof2_pldif_tx_fifo_mode                      : string  := "phase_comp";
			prof2_pldif_tx_double_width_transfer_enable   : integer := 1;
			prof2_pldif_rx_double_width_transfer_enable   : integer := 1;
			prof3_tx_custom_cadence_enable                : integer := 0;
			prof3_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
			prof3_pldif_tx_fifo_mode                      : string  := "phase_comp";
			prof3_pldif_tx_double_width_transfer_enable   : integer := 1;
			prof3_pldif_rx_double_width_transfer_enable   : integer := 1;
			prof4_tx_custom_cadence_enable                : integer := 0;
			prof4_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
			prof4_pldif_tx_fifo_mode                      : string  := "phase_comp";
			prof4_pldif_tx_double_width_transfer_enable   : integer := 1;
			prof4_pldif_rx_double_width_transfer_enable   : integer := 1;
			prof5_tx_custom_cadence_enable                : integer := 0;
			prof5_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
			prof5_pldif_tx_fifo_mode                      : string  := "phase_comp";
			prof5_pldif_tx_double_width_transfer_enable   : integer := 1;
			prof5_pldif_rx_double_width_transfer_enable   : integer := 1;
			prof6_tx_custom_cadence_enable                : integer := 0;
			prof6_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
			prof6_pldif_tx_fifo_mode                      : string  := "phase_comp";
			prof6_pldif_tx_double_width_transfer_enable   : integer := 1;
			prof6_pldif_rx_double_width_transfer_enable   : integer := 1;
			prof7_tx_custom_cadence_enable                : integer := 0;
			prof7_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
			prof7_pldif_tx_fifo_mode                      : string  := "phase_comp";
			prof7_pldif_tx_double_width_transfer_enable   : integer := 1;
			prof7_pldif_rx_double_width_transfer_enable   : integer := 1;
			prof8_tx_custom_cadence_enable                : integer := 0;
			prof8_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
			prof8_pldif_tx_fifo_mode                      : string  := "phase_comp";
			prof8_pldif_tx_double_width_transfer_enable   : integer := 1;
			prof8_pldif_rx_double_width_transfer_enable   : integer := 1;
			prof9_tx_custom_cadence_enable                : integer := 0;
			prof9_enable_port_tx_cadence_slow_clk_locked  : integer := 0;
			prof9_pldif_tx_fifo_mode                      : string  := "phase_comp";
			prof9_pldif_tx_double_width_transfer_enable   : integer := 1;
			prof9_pldif_rx_double_width_transfer_enable   : integer := 1;
			prof10_tx_custom_cadence_enable               : integer := 0;
			prof10_enable_port_tx_cadence_slow_clk_locked : integer := 0;
			prof10_pldif_tx_fifo_mode                     : string  := "phase_comp";
			prof10_pldif_tx_double_width_transfer_enable  : integer := 1;
			prof10_pldif_rx_double_width_transfer_enable  : integer := 1;
			prof11_tx_custom_cadence_enable               : integer := 0;
			prof11_enable_port_tx_cadence_slow_clk_locked : integer := 0;
			prof11_pldif_tx_fifo_mode                     : string  := "phase_comp";
			prof11_pldif_tx_double_width_transfer_enable  : integer := 1;
			prof11_pldif_rx_double_width_transfer_enable  : integer := 1
		);
		port (
			i_rx_cdr_refclk_p              : in  std_logic_vector(num_sys_cop-1 downto 0)      := (others => 'X'); -- clk
			i_pma_cu_clk                   : in  std_logic_vector(l_quad_num-1 downto 0)       := (others => 'X'); -- clk
			i_rx_reset                     : in  std_logic_vector(num_sys_cop-1 downto 0)      := (others => 'X'); -- rx_reset
			o_rx_reset_ack                 : out std_logic_vector(num_sys_cop-1 downto 0);                         -- rx_reset_ack
			o_rx_ready                     : out std_logic_vector(num_sys_cop-1 downto 0);                         -- rx_ready
			i_rx_coreclkin                 : in  std_logic                                     := 'X';             -- i_rx_coreclkin
			o_rx_clkout                    : out std_logic;                                                        -- o_rx_clkout
			i_src_rs_grant                 : in  std_logic_vector(l_sys_xcvrs-1 downto 0)      := (others => 'X'); -- src_rs_grant
			o_src_rs_req                   : out std_logic_vector(l_sys_xcvrs-1 downto 0);                         -- src_rs_req
			o_refclk_bus_out               : out std_logic;                                                        -- refclk_bus_out
			i_rx_serial_data               : in  std_logic_vector(l_sys_xcvrs-1 downto 0)      := (others => 'X'); -- i_rx_serial_data
			i_rx_serial_data_n             : in  std_logic_vector(l_sys_xcvrs-1 downto 0)      := (others => 'X'); -- i_rx_serial_data_n
			o_rx_is_lockedtodata           : out std_logic_vector(l_sys_xcvrs-1 downto 0);                         -- o_rx_is_lockedtodata
			o_rx_is_lockedtoref            : out std_logic_vector(l_sys_xcvrs-1 downto 0);                         -- o_rx_is_lockedtoref
			o_rx_parallel_data             : out std_logic_vector((l_sys_xcvrs*80)-1 downto 0);                    -- o_rx_parallel_data
			o_rx_cdr_divclk                : out std_logic_vector(0 downto 0);                                     -- clk
			i_tx_pll_refclk_p              : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- clk
			i_system_pll_clk               : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- clk
			i_system_pll_lock              : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- system_pll_lock
			i_tx_reset                     : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- tx_reset
			o_tx_reset_ack                 : out std_logic_vector(0 downto 0);                                     -- tx_reset_ack
			o_tx_ready                     : out std_logic_vector(0 downto 0);                                     -- tx_ready
			i_tx_coreclkin                 : in  std_logic                                     := 'X';             -- i_tx_coreclkin
			o_tx_clkout                    : out std_logic;                                                        -- o_tx_clkout
			o_tx_clkout2                   : out std_logic;                                                        -- o_tx_clkout2
			o_rx_clkout2                   : out std_logic;                                                        -- o_rx_clkout2
			o_tx_cadence                   : out std_logic_vector(0 downto 0);                                     -- tx_cadence
			i_tx_cadence_fast_clk          : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- clk
			i_tx_cadence_slow_clk          : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- clk
			i_tx_cadence_slow_clk_locked   : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- tx_cadence_slow_clk_locked
			i_det_lat_rx_dl_clk            : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- clk
			i_det_lat_rx_mux_select        : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- det_lat_rx_mux_select
			i_det_lat_rx_sclk_flop         : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- det_lat_rx_sclk_flop
			i_det_lat_rx_sclk_gen_clk      : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- clk
			i_det_lat_rx_trig_flop         : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- det_lat_rx_trig_flop
			i_det_lat_sampling_clk         : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- clk
			i_det_lat_tx_dl_clk            : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- clk
			i_det_lat_tx_mux_select        : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- det_lat_tx_mux_select
			i_det_lat_tx_sclk_flop         : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- det_lat_tx_sclk_flop
			i_det_lat_tx_sclk_gen_clk      : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- clk
			i_det_lat_tx_trig_flop         : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- det_lat_tx_trig_flop
			o_det_lat_rx_async_dl_sync     : out std_logic_vector(0 downto 0);                                     -- det_lat_rx_async_dl_sync
			o_det_lat_rx_async_pulse       : out std_logic_vector(0 downto 0);                                     -- det_lat_rx_async_pulse
			o_det_lat_rx_async_sample_sync : out std_logic_vector(0 downto 0);                                     -- det_lat_rx_async_sample_sync
			o_det_lat_rx_sclk_sample_sync  : out std_logic_vector(0 downto 0);                                     -- det_lat_rx_sclk_sample_sync
			o_det_lat_rx_trig_sample_sync  : out std_logic_vector(0 downto 0);                                     -- det_lat_rx_trig_sample_sync
			o_det_lat_tx_async_dl_sync     : out std_logic_vector(0 downto 0);                                     -- det_lat_tx_async_dl_sync
			o_det_lat_tx_async_pulse       : out std_logic_vector(0 downto 0);                                     -- det_lat_tx_async_pulse
			o_det_lat_tx_async_sample_sync : out std_logic_vector(0 downto 0);                                     -- det_lat_tx_async_sample_sync
			o_det_lat_tx_sclk_sample_sync  : out std_logic_vector(0 downto 0);                                     -- det_lat_tx_sclk_sample_sync
			o_det_lat_tx_trig_sample_sync  : out std_logic_vector(0 downto 0);                                     -- det_lat_tx_trig_sample_sync
			o_xcvrif_rx_latency_pulse      : out std_logic_vector(0 downto 0);                                     -- xcvrif_rx_latency_pulse
			o_xcvrif_tx_latency_pulse      : out std_logic_vector(0 downto 0);                                     -- xcvrif_tx_latency_pulse
			i_pma_async                    : in  std_logic_vector(79 downto 0)                 := (others => 'X'); -- i_pma_async
			i_pma_async_pcie_mux           : in  std_logic_vector(79 downto 0)                 := (others => 'X'); -- i_pma_async_pcie_mux
			o_pma_async                    : out std_logic_vector(49 downto 0);                                    -- o_pma_async
			i_rx_cdr_freeze                : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- i_rx_cdr_freeze
			i_rx_cdr_fast_freeze_sel       : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- i_rx_cdr_fast_freeze_sel
			o_rx_signal_detect             : out std_logic_vector(0 downto 0);                                     -- o_rx_signal_detect
			o_rx_signal_detect_lfps        : out std_logic_vector(0 downto 0);                                     -- o_rx_signal_detect_lfps
			o_tx_serial_data               : out std_logic_vector(0 downto 0);                                     -- o_tx_serial_data
			o_tx_serial_data_n             : out std_logic_vector(0 downto 0);                                     -- o_tx_serial_data_n
			o_tx_pll_locked                : out std_logic_vector(0 downto 0);                                     -- o_tx_pll_locked
			i_rx_set_locktoref             : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- i_rx_set_locktoref
			i_rx_set_locktodata            : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- i_rx_set_locktodata
			o_tx_fifo_full                 : out std_logic_vector(0 downto 0);                                     -- o_tx_fifo_full
			o_tx_fifo_empty                : out std_logic_vector(0 downto 0);                                     -- o_tx_fifo_empty
			o_tx_fifo_pfull                : out std_logic_vector(0 downto 0);                                     -- o_tx_fifo_pfull
			o_tx_fifo_pempty               : out std_logic_vector(0 downto 0);                                     -- o_tx_fifo_pempty
			o_rx_fifo_full                 : out std_logic_vector(0 downto 0);                                     -- o_rx_fifo_full
			o_rx_fifo_empty                : out std_logic_vector(0 downto 0);                                     -- o_rx_fifo_empty
			o_rx_fifo_pfull                : out std_logic_vector(0 downto 0);                                     -- o_rx_fifo_pfull
			o_rx_fifo_pempty               : out std_logic_vector(0 downto 0);                                     -- o_rx_fifo_pempty
			i_rx_fifo_rd_en                : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- i_rx_fifo_rd_en
			o_rx_pmaif_fifo_empty          : out std_logic_vector(0 downto 0);                                     -- o_rx_pmaif_fifo_empty
			o_rx_pmaif_fifo_pempty         : out std_logic_vector(0 downto 0);                                     -- o_rx_pmaif_fifo_pempty
			o_rx_pmaif_fifo_pfull          : out std_logic_vector(0 downto 0);                                     -- o_rx_pmaif_fifo_pfull
			o_tx_pmaif_fifo_empty          : out std_logic_vector(0 downto 0);                                     -- o_tx_pmaif_fifo_empty
			o_tx_pmaif_fifo_pempty         : out std_logic_vector(0 downto 0);                                     -- o_tx_pmaif_fifo_pempty
			o_tx_pmaif_fifo_pfull          : out std_logic_vector(0 downto 0);                                     -- o_tx_pmaif_fifo_pfull
			o_fec_sf                       : out std_logic_vector(0 downto 0);                                     -- o_fec_sf
			o_fec_status_rx_not_align      : out std_logic_vector(0 downto 0);                                     -- o_fec_status_rx_not_align
			o_fec_status_rx_not_deskew     : out std_logic_vector(0 downto 0);                                     -- o_fec_status_rx_not_deskew
			o_fec_status_rx_not_locked     : out std_logic_vector(0 downto 0);                                     -- o_fec_status_rx_not_locked
			i_fec_snapshot                 : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- i_fec_snapshot
			o_rx_block_lock                : out std_logic_vector(0 downto 0);                                     -- o_rx_block_lock
			o_local_fault_status           : out std_logic_vector(0 downto 0);                                     -- o_local_fault_status
			o_rx_hi_ber                    : out std_logic_vector(0 downto 0);                                     -- o_rx_hi_ber
			o_rx_pcs_fully_aligned         : out std_logic_vector(0 downto 0);                                     -- o_rx_pcs_fully_aligned
			o_refclk2core                  : out std_logic_vector(0 downto 0);                                     -- o_refclk2core
			i_tx_parallel_data             : in  std_logic_vector(79 downto 0)                 := (others => 'X'); -- i_tx_parallel_data
			i_tx_pma_elecidle_sync         : in  std_logic_vector(3 downto 0)                  := (others => 'X'); -- i_tx_pma_elecidle_sync
			i_txclkdivrate_sync            : in  std_logic_vector(2 downto 0)                  := (others => 'X'); -- i_txclkdivrate_sync
			i_reconfig_clk                 : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- clk
			i_reconfig_reset               : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- reset
			i_reconfig_write               : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- write
			i_reconfig_read                : in  std_logic_vector(0 downto 0)                  := (others => 'X'); -- read
			i_reconfig_address             : in  std_logic_vector(17 downto 0)                 := (others => 'X'); -- address
			i_reconfig_byteenable          : in  std_logic_vector(3 downto 0)                  := (others => 'X'); -- byteenable
			i_reconfig_writedata           : in  std_logic_vector(31 downto 0)                 := (others => 'X'); -- writedata
			o_reconfig_readdata            : out std_logic_vector(31 downto 0);                                    -- readdata
			o_reconfig_waitrequest         : out std_logic_vector(0 downto 0);                                     -- waitrequest
			o_reconfig_readdatavalid       : out std_logic_vector(0 downto 0)                                      -- readdatavalid
		);
	end component jesd204b_core_intel_directphy_gts_900_6idpasa_cmp;

	for inst_directphy_1 : jesd204b_core_intel_directphy_gts_900_6idpasa_cmp
		use entity intel_directphy_gts_900.jesd204b_core_intel_directphy_gts_900_6idpasa;
begin

	num_sys_cop_check : if num_sys_cop /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof0_num_sys_cop_check : if prof0_num_sys_cop /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	rcfg_group_check : if rcfg_group /= "lanes-1" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	num_xcvr_per_sys_check : if num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	duplex_mode_check : if duplex_mode /= "rx" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	rx_deskew_en_check : if rx_deskew_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_num_aib_per_xcvr_check : if l_num_aib_per_xcvr /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_sys_xcvrs_check : if l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_quad_num_check : if l_quad_num /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_sys_xcvrs_cascade_check : if l_sys_xcvrs_cascade /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_sys_aibs_check : if l_sys_aibs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_tx_enable_check : if l_tx_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_rx_enable_check : if l_rx_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	fec_en_check : if fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_fec_mode_check : if l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_av1_enable_check : if l_av1_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	avmm1_readdv_enable_check : if avmm1_readdv_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	avmm1_split_check : if avmm1_split /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	avmm1_jtag_enable_check : if avmm1_jtag_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_av1_aib_enable_check : if l_av1_aib_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_soft_csr_enable_check : if l_soft_csr_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_soft_csr_enable_rphy_check : if l_soft_csr_enable_rphy /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_num_avmm1_check : if l_num_avmm1 /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_av1_ifaces_check : if l_av1_ifaces /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_av1_addr_bits_check : if l_av1_addr_bits /= 18 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_line_rate_p1ghz_check : if l_line_rate_p1ghz /= 100 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_av1_enable_rphy_check : if l_av1_enable_rphy /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	avmm1_readdv_enable_rphy_check : if avmm1_readdv_enable_rphy /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	avmm1_jtag_enable_rphy_check : if avmm1_jtag_enable_rphy /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	silicon_revision_check : if silicon_revision /= "14nm5bcr3a" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	device_revision_check : if device_revision /= "14nm5bcr3a" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	enable_port_latency_measurement_check : if enable_port_latency_measurement /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	l_rx_deskew_enable_check : if l_rx_deskew_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	txparalleldata_width_check : if txparalleldata_width /= 80 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	txsimpleinterface_enable_check : if txsimpleinterface_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	simulation_sip_only_check : if simulation_sip_only /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	simulation_only_check : if simulation_only /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof0_num_xcvr_per_sys_check : if prof0_num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof0_fec_en_check : if prof0_fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof0_l_fec_mode_check : if prof0_l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof0_l_sys_xcvrs_check : if prof0_l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof1_num_xcvr_per_sys_check : if prof1_num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof1_fec_en_check : if prof1_fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof1_l_fec_mode_check : if prof1_l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof1_l_sys_xcvrs_check : if prof1_l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof2_num_xcvr_per_sys_check : if prof2_num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof2_fec_en_check : if prof2_fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof2_l_fec_mode_check : if prof2_l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof2_l_sys_xcvrs_check : if prof2_l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof3_num_xcvr_per_sys_check : if prof3_num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof3_fec_en_check : if prof3_fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof3_l_fec_mode_check : if prof3_l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof3_l_sys_xcvrs_check : if prof3_l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof4_num_xcvr_per_sys_check : if prof4_num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof4_fec_en_check : if prof4_fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof4_l_fec_mode_check : if prof4_l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof4_l_sys_xcvrs_check : if prof4_l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof5_num_xcvr_per_sys_check : if prof5_num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof5_fec_en_check : if prof5_fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof5_l_fec_mode_check : if prof5_l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof5_l_sys_xcvrs_check : if prof5_l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof6_num_xcvr_per_sys_check : if prof6_num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof6_fec_en_check : if prof6_fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof6_l_fec_mode_check : if prof6_l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof6_l_sys_xcvrs_check : if prof6_l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof7_num_xcvr_per_sys_check : if prof7_num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof7_fec_en_check : if prof7_fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof7_l_fec_mode_check : if prof7_l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof7_l_sys_xcvrs_check : if prof7_l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof8_num_xcvr_per_sys_check : if prof8_num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof8_fec_en_check : if prof8_fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof8_l_fec_mode_check : if prof8_l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof8_l_sys_xcvrs_check : if prof8_l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof9_num_xcvr_per_sys_check : if prof9_num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof9_fec_en_check : if prof9_fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof9_l_fec_mode_check : if prof9_l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof9_l_sys_xcvrs_check : if prof9_l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof10_num_xcvr_per_sys_check : if prof10_num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof10_fec_en_check : if prof10_fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof10_l_fec_mode_check : if prof10_l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof10_l_sys_xcvrs_check : if prof10_l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof11_num_xcvr_per_sys_check : if prof11_num_xcvr_per_sys /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof11_fec_en_check : if prof11_fec_en /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof11_l_fec_mode_check : if prof11_l_fec_mode /= "IEEE 802.3 BASE-R Firecode (CL 74)" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof11_l_sys_xcvrs_check : if prof11_l_sys_xcvrs /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	bb_f_ehip_rx_fec_enable_check : if bb_f_ehip_rx_fec_enable /= "RX_FEC_ENABLE_DISABLED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	bb_f_ehip_tx_fec_enable_check : if bb_f_ehip_tx_fec_enable /= "TX_FEC_ENABLE_DISABLED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	bb_f_ehip_xcvr_mode_check : if bb_f_ehip_xcvr_mode /= "XCVR_MODE_NRZ" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	bb_f_ehip_xcvr_type_check : if bb_f_ehip_xcvr_type /= "XCVR_TYPE_UX" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	bb_f_ux_tx_tuning_hint_check : if bb_f_ux_tx_tuning_hint /= "TX_TUNING_HINT_DISABLED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	bb_f_ux_rx_tuning_hint_check : if bb_f_ux_rx_tuning_hint /= "RX_TUNING_HINT_DISABLED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	tx_custom_cadence_enable_check : if tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	enable_port_tx_cadence_slow_clk_locked_check : if enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	pldif_tx_fifo_mode_check : if pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	pldif_tx_double_width_transfer_enable_check : if pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	pldif_rx_double_width_transfer_enable_check : if pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof0_tx_custom_cadence_enable_check : if prof0_tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof0_enable_port_tx_cadence_slow_clk_locked_check : if prof0_enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof0_pldif_tx_fifo_mode_check : if prof0_pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof0_pldif_tx_double_width_transfer_enable_check : if prof0_pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof0_pldif_rx_double_width_transfer_enable_check : if prof0_pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof1_tx_custom_cadence_enable_check : if prof1_tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof1_enable_port_tx_cadence_slow_clk_locked_check : if prof1_enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof1_pldif_tx_fifo_mode_check : if prof1_pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof1_pldif_tx_double_width_transfer_enable_check : if prof1_pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof1_pldif_rx_double_width_transfer_enable_check : if prof1_pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof2_tx_custom_cadence_enable_check : if prof2_tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof2_enable_port_tx_cadence_slow_clk_locked_check : if prof2_enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof2_pldif_tx_fifo_mode_check : if prof2_pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof2_pldif_tx_double_width_transfer_enable_check : if prof2_pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof2_pldif_rx_double_width_transfer_enable_check : if prof2_pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof3_tx_custom_cadence_enable_check : if prof3_tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof3_enable_port_tx_cadence_slow_clk_locked_check : if prof3_enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof3_pldif_tx_fifo_mode_check : if prof3_pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof3_pldif_tx_double_width_transfer_enable_check : if prof3_pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof3_pldif_rx_double_width_transfer_enable_check : if prof3_pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof4_tx_custom_cadence_enable_check : if prof4_tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof4_enable_port_tx_cadence_slow_clk_locked_check : if prof4_enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof4_pldif_tx_fifo_mode_check : if prof4_pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof4_pldif_tx_double_width_transfer_enable_check : if prof4_pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof4_pldif_rx_double_width_transfer_enable_check : if prof4_pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof5_tx_custom_cadence_enable_check : if prof5_tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof5_enable_port_tx_cadence_slow_clk_locked_check : if prof5_enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof5_pldif_tx_fifo_mode_check : if prof5_pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof5_pldif_tx_double_width_transfer_enable_check : if prof5_pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof5_pldif_rx_double_width_transfer_enable_check : if prof5_pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof6_tx_custom_cadence_enable_check : if prof6_tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof6_enable_port_tx_cadence_slow_clk_locked_check : if prof6_enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof6_pldif_tx_fifo_mode_check : if prof6_pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof6_pldif_tx_double_width_transfer_enable_check : if prof6_pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof6_pldif_rx_double_width_transfer_enable_check : if prof6_pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof7_tx_custom_cadence_enable_check : if prof7_tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof7_enable_port_tx_cadence_slow_clk_locked_check : if prof7_enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof7_pldif_tx_fifo_mode_check : if prof7_pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof7_pldif_tx_double_width_transfer_enable_check : if prof7_pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof7_pldif_rx_double_width_transfer_enable_check : if prof7_pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof8_tx_custom_cadence_enable_check : if prof8_tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof8_enable_port_tx_cadence_slow_clk_locked_check : if prof8_enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof8_pldif_tx_fifo_mode_check : if prof8_pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof8_pldif_tx_double_width_transfer_enable_check : if prof8_pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof8_pldif_rx_double_width_transfer_enable_check : if prof8_pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof9_tx_custom_cadence_enable_check : if prof9_tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof9_enable_port_tx_cadence_slow_clk_locked_check : if prof9_enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof9_pldif_tx_fifo_mode_check : if prof9_pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof9_pldif_tx_double_width_transfer_enable_check : if prof9_pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof9_pldif_rx_double_width_transfer_enable_check : if prof9_pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof10_tx_custom_cadence_enable_check : if prof10_tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof10_enable_port_tx_cadence_slow_clk_locked_check : if prof10_enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof10_pldif_tx_fifo_mode_check : if prof10_pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof10_pldif_tx_double_width_transfer_enable_check : if prof10_pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof10_pldif_rx_double_width_transfer_enable_check : if prof10_pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof11_tx_custom_cadence_enable_check : if prof11_tx_custom_cadence_enable /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof11_enable_port_tx_cadence_slow_clk_locked_check : if prof11_enable_port_tx_cadence_slow_clk_locked /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof11_pldif_tx_fifo_mode_check : if prof11_pldif_tx_fifo_mode /= "phase_comp" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof11_pldif_tx_double_width_transfer_enable_check : if prof11_pldif_tx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	prof11_pldif_rx_double_width_transfer_enable_check : if prof11_pldif_rx_double_width_transfer_enable /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inst_directphy_1 : component jesd204b_core_intel_directphy_gts_900_6idpasa_cmp
		generic map (
			num_sys_cop                                   => 1,
			prof0_num_sys_cop                             => 1,
			rcfg_group                                    => "lanes-1",
			num_xcvr_per_sys                              => 1,
			duplex_mode                                   => "rx",
			rx_deskew_en                                  => 0,
			l_num_aib_per_xcvr                            => 1,
			l_sys_xcvrs                                   => 1,
			l_quad_num                                    => 1,
			l_sys_xcvrs_cascade                           => 1,
			l_sys_aibs                                    => 1,
			l_tx_enable                                   => 0,
			l_rx_enable                                   => 1,
			fec_en                                        => 0,
			l_fec_mode                                    => "IEEE 802.3 BASE-R Firecode (CL 74)",
			l_av1_enable                                  => 0,
			avmm1_readdv_enable                           => 1,
			avmm1_split                                   => 0,
			avmm1_jtag_enable                             => 0,
			l_av1_aib_enable                              => 0,
			l_soft_csr_enable                             => 0,
			l_soft_csr_enable_rphy                        => 0,
			l_num_avmm1                                   => 1,
			l_av1_ifaces                                  => 1,
			l_av1_addr_bits                               => 18,
			l_line_rate_p1ghz                             => 100,
			l_av1_enable_rphy                             => 0,
			avmm1_readdv_enable_rphy                      => 1,
			avmm1_jtag_enable_rphy                        => 0,
			silicon_revision                              => "14nm5bcr3a",
			device_revision                               => "14nm5bcr3a",
			enable_port_latency_measurement               => 0,
			l_rx_deskew_enable                            => 0,
			txparalleldata_width                          => 80,
			txsimpleinterface_enable                      => 0,
			simulation_sip_only                           => 0,
			simulation_only                               => 0,
			prof0_num_xcvr_per_sys                        => 1,
			prof0_fec_en                                  => 0,
			prof0_l_fec_mode                              => "IEEE 802.3 BASE-R Firecode (CL 74)",
			prof0_l_sys_xcvrs                             => 1,
			prof1_num_xcvr_per_sys                        => 1,
			prof1_fec_en                                  => 0,
			prof1_l_fec_mode                              => "IEEE 802.3 BASE-R Firecode (CL 74)",
			prof1_l_sys_xcvrs                             => 1,
			prof2_num_xcvr_per_sys                        => 1,
			prof2_fec_en                                  => 0,
			prof2_l_fec_mode                              => "IEEE 802.3 BASE-R Firecode (CL 74)",
			prof2_l_sys_xcvrs                             => 1,
			prof3_num_xcvr_per_sys                        => 1,
			prof3_fec_en                                  => 0,
			prof3_l_fec_mode                              => "IEEE 802.3 BASE-R Firecode (CL 74)",
			prof3_l_sys_xcvrs                             => 1,
			prof4_num_xcvr_per_sys                        => 1,
			prof4_fec_en                                  => 0,
			prof4_l_fec_mode                              => "IEEE 802.3 BASE-R Firecode (CL 74)",
			prof4_l_sys_xcvrs                             => 1,
			prof5_num_xcvr_per_sys                        => 1,
			prof5_fec_en                                  => 0,
			prof5_l_fec_mode                              => "IEEE 802.3 BASE-R Firecode (CL 74)",
			prof5_l_sys_xcvrs                             => 1,
			prof6_num_xcvr_per_sys                        => 1,
			prof6_fec_en                                  => 0,
			prof6_l_fec_mode                              => "IEEE 802.3 BASE-R Firecode (CL 74)",
			prof6_l_sys_xcvrs                             => 1,
			prof7_num_xcvr_per_sys                        => 1,
			prof7_fec_en                                  => 0,
			prof7_l_fec_mode                              => "IEEE 802.3 BASE-R Firecode (CL 74)",
			prof7_l_sys_xcvrs                             => 1,
			prof8_num_xcvr_per_sys                        => 1,
			prof8_fec_en                                  => 0,
			prof8_l_fec_mode                              => "IEEE 802.3 BASE-R Firecode (CL 74)",
			prof8_l_sys_xcvrs                             => 1,
			prof9_num_xcvr_per_sys                        => 1,
			prof9_fec_en                                  => 0,
			prof9_l_fec_mode                              => "IEEE 802.3 BASE-R Firecode (CL 74)",
			prof9_l_sys_xcvrs                             => 1,
			prof10_num_xcvr_per_sys                       => 1,
			prof10_fec_en                                 => 0,
			prof10_l_fec_mode                             => "IEEE 802.3 BASE-R Firecode (CL 74)",
			prof10_l_sys_xcvrs                            => 1,
			prof11_num_xcvr_per_sys                       => 1,
			prof11_fec_en                                 => 0,
			prof11_l_fec_mode                             => "IEEE 802.3 BASE-R Firecode (CL 74)",
			prof11_l_sys_xcvrs                            => 1,
			bb_f_ehip_rx_fec_enable                       => "RX_FEC_ENABLE_DISABLED",
			bb_f_ehip_tx_fec_enable                       => "TX_FEC_ENABLE_DISABLED",
			bb_f_ehip_xcvr_mode                           => "XCVR_MODE_NRZ",
			bb_f_ehip_xcvr_type                           => "XCVR_TYPE_UX",
			bb_f_ux_tx_tuning_hint                        => "TX_TUNING_HINT_DISABLED",
			bb_f_ux_rx_tuning_hint                        => "RX_TUNING_HINT_DISABLED",
			tx_custom_cadence_enable                      => 0,
			enable_port_tx_cadence_slow_clk_locked        => 0,
			pldif_tx_fifo_mode                            => "phase_comp",
			pldif_tx_double_width_transfer_enable         => 1,
			pldif_rx_double_width_transfer_enable         => 1,
			prof0_tx_custom_cadence_enable                => 0,
			prof0_enable_port_tx_cadence_slow_clk_locked  => 0,
			prof0_pldif_tx_fifo_mode                      => "phase_comp",
			prof0_pldif_tx_double_width_transfer_enable   => 1,
			prof0_pldif_rx_double_width_transfer_enable   => 1,
			prof1_tx_custom_cadence_enable                => 0,
			prof1_enable_port_tx_cadence_slow_clk_locked  => 0,
			prof1_pldif_tx_fifo_mode                      => "phase_comp",
			prof1_pldif_tx_double_width_transfer_enable   => 1,
			prof1_pldif_rx_double_width_transfer_enable   => 1,
			prof2_tx_custom_cadence_enable                => 0,
			prof2_enable_port_tx_cadence_slow_clk_locked  => 0,
			prof2_pldif_tx_fifo_mode                      => "phase_comp",
			prof2_pldif_tx_double_width_transfer_enable   => 1,
			prof2_pldif_rx_double_width_transfer_enable   => 1,
			prof3_tx_custom_cadence_enable                => 0,
			prof3_enable_port_tx_cadence_slow_clk_locked  => 0,
			prof3_pldif_tx_fifo_mode                      => "phase_comp",
			prof3_pldif_tx_double_width_transfer_enable   => 1,
			prof3_pldif_rx_double_width_transfer_enable   => 1,
			prof4_tx_custom_cadence_enable                => 0,
			prof4_enable_port_tx_cadence_slow_clk_locked  => 0,
			prof4_pldif_tx_fifo_mode                      => "phase_comp",
			prof4_pldif_tx_double_width_transfer_enable   => 1,
			prof4_pldif_rx_double_width_transfer_enable   => 1,
			prof5_tx_custom_cadence_enable                => 0,
			prof5_enable_port_tx_cadence_slow_clk_locked  => 0,
			prof5_pldif_tx_fifo_mode                      => "phase_comp",
			prof5_pldif_tx_double_width_transfer_enable   => 1,
			prof5_pldif_rx_double_width_transfer_enable   => 1,
			prof6_tx_custom_cadence_enable                => 0,
			prof6_enable_port_tx_cadence_slow_clk_locked  => 0,
			prof6_pldif_tx_fifo_mode                      => "phase_comp",
			prof6_pldif_tx_double_width_transfer_enable   => 1,
			prof6_pldif_rx_double_width_transfer_enable   => 1,
			prof7_tx_custom_cadence_enable                => 0,
			prof7_enable_port_tx_cadence_slow_clk_locked  => 0,
			prof7_pldif_tx_fifo_mode                      => "phase_comp",
			prof7_pldif_tx_double_width_transfer_enable   => 1,
			prof7_pldif_rx_double_width_transfer_enable   => 1,
			prof8_tx_custom_cadence_enable                => 0,
			prof8_enable_port_tx_cadence_slow_clk_locked  => 0,
			prof8_pldif_tx_fifo_mode                      => "phase_comp",
			prof8_pldif_tx_double_width_transfer_enable   => 1,
			prof8_pldif_rx_double_width_transfer_enable   => 1,
			prof9_tx_custom_cadence_enable                => 0,
			prof9_enable_port_tx_cadence_slow_clk_locked  => 0,
			prof9_pldif_tx_fifo_mode                      => "phase_comp",
			prof9_pldif_tx_double_width_transfer_enable   => 1,
			prof9_pldif_rx_double_width_transfer_enable   => 1,
			prof10_tx_custom_cadence_enable               => 0,
			prof10_enable_port_tx_cadence_slow_clk_locked => 0,
			prof10_pldif_tx_fifo_mode                     => "phase_comp",
			prof10_pldif_tx_double_width_transfer_enable  => 1,
			prof10_pldif_rx_double_width_transfer_enable  => 1,
			prof11_tx_custom_cadence_enable               => 0,
			prof11_enable_port_tx_cadence_slow_clk_locked => 0,
			prof11_pldif_tx_fifo_mode                     => "phase_comp",
			prof11_pldif_tx_double_width_transfer_enable  => 1,
			prof11_pldif_rx_double_width_transfer_enable  => 1
		)
		port map (
			i_rx_cdr_refclk_p              => i_rx_cdr_refclk_p,                                                                  --    i_rx_cdr_refclk_p.clk
			i_pma_cu_clk                   => i_pma_cu_clk,                                                                       --         i_pma_cu_clk.clk
			i_rx_reset                     => i_rx_reset,                                                                         --           i_rx_reset.rx_reset
			o_rx_reset_ack                 => o_rx_reset_ack,                                                                     --       o_rx_reset_ack.rx_reset_ack
			o_rx_ready                     => o_rx_ready,                                                                         --           o_rx_ready.rx_ready
			i_rx_coreclkin                 => i_rx_coreclkin,                                                                     --       i_rx_coreclkin.i_rx_coreclkin
			o_rx_clkout                    => o_rx_clkout,                                                                        --          o_rx_clkout.o_rx_clkout
			i_src_rs_grant                 => i_src_rs_grant,                                                                     --       i_src_rs_grant.src_rs_grant
			o_src_rs_req                   => o_src_rs_req,                                                                       --         o_src_rs_req.src_rs_req
			o_refclk_bus_out               => o_refclk_bus_out,                                                                   --     o_refclk_bus_out.refclk_bus_out
			i_rx_serial_data               => i_rx_serial_data,                                                                   --     i_rx_serial_data.i_rx_serial_data
			i_rx_serial_data_n             => i_rx_serial_data_n,                                                                 --   i_rx_serial_data_n.i_rx_serial_data_n
			o_rx_is_lockedtodata           => o_rx_is_lockedtodata,                                                               -- o_rx_is_lockedtodata.o_rx_is_lockedtodata
			o_rx_is_lockedtoref            => o_rx_is_lockedtoref,                                                                --  o_rx_is_lockedtoref.o_rx_is_lockedtoref
			o_rx_parallel_data             => o_rx_parallel_data,                                                                 --   o_rx_parallel_data.o_rx_parallel_data
			o_rx_cdr_divclk                => open,                                                                               --          (terminated)
			i_tx_pll_refclk_p              => "0",                                                                                --          (terminated)
			i_system_pll_clk               => "0",                                                                                --          (terminated)
			i_system_pll_lock              => "0",                                                                                --          (terminated)
			i_tx_reset                     => "0",                                                                                --          (terminated)
			o_tx_reset_ack                 => open,                                                                               --          (terminated)
			o_tx_ready                     => open,                                                                               --          (terminated)
			i_tx_coreclkin                 => '0',                                                                                --          (terminated)
			o_tx_clkout                    => open,                                                                               --          (terminated)
			o_tx_clkout2                   => open,                                                                               --          (terminated)
			o_rx_clkout2                   => open,                                                                               --          (terminated)
			o_tx_cadence                   => open,                                                                               --          (terminated)
			i_tx_cadence_fast_clk          => "0",                                                                                --          (terminated)
			i_tx_cadence_slow_clk          => "0",                                                                                --          (terminated)
			i_tx_cadence_slow_clk_locked   => "0",                                                                                --          (terminated)
			i_det_lat_rx_dl_clk            => "0",                                                                                --          (terminated)
			i_det_lat_rx_mux_select        => "0",                                                                                --          (terminated)
			i_det_lat_rx_sclk_flop         => "0",                                                                                --          (terminated)
			i_det_lat_rx_sclk_gen_clk      => "0",                                                                                --          (terminated)
			i_det_lat_rx_trig_flop         => "0",                                                                                --          (terminated)
			i_det_lat_sampling_clk         => "0",                                                                                --          (terminated)
			i_det_lat_tx_dl_clk            => "0",                                                                                --          (terminated)
			i_det_lat_tx_mux_select        => "0",                                                                                --          (terminated)
			i_det_lat_tx_sclk_flop         => "0",                                                                                --          (terminated)
			i_det_lat_tx_sclk_gen_clk      => "0",                                                                                --          (terminated)
			i_det_lat_tx_trig_flop         => "0",                                                                                --          (terminated)
			o_det_lat_rx_async_dl_sync     => open,                                                                               --          (terminated)
			o_det_lat_rx_async_pulse       => open,                                                                               --          (terminated)
			o_det_lat_rx_async_sample_sync => open,                                                                               --          (terminated)
			o_det_lat_rx_sclk_sample_sync  => open,                                                                               --          (terminated)
			o_det_lat_rx_trig_sample_sync  => open,                                                                               --          (terminated)
			o_det_lat_tx_async_dl_sync     => open,                                                                               --          (terminated)
			o_det_lat_tx_async_pulse       => open,                                                                               --          (terminated)
			o_det_lat_tx_async_sample_sync => open,                                                                               --          (terminated)
			o_det_lat_tx_sclk_sample_sync  => open,                                                                               --          (terminated)
			o_det_lat_tx_trig_sample_sync  => open,                                                                               --          (terminated)
			o_xcvrif_rx_latency_pulse      => open,                                                                               --          (terminated)
			o_xcvrif_tx_latency_pulse      => open,                                                                               --          (terminated)
			i_pma_async                    => "00000000000000000000000000000000000000000000000000000000000000000000000000000000", --          (terminated)
			i_pma_async_pcie_mux           => "00000000000000000000000000000000000000000000000000000000000000000000000000000000", --          (terminated)
			o_pma_async                    => open,                                                                               --          (terminated)
			i_rx_cdr_freeze                => "0",                                                                                --          (terminated)
			i_rx_cdr_fast_freeze_sel       => "0",                                                                                --          (terminated)
			o_rx_signal_detect             => open,                                                                               --          (terminated)
			o_rx_signal_detect_lfps        => open,                                                                               --          (terminated)
			o_tx_serial_data               => open,                                                                               --          (terminated)
			o_tx_serial_data_n             => open,                                                                               --          (terminated)
			o_tx_pll_locked                => open,                                                                               --          (terminated)
			i_rx_set_locktoref             => "0",                                                                                --          (terminated)
			i_rx_set_locktodata            => "0",                                                                                --          (terminated)
			o_tx_fifo_full                 => open,                                                                               --          (terminated)
			o_tx_fifo_empty                => open,                                                                               --          (terminated)
			o_tx_fifo_pfull                => open,                                                                               --          (terminated)
			o_tx_fifo_pempty               => open,                                                                               --          (terminated)
			o_rx_fifo_full                 => open,                                                                               --          (terminated)
			o_rx_fifo_empty                => open,                                                                               --          (terminated)
			o_rx_fifo_pfull                => open,                                                                               --          (terminated)
			o_rx_fifo_pempty               => open,                                                                               --          (terminated)
			i_rx_fifo_rd_en                => "0",                                                                                --          (terminated)
			o_rx_pmaif_fifo_empty          => open,                                                                               --          (terminated)
			o_rx_pmaif_fifo_pempty         => open,                                                                               --          (terminated)
			o_rx_pmaif_fifo_pfull          => open,                                                                               --          (terminated)
			o_tx_pmaif_fifo_empty          => open,                                                                               --          (terminated)
			o_tx_pmaif_fifo_pempty         => open,                                                                               --          (terminated)
			o_tx_pmaif_fifo_pfull          => open,                                                                               --          (terminated)
			o_fec_sf                       => open,                                                                               --          (terminated)
			o_fec_status_rx_not_align      => open,                                                                               --          (terminated)
			o_fec_status_rx_not_deskew     => open,                                                                               --          (terminated)
			o_fec_status_rx_not_locked     => open,                                                                               --          (terminated)
			i_fec_snapshot                 => "0",                                                                                --          (terminated)
			o_rx_block_lock                => open,                                                                               --          (terminated)
			o_local_fault_status           => open,                                                                               --          (terminated)
			o_rx_hi_ber                    => open,                                                                               --          (terminated)
			o_rx_pcs_fully_aligned         => open,                                                                               --          (terminated)
			o_refclk2core                  => open,                                                                               --          (terminated)
			i_tx_parallel_data             => "00000000000000000000000000000000000000000000000000000000000000000000000000000000", --          (terminated)
			i_tx_pma_elecidle_sync         => "0000",                                                                             --          (terminated)
			i_txclkdivrate_sync            => "000",                                                                              --          (terminated)
			i_reconfig_clk                 => "0",                                                                                --          (terminated)
			i_reconfig_reset               => "0",                                                                                --          (terminated)
			i_reconfig_write               => "0",                                                                                --          (terminated)
			i_reconfig_read                => "0",                                                                                --          (terminated)
			i_reconfig_address             => "000000000000000000",                                                               --          (terminated)
			i_reconfig_byteenable          => "0000",                                                                             --          (terminated)
			i_reconfig_writedata           => "00000000000000000000000000000000",                                                 --          (terminated)
			o_reconfig_readdata            => open,                                                                               --          (terminated)
			o_reconfig_waitrequest         => open,                                                                               --          (terminated)
			o_reconfig_readdatavalid       => open                                                                                --          (terminated)
		);

end architecture rtl; -- of jesd204b_core_intel_jesd204b_gts_phy_intel_directphy_gts_191_lvsxkwq
