-- niosv_pd_altera_mm_interconnect_1920_lv3rznq_jesd_12_chan_interface_1_avalon_slave_agent.vhd

-- This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 25.1.1 125

library IEEE;
library altera_merlin_slave_agent_1930;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity niosv_pd_altera_mm_interconnect_1920_lv3rznq_jesd_12_chan_interface_1_avalon_slave_agent is
	generic (
		PKT_ORI_BURST_SIZE_H      : integer := 121;
		PKT_ORI_BURST_SIZE_L      : integer := 119;
		PKT_RESPONSE_STATUS_H     : integer := 118;
		PKT_RESPONSE_STATUS_L     : integer := 117;
		PKT_BURST_SIZE_H          : integer := 94;
		PKT_BURST_SIZE_L          : integer := 92;
		PKT_TRANS_LOCK            : integer := 72;
		PKT_BEGIN_BURST           : integer := 99;
		PKT_PROTECTION_H          : integer := 112;
		PKT_PROTECTION_L          : integer := 110;
		PKT_BURSTWRAP_H           : integer := 91;
		PKT_BURSTWRAP_L           : integer := 83;
		PKT_BYTE_CNT_H            : integer := 82;
		PKT_BYTE_CNT_L            : integer := 74;
		PKT_ADDR_H                : integer := 67;
		PKT_ADDR_L                : integer := 36;
		PKT_TRANS_COMPRESSED_READ : integer := 68;
		PKT_TRANS_POSTED          : integer := 69;
		PKT_TRANS_WRITE           : integer := 70;
		PKT_TRANS_READ            : integer := 71;
		PKT_DATA_H                : integer := 31;
		PKT_DATA_L                : integer := 0;
		PKT_BYTEEN_H              : integer := 35;
		PKT_BYTEEN_L              : integer := 32;
		PKT_SRC_ID_H              : integer := 104;
		PKT_SRC_ID_L              : integer := 101;
		PKT_DEST_ID_H             : integer := 108;
		PKT_DEST_ID_L             : integer := 105;
		PKT_POISON_H              : integer := 131;
		PKT_POISON_L              : integer := 131;
		PKT_DATACHK_H             : integer := 132;
		PKT_DATACHK_L             : integer := 132;
		PKT_SAI_H                 : integer := 136;
		PKT_SAI_L                 : integer := 136;
		PKT_ADDRCHK_H             : integer := 135;
		PKT_ADDRCHK_L             : integer := 134;
		PKT_USER_DATA_H           : integer := 133;
		PKT_USER_DATA_L           : integer := 133;
		PKT_ATRACE                : integer := 146;
		PKT_TRACE                 : integer := 147;
		PKT_AWAKEUP               : integer := 148;
		PKT_AWATOP_H              : integer := 154;
		PKT_AWATOP_L              : integer := 149;
		PKT_AWSTASHNID_H          : integer := 165;
		PKT_AWSTASHNID_L          : integer := 155;
		PKT_AWSTASHNIDEN          : integer := 166;
		PKT_AWSTASHLPID_H         : integer := 171;
		PKT_AWSTASHLPID_L         : integer := 167;
		PKT_AWSTASHLPIDEN         : integer := 172;
		PKT_MMUSECSID             : integer := 174;
		PKT_MMUSID_H              : integer := 173;
		PKT_MMUSID_L              : integer := 173;
		PKT_DATALESS              : integer := 175;
		PKT_SYMBOL_W              : integer := 8;
		ST_CHANNEL_W              : integer := 11;
		ST_DATA_W                 : integer := 176;
		AVS_BURSTCOUNT_W          : integer := 3;
		SUPPRESS_0_BYTEEN_CMD     : integer := 0;
		USE_MEMORY_BLOCKS         : integer := 0;
		PREVENT_FIFO_OVERFLOW     : integer := 1;
		USE_READRESPONSE          : integer := 0;
		USE_WRITERESPONSE         : integer := 0;
		ECC_ENABLE                : integer := 0;
		SYNC_RESET                : integer := 1;
		USE_PKT_DATACHK           : integer := 0;
		ROLE_BASED_USER           : integer := 0;
		ENABLE_AXI5               : integer := 0
	);
	port (
		clk                     : in  std_logic                      := '0';             --             clk.clk
		reset                   : in  std_logic                      := '0';             --       clk_reset.reset
		m0_address              : out std_logic_vector(31 downto 0);                     --              m0.address
		m0_burstcount           : out std_logic_vector(2 downto 0);                      --                .burstcount
		m0_byteenable           : out std_logic_vector(3 downto 0);                      --                .byteenable
		m0_debugaccess          : out std_logic;                                         --                .debugaccess
		m0_lock                 : out std_logic;                                         --                .lock
		m0_readdata             : in  std_logic_vector(31 downto 0)  := (others => '0'); --                .readdata
		m0_readdatavalid        : in  std_logic                      := '0';             --                .readdatavalid
		m0_read                 : out std_logic;                                         --                .read
		m0_waitrequest          : in  std_logic                      := '0';             --                .waitrequest
		m0_writedata            : out std_logic_vector(31 downto 0);                     --                .writedata
		m0_write                : out std_logic;                                         --                .write
		rp_endofpacket          : out std_logic;                                         --              rp.endofpacket
		rp_ready                : in  std_logic                      := '0';             --                .ready
		rp_valid                : out std_logic;                                         --                .valid
		rp_data                 : out std_logic_vector(175 downto 0);                    --                .data
		rp_startofpacket        : out std_logic;                                         --                .startofpacket
		cp_ready                : out std_logic;                                         --              cp.ready
		cp_valid                : in  std_logic                      := '0';             --                .valid
		cp_data                 : in  std_logic_vector(175 downto 0) := (others => '0'); --                .data
		cp_startofpacket        : in  std_logic                      := '0';             --                .startofpacket
		cp_endofpacket          : in  std_logic                      := '0';             --                .endofpacket
		cp_channel              : in  std_logic_vector(10 downto 0)  := (others => '0'); --                .channel
		rf_sink_ready           : out std_logic;                                         --         rf_sink.ready
		rf_sink_valid           : in  std_logic                      := '0';             --                .valid
		rf_sink_startofpacket   : in  std_logic                      := '0';             --                .startofpacket
		rf_sink_endofpacket     : in  std_logic                      := '0';             --                .endofpacket
		rf_sink_data            : in  std_logic_vector(176 downto 0) := (others => '0'); --                .data
		rf_source_ready         : in  std_logic                      := '0';             --       rf_source.ready
		rf_source_valid         : out std_logic;                                         --                .valid
		rf_source_startofpacket : out std_logic;                                         --                .startofpacket
		rf_source_endofpacket   : out std_logic;                                         --                .endofpacket
		rf_source_data          : out std_logic_vector(176 downto 0);                    --                .data
		rdata_fifo_sink_ready   : out std_logic;                                         -- rdata_fifo_sink.ready
		rdata_fifo_sink_valid   : in  std_logic                      := '0';             --                .valid
		rdata_fifo_sink_data    : in  std_logic_vector(33 downto 0)  := (others => '0'); --                .data
		rdata_fifo_src_ready    : in  std_logic                      := '0';             --  rdata_fifo_src.ready
		rdata_fifo_src_valid    : out std_logic;                                         --                .valid
		rdata_fifo_src_data     : out std_logic_vector(33 downto 0);                     --                .data
		m0_response             : in  std_logic_vector(1 downto 0)   := (others => '0');
		m0_writeresponsevalid   : in  std_logic                      := '0';
		rdata_fifo_sink_error   : in  std_logic                      := '0'
	);
end entity niosv_pd_altera_mm_interconnect_1920_lv3rznq_jesd_12_chan_interface_1_avalon_slave_agent;

architecture rtl of niosv_pd_altera_mm_interconnect_1920_lv3rznq_jesd_12_chan_interface_1_avalon_slave_agent is
	component niosv_pd_altera_merlin_slave_agent_1930_jxauz3i_cmp is
		generic (
			PKT_ORI_BURST_SIZE_H      : integer := 90;
			PKT_ORI_BURST_SIZE_L      : integer := 88;
			PKT_RESPONSE_STATUS_H     : integer := 87;
			PKT_RESPONSE_STATUS_L     : integer := 86;
			PKT_BURST_SIZE_H          : integer := 85;
			PKT_BURST_SIZE_L          : integer := 83;
			PKT_TRANS_LOCK            : integer := 82;
			PKT_BEGIN_BURST           : integer := 81;
			PKT_PROTECTION_H          : integer := 80;
			PKT_PROTECTION_L          : integer := 80;
			PKT_BURSTWRAP_H           : integer := 79;
			PKT_BURSTWRAP_L           : integer := 77;
			PKT_BYTE_CNT_H            : integer := 76;
			PKT_BYTE_CNT_L            : integer := 74;
			PKT_ADDR_H                : integer := 73;
			PKT_ADDR_L                : integer := 42;
			PKT_TRANS_COMPRESSED_READ : integer := 41;
			PKT_TRANS_POSTED          : integer := 40;
			PKT_TRANS_WRITE           : integer := 39;
			PKT_TRANS_READ            : integer := 38;
			PKT_DATA_H                : integer := 37;
			PKT_DATA_L                : integer := 6;
			PKT_BYTEEN_H              : integer := 5;
			PKT_BYTEEN_L              : integer := 2;
			PKT_SRC_ID_H              : integer := 1;
			PKT_SRC_ID_L              : integer := 1;
			PKT_DEST_ID_H             : integer := 0;
			PKT_DEST_ID_L             : integer := 0;
			PKT_POISON_H              : integer := 92;
			PKT_POISON_L              : integer := 92;
			PKT_DATACHK_H             : integer := 97;
			PKT_DATACHK_L             : integer := 94;
			PKT_SAI_H                 : integer := 98;
			PKT_SAI_L                 : integer := 98;
			PKT_ADDRCHK_H             : integer := 99;
			PKT_ADDRCHK_L             : integer := 99;
			PKT_USER_DATA_H           : integer := 103;
			PKT_USER_DATA_L           : integer := 103;
			PKT_ATRACE                : integer := 104;
			PKT_TRACE                 : integer := 105;
			PKT_AWAKEUP               : integer := 106;
			PKT_AWATOP_H              : integer := 159;
			PKT_AWATOP_L              : integer := 154;
			PKT_AWSTASHNID_H          : integer := 170;
			PKT_AWSTASHNID_L          : integer := 160;
			PKT_AWSTASHNIDEN          : integer := 171;
			PKT_AWSTASHLPID_H         : integer := 176;
			PKT_AWSTASHLPID_L         : integer := 172;
			PKT_AWSTASHLPIDEN         : integer := 177;
			PKT_MMUSECSID             : integer := 178;
			PKT_MMUSID_H              : integer := 194;
			PKT_MMUSID_L              : integer := 179;
			PKT_DATALESS              : integer := 180;
			PKT_SYMBOL_W              : integer := 8;
			ST_CHANNEL_W              : integer := 8;
			ST_DATA_W                 : integer := 98;
			AVS_BURSTCOUNT_W          : integer := 4;
			SUPPRESS_0_BYTEEN_CMD     : integer := 1;
			USE_MEMORY_BLOCKS         : integer := 0;
			PREVENT_FIFO_OVERFLOW     : integer := 0;
			USE_READRESPONSE          : integer := 0;
			USE_WRITERESPONSE         : integer := 0;
			ECC_ENABLE                : integer := 0;
			SYNC_RESET                : integer := 0;
			USE_PKT_DATACHK           : integer := 0;
			ROLE_BASED_USER           : integer := 0;
			ENABLE_AXI5               : integer := 0
		);
		port (
			clk                     : in  std_logic                      := 'X';             -- clk
			reset                   : in  std_logic                      := 'X';             -- reset
			m0_address              : out std_logic_vector(31 downto 0);                     -- address
			m0_burstcount           : out std_logic_vector(2 downto 0);                      -- burstcount
			m0_byteenable           : out std_logic_vector(3 downto 0);                      -- byteenable
			m0_debugaccess          : out std_logic;                                         -- debugaccess
			m0_lock                 : out std_logic;                                         -- lock
			m0_readdata             : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- readdata
			m0_readdatavalid        : in  std_logic                      := 'X';             -- readdatavalid
			m0_read                 : out std_logic;                                         -- read
			m0_waitrequest          : in  std_logic                      := 'X';             -- waitrequest
			m0_writedata            : out std_logic_vector(31 downto 0);                     -- writedata
			m0_write                : out std_logic;                                         -- write
			rp_endofpacket          : out std_logic;                                         -- endofpacket
			rp_ready                : in  std_logic                      := 'X';             -- ready
			rp_valid                : out std_logic;                                         -- valid
			rp_data                 : out std_logic_vector(175 downto 0);                    -- data
			rp_startofpacket        : out std_logic;                                         -- startofpacket
			cp_ready                : out std_logic;                                         -- ready
			cp_valid                : in  std_logic                      := 'X';             -- valid
			cp_data                 : in  std_logic_vector(175 downto 0) := (others => 'X'); -- data
			cp_startofpacket        : in  std_logic                      := 'X';             -- startofpacket
			cp_endofpacket          : in  std_logic                      := 'X';             -- endofpacket
			cp_channel              : in  std_logic_vector(10 downto 0)  := (others => 'X'); -- channel
			rf_sink_ready           : out std_logic;                                         -- ready
			rf_sink_valid           : in  std_logic                      := 'X';             -- valid
			rf_sink_startofpacket   : in  std_logic                      := 'X';             -- startofpacket
			rf_sink_endofpacket     : in  std_logic                      := 'X';             -- endofpacket
			rf_sink_data            : in  std_logic_vector(176 downto 0) := (others => 'X'); -- data
			rf_source_ready         : in  std_logic                      := 'X';             -- ready
			rf_source_valid         : out std_logic;                                         -- valid
			rf_source_startofpacket : out std_logic;                                         -- startofpacket
			rf_source_endofpacket   : out std_logic;                                         -- endofpacket
			rf_source_data          : out std_logic_vector(176 downto 0);                    -- data
			rdata_fifo_sink_ready   : out std_logic;                                         -- ready
			rdata_fifo_sink_valid   : in  std_logic                      := 'X';             -- valid
			rdata_fifo_sink_data    : in  std_logic_vector(33 downto 0)  := (others => 'X'); -- data
			rdata_fifo_src_ready    : in  std_logic                      := 'X';             -- ready
			rdata_fifo_src_valid    : out std_logic;                                         -- valid
			rdata_fifo_src_data     : out std_logic_vector(33 downto 0);                     -- data
			m0_response             : in  std_logic_vector(1 downto 0)   := (others => 'X'); -- response
			m0_writeresponsevalid   : in  std_logic                      := 'X';             -- writeresponsevalid
			rdata_fifo_sink_error   : in  std_logic                      := 'X'              -- error
		);
	end component niosv_pd_altera_merlin_slave_agent_1930_jxauz3i_cmp;

	for jesd_12_chan_interface_1_avalon_slave_agent : niosv_pd_altera_merlin_slave_agent_1930_jxauz3i_cmp
		use entity altera_merlin_slave_agent_1930.niosv_pd_altera_merlin_slave_agent_1930_jxauz3i;
begin

	jesd_12_chan_interface_1_avalon_slave_agent : component niosv_pd_altera_merlin_slave_agent_1930_jxauz3i_cmp
		generic map (
			PKT_ORI_BURST_SIZE_H      => PKT_ORI_BURST_SIZE_H,
			PKT_ORI_BURST_SIZE_L      => PKT_ORI_BURST_SIZE_L,
			PKT_RESPONSE_STATUS_H     => PKT_RESPONSE_STATUS_H,
			PKT_RESPONSE_STATUS_L     => PKT_RESPONSE_STATUS_L,
			PKT_BURST_SIZE_H          => PKT_BURST_SIZE_H,
			PKT_BURST_SIZE_L          => PKT_BURST_SIZE_L,
			PKT_TRANS_LOCK            => PKT_TRANS_LOCK,
			PKT_BEGIN_BURST           => PKT_BEGIN_BURST,
			PKT_PROTECTION_H          => PKT_PROTECTION_H,
			PKT_PROTECTION_L          => PKT_PROTECTION_L,
			PKT_BURSTWRAP_H           => PKT_BURSTWRAP_H,
			PKT_BURSTWRAP_L           => PKT_BURSTWRAP_L,
			PKT_BYTE_CNT_H            => PKT_BYTE_CNT_H,
			PKT_BYTE_CNT_L            => PKT_BYTE_CNT_L,
			PKT_ADDR_H                => PKT_ADDR_H,
			PKT_ADDR_L                => PKT_ADDR_L,
			PKT_TRANS_COMPRESSED_READ => PKT_TRANS_COMPRESSED_READ,
			PKT_TRANS_POSTED          => PKT_TRANS_POSTED,
			PKT_TRANS_WRITE           => PKT_TRANS_WRITE,
			PKT_TRANS_READ            => PKT_TRANS_READ,
			PKT_DATA_H                => PKT_DATA_H,
			PKT_DATA_L                => PKT_DATA_L,
			PKT_BYTEEN_H              => PKT_BYTEEN_H,
			PKT_BYTEEN_L              => PKT_BYTEEN_L,
			PKT_SRC_ID_H              => PKT_SRC_ID_H,
			PKT_SRC_ID_L              => PKT_SRC_ID_L,
			PKT_DEST_ID_H             => PKT_DEST_ID_H,
			PKT_DEST_ID_L             => PKT_DEST_ID_L,
			PKT_POISON_H              => PKT_POISON_H,
			PKT_POISON_L              => PKT_POISON_L,
			PKT_DATACHK_H             => PKT_DATACHK_H,
			PKT_DATACHK_L             => PKT_DATACHK_L,
			PKT_SAI_H                 => PKT_SAI_H,
			PKT_SAI_L                 => PKT_SAI_L,
			PKT_ADDRCHK_H             => PKT_ADDRCHK_H,
			PKT_ADDRCHK_L             => PKT_ADDRCHK_L,
			PKT_USER_DATA_H           => PKT_USER_DATA_H,
			PKT_USER_DATA_L           => PKT_USER_DATA_L,
			PKT_ATRACE                => PKT_ATRACE,
			PKT_TRACE                 => PKT_TRACE,
			PKT_AWAKEUP               => PKT_AWAKEUP,
			PKT_AWATOP_H              => PKT_AWATOP_H,
			PKT_AWATOP_L              => PKT_AWATOP_L,
			PKT_AWSTASHNID_H          => PKT_AWSTASHNID_H,
			PKT_AWSTASHNID_L          => PKT_AWSTASHNID_L,
			PKT_AWSTASHNIDEN          => PKT_AWSTASHNIDEN,
			PKT_AWSTASHLPID_H         => PKT_AWSTASHLPID_H,
			PKT_AWSTASHLPID_L         => PKT_AWSTASHLPID_L,
			PKT_AWSTASHLPIDEN         => PKT_AWSTASHLPIDEN,
			PKT_MMUSECSID             => PKT_MMUSECSID,
			PKT_MMUSID_H              => PKT_MMUSID_H,
			PKT_MMUSID_L              => PKT_MMUSID_L,
			PKT_DATALESS              => PKT_DATALESS,
			PKT_SYMBOL_W              => PKT_SYMBOL_W,
			ST_CHANNEL_W              => ST_CHANNEL_W,
			ST_DATA_W                 => ST_DATA_W,
			AVS_BURSTCOUNT_W          => AVS_BURSTCOUNT_W,
			SUPPRESS_0_BYTEEN_CMD     => SUPPRESS_0_BYTEEN_CMD,
			USE_MEMORY_BLOCKS         => USE_MEMORY_BLOCKS,
			PREVENT_FIFO_OVERFLOW     => PREVENT_FIFO_OVERFLOW,
			USE_READRESPONSE          => USE_READRESPONSE,
			USE_WRITERESPONSE         => USE_WRITERESPONSE,
			ECC_ENABLE                => ECC_ENABLE,
			SYNC_RESET                => SYNC_RESET,
			USE_PKT_DATACHK           => USE_PKT_DATACHK,
			ROLE_BASED_USER           => ROLE_BASED_USER,
			ENABLE_AXI5               => ENABLE_AXI5
		)
		port map (
			clk                     => clk,                     --             clk.clk
			reset                   => reset,                   --       clk_reset.reset
			m0_address              => m0_address,              --              m0.address
			m0_burstcount           => m0_burstcount,           --                .burstcount
			m0_byteenable           => m0_byteenable,           --                .byteenable
			m0_debugaccess          => m0_debugaccess,          --                .debugaccess
			m0_lock                 => m0_lock,                 --                .lock
			m0_readdata             => m0_readdata,             --                .readdata
			m0_readdatavalid        => m0_readdatavalid,        --                .readdatavalid
			m0_read                 => m0_read,                 --                .read
			m0_waitrequest          => m0_waitrequest,          --                .waitrequest
			m0_writedata            => m0_writedata,            --                .writedata
			m0_write                => m0_write,                --                .write
			rp_endofpacket          => rp_endofpacket,          --              rp.endofpacket
			rp_ready                => rp_ready,                --                .ready
			rp_valid                => rp_valid,                --                .valid
			rp_data                 => rp_data,                 --                .data
			rp_startofpacket        => rp_startofpacket,        --                .startofpacket
			cp_ready                => cp_ready,                --              cp.ready
			cp_valid                => cp_valid,                --                .valid
			cp_data                 => cp_data,                 --                .data
			cp_startofpacket        => cp_startofpacket,        --                .startofpacket
			cp_endofpacket          => cp_endofpacket,          --                .endofpacket
			cp_channel              => cp_channel,              --                .channel
			rf_sink_ready           => rf_sink_ready,           --         rf_sink.ready
			rf_sink_valid           => rf_sink_valid,           --                .valid
			rf_sink_startofpacket   => rf_sink_startofpacket,   --                .startofpacket
			rf_sink_endofpacket     => rf_sink_endofpacket,     --                .endofpacket
			rf_sink_data            => rf_sink_data,            --                .data
			rf_source_ready         => rf_source_ready,         --       rf_source.ready
			rf_source_valid         => rf_source_valid,         --                .valid
			rf_source_startofpacket => rf_source_startofpacket, --                .startofpacket
			rf_source_endofpacket   => rf_source_endofpacket,   --                .endofpacket
			rf_source_data          => rf_source_data,          --                .data
			rdata_fifo_sink_ready   => rdata_fifo_sink_ready,   -- rdata_fifo_sink.ready
			rdata_fifo_sink_valid   => rdata_fifo_sink_valid,   --                .valid
			rdata_fifo_sink_data    => rdata_fifo_sink_data,    --                .data
			rdata_fifo_src_ready    => rdata_fifo_src_ready,    --  rdata_fifo_src.ready
			rdata_fifo_src_valid    => rdata_fifo_src_valid,    --                .valid
			rdata_fifo_src_data     => rdata_fifo_src_data,     --                .data
			m0_response             => "00",                    --     (terminated)
			m0_writeresponsevalid   => '0',                     --     (terminated)
			rdata_fifo_sink_error   => '0'                      --     (terminated)
		);

end architecture rtl; -- of niosv_pd_altera_mm_interconnect_1920_lv3rznq_jesd_12_chan_interface_1_avalon_slave_agent
