-- tic_uart_sync_tx_la_fifo_1k.vhd

-- Generated using ACDS version 25.1.1 125

library IEEE;
library fifo_1941;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tic_uart_sync_tx_la_fifo_1k is
	port (
		data  : in  std_logic_vector(7 downto 0) := (others => '0'); --  fifo_input.datain,  Data input of the memory.The data port is required for all FIFO operation.
		wrreq : in  std_logic                    := '0';             --            .wrreq,   wrreq input signal to request for write operation.The wrreq signal is required for all FIFO operation.
		rdreq : in  std_logic                    := '0';             --            .rdreq,   rdreq input signal to request for read operation.The rdreq signal is required for all FIFO operation.
		clock : in  std_logic                    := '0';             --            .clk,     Positive-edge-triggered clock.
		aclr  : in  std_logic                    := '0';             --            .aclr,    It is asynchronous reset.Assert this signal to clear all the output status ports, but the effect on the q output may vary for different FIFO configurations.
		sclr  : in  std_logic                    := '0';             --            .sclr,    It is synchronous reset.Assert this signal to clear all the output status ports, but the effect on the q output may vary for different FIFO configurations.
		q     : out std_logic_vector(7 downto 0);                    -- fifo_output.dataout, Data output of the memory. This port is required for all FIFO operation.
		usedw : out std_logic_vector(9 downto 0);                    --            .usedw,   Show the number of words stored in the FIFO.
		full  : out std_logic;                                       --            .full,    When full signal is asserted, the FIFO IP core is considered full. Do not perform write request operation when the FIFO IP core is full.
		empty : out std_logic                                        --            .empty,   When empty signal is asserted, the FIFO IP core is considered empty.Do not perform read request operation when the FIFO IP core is empty.
	);
end entity tic_uart_sync_tx_la_fifo_1k;

architecture rtl of tic_uart_sync_tx_la_fifo_1k is
	component tic_uart_sync_tx_la_fifo_1k_fifo_1941_oyfkwki_cmp is
		port (
			data  : in  std_logic_vector(7 downto 0) := (others => 'X'); -- datain
			wrreq : in  std_logic                    := 'X';             -- wrreq
			rdreq : in  std_logic                    := 'X';             -- rdreq
			clock : in  std_logic                    := 'X';             -- clk
			aclr  : in  std_logic                    := 'X';             -- aclr
			sclr  : in  std_logic                    := 'X';             -- sclr
			q     : out std_logic_vector(7 downto 0);                    -- dataout
			usedw : out std_logic_vector(9 downto 0);                    -- usedw
			full  : out std_logic;                                       -- full
			empty : out std_logic                                        -- empty
		);
	end component tic_uart_sync_tx_la_fifo_1k_fifo_1941_oyfkwki_cmp;

	for fifo_0 : tic_uart_sync_tx_la_fifo_1k_fifo_1941_oyfkwki_cmp
		use entity fifo_1941.tic_uart_sync_tx_la_fifo_1k_fifo_1941_oyfkwki;
begin

	fifo_0 : component tic_uart_sync_tx_la_fifo_1k_fifo_1941_oyfkwki_cmp
		port map (
			data  => data,  --  fifo_input.datain
			wrreq => wrreq, --            .wrreq
			rdreq => rdreq, --            .rdreq
			clock => clock, --            .clk
			aclr  => aclr,  --            .aclr
			sclr  => sclr,  --            .sclr
			q     => q,     -- fifo_output.dataout
			usedw => usedw, --            .usedw
			full  => full,  --            .full
			empty => empty  --            .empty
		);

end architecture rtl; -- of tic_uart_sync_tx_la_fifo_1k
