-- jesd_gts_reset_sequencer.vhd

-- Generated using ACDS version 25.1.1 125

library IEEE;
library intel_srcss_gts_401;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity jesd_gts_reset_sequencer is
	port (
		o_src_rs_grant               : out std_logic_vector(11 downto 0);                    --               o_src_rs_grant.src_rs_grant,               Grant from SRC_Shoreline_Sequencer to SRC_Lane, this will allow SRC_Lane to drive/toggle a reset
		i_src_rs_priority            : in  std_logic_vector(11 downto 0) := (others => '0'); --            i_src_rs_priority.src_rs_priority,            Binary Priority Input(0 - Less priority and 1 - high Priority). The user will have to tie this input to '0' unless the request is from an IP which needs fast reconfigurations.
		i_src_rs_req                 : in  std_logic_vector(11 downto 0) := (others => '0'); --                 i_src_rs_req.src_rs_req,                 Request from SRC_Lane to the SRC_Shoreline_Sequencer when it wants to toggle a reset
		o_pma_cu_clk                 : out std_logic_vector(2 downto 0);                     --                 o_pma_cu_clk.clk,                        PMA control unit clock output, 1 per quad of a shoreline. For example, SPLL is used for QHIP/s across quads then 1 output port to be connected to each quad input.
		i_refclk_bus_out             : in  std_logic                     := '0';             --             i_refclk_bus_out.refclk_bus_out,             Refclk fail status from 1 QHIP in this shoreline which says if the clkrx refclk failure has occured
		o_shoreline_refclk_fail_stat : out std_logic                                         -- o_shoreline_refclk_fail_stat.shoreline_refclk_fail_stat, Refclk fail status to the user design which says if the clkrx refclk failure has occured
	);
end entity jesd_gts_reset_sequencer;

architecture rtl of jesd_gts_reset_sequencer is
	component jesd_gts_reset_sequencer_intel_srcss_gts_401_467auiy_cmp is
		generic (
			SRC_RS_DISABLE      : boolean := false;
			NUM_LANES_SHORELINE : integer := 1;
			NUM_BANKS_SHORELINE : integer := 1
		);
		port (
			o_src_rs_grant               : out std_logic_vector(NUM_LANES_SHORELINE-1 downto 0);                    -- src_rs_grant
			i_src_rs_priority            : in  std_logic_vector(NUM_LANES_SHORELINE-1 downto 0) := (others => 'X'); -- src_rs_priority
			i_src_rs_req                 : in  std_logic_vector(NUM_LANES_SHORELINE-1 downto 0) := (others => 'X'); -- src_rs_req
			o_pma_cu_clk                 : out std_logic_vector(NUM_BANKS_SHORELINE-1 downto 0);                    -- clk
			i_refclk_bus_out             : in  std_logic                                        := 'X';             -- refclk_bus_out
			o_shoreline_refclk_fail_stat : out std_logic                                                            -- shoreline_refclk_fail_stat
		);
	end component jesd_gts_reset_sequencer_intel_srcss_gts_401_467auiy_cmp;

	for intel_srcss_gts_0 : jesd_gts_reset_sequencer_intel_srcss_gts_401_467auiy_cmp
		use entity intel_srcss_gts_401.jesd_gts_reset_sequencer_intel_srcss_gts_401_467auiy;
begin

	intel_srcss_gts_0 : component jesd_gts_reset_sequencer_intel_srcss_gts_401_467auiy_cmp
		generic map (
			SRC_RS_DISABLE      => false,
			NUM_LANES_SHORELINE => 12,
			NUM_BANKS_SHORELINE => 3
		)
		port map (
			o_src_rs_grant               => o_src_rs_grant,               --               o_src_rs_grant.src_rs_grant
			i_src_rs_priority            => i_src_rs_priority,            --            i_src_rs_priority.src_rs_priority
			i_src_rs_req                 => i_src_rs_req,                 --                 i_src_rs_req.src_rs_req
			o_pma_cu_clk                 => o_pma_cu_clk,                 --                 o_pma_cu_clk.clk
			i_refclk_bus_out             => i_refclk_bus_out,             --             i_refclk_bus_out.refclk_bus_out
			o_shoreline_refclk_fail_stat => o_shoreline_refclk_fail_stat  -- o_shoreline_refclk_fail_stat.shoreline_refclk_fail_stat
		);

end architecture rtl; -- of jesd_gts_reset_sequencer
