-- jesd204b_core_one_lane_hal_fec_hal_2100_hmiwnzy.vhd

-- Generated using ACDS version 25.1.1 125

library IEEE;
library fec_hal_2100;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity jesd204b_core_one_lane_hal_fec_hal_2100_hmiwnzy is
	generic (
		ch_fec_l_duplex_mode_atom   : string := "DUPLEX_MODE_RX_ONLY_SIMPLEX";
		ch_fec_l_fec_spec_atom      : string := "FEC_SPEC_DISABLED";
		ch_fec_l_fracture_atom      : string := "FRACTURE_UNUSED";
		ch_fec_dr_enabled_atom      : string := "DR_ENABLED_DR_ENABLED";
		ch_fec_l_sup_mode_atom      : string := "SUP_MODE_USER_MODE";
		ch_fec_l_sim_mode_atom      : string := "SIM_MODE_ENABLE";
		ch_fec_l_pcs_tx_en_atom     : string := "FALSE";
		ch_fec_l_pcs_rx_en_atom     : string := "FALSE";
		ch_fec_l_loopback_mode_atom : string := "LOOPBACK_MODE_DISABLE";
		ch_fec_l_dyn_tx_mux_atom    : string := "DYN_TX_MUX_UNUSED";
		ch_fec_l_fec_error_atom     : string := "FALSE";
		ch_fec_l_fec_mode_atom      : string := "FEC_MODE_DISABLED";
		ch_fec_l_tx_en_atom         : string := "FALSE";
		ch_fec_l_rx_en_atom         : string := "FALSE"
	);
	port (
		i_ch_lavmm_fec_addr                 : in  std_logic_vector(19 downto 0) := (others => '0'); --                        reconfig.address,       Stats Snapshot
		i_ch_lavmm_fec_be                   : in  std_logic_vector(3 downto 0)  := (others => '0'); --                                .byteenable,    RX PFC
		i_ch_lavmm_fec_read                 : in  std_logic                     := '0';             --                                .read,          RX error bits asserted on the EOP cycle
		i_ch_lavmm_fec_wdata                : in  std_logic_vector(31 downto 0) := (others => '0'); --                                .writedata,     RX error bits asserted on the EOP cycle
		i_ch_lavmm_fec_write                : in  std_logic                     := '0';             --                                .write,         CSR access address
		o_ch_lavmm_fec_rdata                : out std_logic_vector(31 downto 0);                    --                                .readdata,      RX error bits asserted on the EOP cycle
		o_ch_lavmm_fec_rdata_valid          : out std_logic;                                        --                                .readdatavalid, Stats Snapshot
		o_ch_lavmm_fec_waitreq              : out std_logic;                                        --                                .waitrequest,   RX PFC
		i_ch_lavmm_fec_clk                  : in  std_logic                     := '0';             --                    reconfig_clk.clk,           RX PFC
		i_ch_lavmm_fec_rstn                 : in  std_logic                     := '0';             --                    reconfig_rst.reset,         RX error bits asserted on the EOP cycle
		i_ch_eth_fec_tx_async               : in  std_logic_vector(6 downto 0)  := (others => '0'); --                     asyncdata_0.data,          CSR access address
		i_ch_eth_fec_tx_direct              : in  std_logic                     := '0';             --                     asyncdata_1.data,          RX error bits asserted on the EOP cycle
		o_ch_eth_fec_rx_async               : out std_logic_vector(11 downto 0);                    --                     asyncdata_2.data,          Stats Snapshot
		o_ch_eth_fec_rx_direct              : out std_logic;                                        --                     asyncdata_3.data,          RX PFC
		i_rstfec_fec_csr_ret                : in  std_logic                     := '0';             --            i_rstfec_fec_csr_ret.data,          CSR access address
		o_fec_rx_rdy_n                      : out std_logic;                                        --                  o_fec_rx_rdy_n.data,          RX error bits asserted on the EOP cycle
		i_rstfec_rx_fec_sfrz_n              : in  std_logic                     := '0';             --          i_rstfec_rx_fec_sfrz_n.data,          Stats Snapshot
		i_rstfec_fec_rx_rst_n               : in  std_logic                     := '0';             --           i_rstfec_fec_rx_rst_n.data,          RX PFC
		i_rstfec_tx_fec_sfrz_n              : in  std_logic                     := '0';             --          i_rstfec_tx_fec_sfrz_n.reset,         CSR access address
		i_rstfec_fec_tx_rst_n               : in  std_logic                     := '0';             --           i_rstfec_fec_tx_rst_n.data,          RX error bits asserted on the EOP cycle
		o_fec_rx_data                       : out std_logic_vector(42 downto 0);                    --                   o_fec_rx_data.data,          CSR access address
		i_fec_clk                           : in  std_logic                     := '0';             --                       i_fec_clk.clk,           RX error bits asserted on the EOP cycle
		i_xcvr_rx_data                      : in  std_logic_vector(42 downto 0) := (others => '0'); --                  i_xcvr_rx_data.data,          CSR access address
		o_xcvr_tx_data                      : out std_logic_vector(42 downto 0);                    --                  o_xcvr_tx_data.data,          RX error bits asserted on the EOP cycle
		i_pma_rx_sf                         : in  std_logic                     := '0';             --                     i_pma_rx_sf.data,          RX error bits asserted on the EOP cycle
		o_ch_lavmm_fec_addr_fec_wrap        : out std_logic_vector(19 downto 0);                    --                reconfig_fecwrap.address
		o_ch_lavmm_fec_be_fec_wrap          : out std_logic_vector(3 downto 0);                     --                                .byteenable
		o_ch_lavmm_fec_read_fec_wrap        : out std_logic;                                        --                                .read
		o_ch_lavmm_fec_wdata_fec_wrap       : out std_logic_vector(31 downto 0);                    --                                .writedata
		o_ch_lavmm_fec_write_fec_wrap       : out std_logic;                                        --                                .write
		i_ch_lavmm_fec_rdata_fec_wrap       : in  std_logic_vector(31 downto 0) := (others => '0'); --                                .readdata
		i_ch_lavmm_fec_rdata_valid_fec_wrap : in  std_logic                     := '0';             --                                .readdatavalid
		i_ch_lavmm_fec_waitreq_fec_wrap     : in  std_logic                     := '0';             --                                .waitrequest
		o_ch_lavmm_fec_clk_fec_wrap         : out std_logic;                                        --            reconfig_fecwrap_clk.clk
		o_ch_lavmm_fec_rstn_fec_wrap        : out std_logic;                                        --            reconfig_fecwrap_rst.reset
		i_ch_eth_fec_rx_async_fec_wrap      : in  std_logic_vector(11 downto 0) := (others => '0'); --                     asyncdata_4.data
		i_ch_eth_fec_rx_direct_fec_wrap     : in  std_logic                     := '0';             --                     asyncdata_5.data
		o_ch_eth_fec_tx_async_fec_wrap      : out std_logic_vector(6 downto 0);                     --                     asyncdata_6.data
		o_ch_eth_fec_tx_direct_fec_wrap     : out std_logic;                                        --                     asyncdata_7.data
		o_rstfec_fec_csr_ret_fec_wrap       : out std_logic;                                        --   o_rstfec_fec_csr_ret_fec_wrap.data
		i_fec_rx_rdy_n_fec_wrap             : in  std_logic                     := '0';             --         i_fec_rx_rdy_n_fec_wrap.data
		o_rstfec_fec_rx_rst_n_fec_wrap      : out std_logic;                                        --  o_rstfec_fec_rx_rst_n_fec_wrap.reset
		o_rstfec_fec_tx_rst_n_fec_wrap      : out std_logic;                                        --  o_rstfec_fec_tx_rst_n_fec_wrap.reset
		o_rstfec_rx_fec_sfrz_n_fec_wrap     : out std_logic;                                        -- o_rstfec_rx_fec_sfrz_n_fec_wrap.reset
		o_rstfec_tx_fec_sfrz_n_fec_wrap     : out std_logic;                                        -- o_rstfec_tx_fec_sfrz_n_fec_wrap.reset
		i_fec_tx_data_mux_sel_fec_wrap      : in  std_logic                     := '0';             --  i_fec_tx_data_mux_sel_fec_wrap.muxsel
		i_fec_rx_data_fec_wrap              : in  std_logic_vector(42 downto 0) := (others => '0'); --          i_fec_rx_data_fec_wrap.data
		o_fec_i_tx_mux_data_fec_wrap        : out std_logic_vector(42 downto 0);                    --    o_fec_i_tx_mux_data_fec_wrap.data
		o_xcvr_rx_data                      : out std_logic_vector(42 downto 0);                    --                  o_xcvr_rx_data.data
		i_xcvr_tx_data                      : in  std_logic_vector(42 downto 0) := (others => '0'); --                  i_xcvr_tx_data.data
		o_pma_rx_sf                         : out std_logic;                                        --                     o_pma_rx_sf.data
		o_fec_tx_data_mux_sel               : out std_logic;                                        --           o_fec_tx_data_mux_sel.data
		i_fec_i_tx_mux_data                 : in  std_logic_vector(42 downto 0) := (others => '0')  --             i_fec_i_tx_mux_data.data
	);
end entity jesd204b_core_one_lane_hal_fec_hal_2100_hmiwnzy;

architecture rtl of jesd204b_core_one_lane_hal_fec_hal_2100_hmiwnzy is
	component jesd204b_core_fec_hal_2100_lxszoea_cmp is
		generic (
			ch_fec_l_duplex_mode_atom   : string := "";
			ch_fec_l_fec_spec_atom      : string := "";
			ch_fec_l_fracture_atom      : string := "";
			ch_fec_dr_enabled_atom      : string := "";
			ch_fec_l_sup_mode_atom      : string := "";
			ch_fec_l_sim_mode_atom      : string := "";
			ch_fec_l_pcs_tx_en_atom     : string := "";
			ch_fec_l_pcs_rx_en_atom     : string := "";
			ch_fec_l_loopback_mode_atom : string := "";
			ch_fec_l_dyn_tx_mux_atom    : string := "DYN_TX_MUX_UNUSED";
			ch_fec_l_fec_error_atom     : string := "FALSE";
			ch_fec_l_fec_mode_atom      : string := "FEC_MODE_DISABLED";
			ch_fec_l_tx_en_atom         : string := "FALSE";
			ch_fec_l_rx_en_atom         : string := "FALSE"
		);
		port (
			i_ch_lavmm_fec_addr                 : in  std_logic_vector(19 downto 0) := (others => 'X'); -- address
			i_ch_lavmm_fec_be                   : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			i_ch_lavmm_fec_read                 : in  std_logic                     := 'X';             -- read
			i_ch_lavmm_fec_wdata                : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			i_ch_lavmm_fec_write                : in  std_logic                     := 'X';             -- write
			o_ch_lavmm_fec_rdata                : out std_logic_vector(31 downto 0);                    -- readdata
			o_ch_lavmm_fec_rdata_valid          : out std_logic;                                        -- readdatavalid
			o_ch_lavmm_fec_waitreq              : out std_logic;                                        -- waitrequest
			i_ch_lavmm_fec_clk                  : in  std_logic                     := 'X';             -- clk
			i_ch_lavmm_fec_rstn                 : in  std_logic                     := 'X';             -- reset
			i_ch_eth_fec_tx_async               : in  std_logic_vector(6 downto 0)  := (others => 'X'); -- data
			i_ch_eth_fec_tx_direct              : in  std_logic                     := 'X';             -- data
			o_ch_eth_fec_rx_async               : out std_logic_vector(11 downto 0);                    -- data
			o_ch_eth_fec_rx_direct              : out std_logic;                                        -- data
			i_rstfec_fec_csr_ret                : in  std_logic                     := 'X';             -- data
			o_fec_rx_rdy_n                      : out std_logic;                                        -- data
			i_rstfec_rx_fec_sfrz_n              : in  std_logic                     := 'X';             -- data
			i_rstfec_fec_rx_rst_n               : in  std_logic                     := 'X';             -- data
			i_rstfec_tx_fec_sfrz_n              : in  std_logic                     := 'X';             -- reset
			i_rstfec_fec_tx_rst_n               : in  std_logic                     := 'X';             -- data
			o_fec_rx_data                       : out std_logic_vector(42 downto 0);                    -- data
			i_fec_clk                           : in  std_logic                     := 'X';             -- clk
			i_xcvr_rx_data                      : in  std_logic_vector(42 downto 0) := (others => 'X'); -- data
			o_xcvr_tx_data                      : out std_logic_vector(42 downto 0);                    -- data
			i_pma_rx_sf                         : in  std_logic                     := 'X';             -- data
			o_ch_lavmm_fec_addr_fec_wrap        : out std_logic_vector(19 downto 0);                    -- address
			o_ch_lavmm_fec_be_fec_wrap          : out std_logic_vector(3 downto 0);                     -- byteenable
			o_ch_lavmm_fec_read_fec_wrap        : out std_logic;                                        -- read
			o_ch_lavmm_fec_wdata_fec_wrap       : out std_logic_vector(31 downto 0);                    -- writedata
			o_ch_lavmm_fec_write_fec_wrap       : out std_logic;                                        -- write
			i_ch_lavmm_fec_rdata_fec_wrap       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			i_ch_lavmm_fec_rdata_valid_fec_wrap : in  std_logic                     := 'X';             -- readdatavalid
			i_ch_lavmm_fec_waitreq_fec_wrap     : in  std_logic                     := 'X';             -- waitrequest
			o_ch_lavmm_fec_clk_fec_wrap         : out std_logic;                                        -- clk
			o_ch_lavmm_fec_rstn_fec_wrap        : out std_logic;                                        -- reset
			i_ch_eth_fec_rx_async_fec_wrap      : in  std_logic_vector(11 downto 0) := (others => 'X'); -- data
			i_ch_eth_fec_rx_direct_fec_wrap     : in  std_logic                     := 'X';             -- data
			o_ch_eth_fec_tx_async_fec_wrap      : out std_logic_vector(6 downto 0);                     -- data
			o_ch_eth_fec_tx_direct_fec_wrap     : out std_logic;                                        -- data
			o_rstfec_fec_csr_ret_fec_wrap       : out std_logic;                                        -- data
			i_fec_rx_rdy_n_fec_wrap             : in  std_logic                     := 'X';             -- data
			o_rstfec_fec_rx_rst_n_fec_wrap      : out std_logic;                                        -- reset
			o_rstfec_fec_tx_rst_n_fec_wrap      : out std_logic;                                        -- reset
			o_rstfec_rx_fec_sfrz_n_fec_wrap     : out std_logic;                                        -- reset
			o_rstfec_tx_fec_sfrz_n_fec_wrap     : out std_logic;                                        -- reset
			i_fec_tx_data_mux_sel_fec_wrap      : in  std_logic                     := 'X';             -- muxsel
			i_fec_rx_data_fec_wrap              : in  std_logic_vector(42 downto 0) := (others => 'X'); -- data
			o_fec_i_tx_mux_data_fec_wrap        : out std_logic_vector(42 downto 0);                    -- data
			o_xcvr_rx_data                      : out std_logic_vector(42 downto 0);                    -- data
			i_xcvr_tx_data                      : in  std_logic_vector(42 downto 0) := (others => 'X'); -- data
			o_pma_rx_sf                         : out std_logic;                                        -- data
			o_fec_tx_data_mux_sel               : out std_logic;                                        -- data
			i_fec_i_tx_mux_data                 : in  std_logic_vector(42 downto 0) := (others => 'X')  -- data
		);
	end component jesd204b_core_fec_hal_2100_lxszoea_cmp;

	for fec_hal_top : jesd204b_core_fec_hal_2100_lxszoea_cmp
		use entity fec_hal_2100.jesd204b_core_fec_hal_2100_lxszoea;
begin

	ch_fec_l_duplex_mode_atom_check : if ch_fec_l_duplex_mode_atom /= "DUPLEX_MODE_RX_ONLY_SIMPLEX" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_l_fec_spec_atom_check : if ch_fec_l_fec_spec_atom /= "FEC_SPEC_DISABLED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_l_fracture_atom_check : if ch_fec_l_fracture_atom /= "FRACTURE_UNUSED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_dr_enabled_atom_check : if ch_fec_dr_enabled_atom /= "DR_ENABLED_DR_ENABLED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_l_sup_mode_atom_check : if ch_fec_l_sup_mode_atom /= "SUP_MODE_USER_MODE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_l_sim_mode_atom_check : if ch_fec_l_sim_mode_atom /= "SIM_MODE_ENABLE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_l_pcs_tx_en_atom_check : if ch_fec_l_pcs_tx_en_atom /= "FALSE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_l_pcs_rx_en_atom_check : if ch_fec_l_pcs_rx_en_atom /= "FALSE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_l_loopback_mode_atom_check : if ch_fec_l_loopback_mode_atom /= "LOOPBACK_MODE_DISABLE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_l_dyn_tx_mux_atom_check : if ch_fec_l_dyn_tx_mux_atom /= "DYN_TX_MUX_UNUSED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_l_fec_error_atom_check : if ch_fec_l_fec_error_atom /= "FALSE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_l_fec_mode_atom_check : if ch_fec_l_fec_mode_atom /= "FEC_MODE_DISABLED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_l_tx_en_atom_check : if ch_fec_l_tx_en_atom /= "FALSE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_fec_l_rx_en_atom_check : if ch_fec_l_rx_en_atom /= "FALSE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	fec_hal_top : component jesd204b_core_fec_hal_2100_lxszoea_cmp
		generic map (
			ch_fec_l_duplex_mode_atom   => "DUPLEX_MODE_RX_ONLY_SIMPLEX",
			ch_fec_l_fec_spec_atom      => "FEC_SPEC_DISABLED",
			ch_fec_l_fracture_atom      => "FRACTURE_UNUSED",
			ch_fec_dr_enabled_atom      => "DR_ENABLED_DR_ENABLED",
			ch_fec_l_sup_mode_atom      => "SUP_MODE_USER_MODE",
			ch_fec_l_sim_mode_atom      => "SIM_MODE_ENABLE",
			ch_fec_l_pcs_tx_en_atom     => "FALSE",
			ch_fec_l_pcs_rx_en_atom     => "FALSE",
			ch_fec_l_loopback_mode_atom => "LOOPBACK_MODE_DISABLE",
			ch_fec_l_dyn_tx_mux_atom    => "DYN_TX_MUX_UNUSED",
			ch_fec_l_fec_error_atom     => "FALSE",
			ch_fec_l_fec_mode_atom      => "FEC_MODE_DISABLED",
			ch_fec_l_tx_en_atom         => "FALSE",
			ch_fec_l_rx_en_atom         => "FALSE"
		)
		port map (
			i_ch_lavmm_fec_addr                 => i_ch_lavmm_fec_addr,                 --                        reconfig.address
			i_ch_lavmm_fec_be                   => i_ch_lavmm_fec_be,                   --                                .byteenable
			i_ch_lavmm_fec_read                 => i_ch_lavmm_fec_read,                 --                                .read
			i_ch_lavmm_fec_wdata                => i_ch_lavmm_fec_wdata,                --                                .writedata
			i_ch_lavmm_fec_write                => i_ch_lavmm_fec_write,                --                                .write
			o_ch_lavmm_fec_rdata                => o_ch_lavmm_fec_rdata,                --                                .readdata
			o_ch_lavmm_fec_rdata_valid          => o_ch_lavmm_fec_rdata_valid,          --                                .readdatavalid
			o_ch_lavmm_fec_waitreq              => o_ch_lavmm_fec_waitreq,              --                                .waitrequest
			i_ch_lavmm_fec_clk                  => i_ch_lavmm_fec_clk,                  --                    reconfig_clk.clk
			i_ch_lavmm_fec_rstn                 => i_ch_lavmm_fec_rstn,                 --                    reconfig_rst.reset
			i_ch_eth_fec_tx_async               => i_ch_eth_fec_tx_async,               --                     asyncdata_0.data
			i_ch_eth_fec_tx_direct              => i_ch_eth_fec_tx_direct,              --                     asyncdata_1.data
			o_ch_eth_fec_rx_async               => o_ch_eth_fec_rx_async,               --                     asyncdata_2.data
			o_ch_eth_fec_rx_direct              => o_ch_eth_fec_rx_direct,              --                     asyncdata_3.data
			i_rstfec_fec_csr_ret                => i_rstfec_fec_csr_ret,                --            i_rstfec_fec_csr_ret.data
			o_fec_rx_rdy_n                      => o_fec_rx_rdy_n,                      --                  o_fec_rx_rdy_n.data
			i_rstfec_rx_fec_sfrz_n              => i_rstfec_rx_fec_sfrz_n,              --          i_rstfec_rx_fec_sfrz_n.data
			i_rstfec_fec_rx_rst_n               => i_rstfec_fec_rx_rst_n,               --           i_rstfec_fec_rx_rst_n.data
			i_rstfec_tx_fec_sfrz_n              => i_rstfec_tx_fec_sfrz_n,              --          i_rstfec_tx_fec_sfrz_n.reset
			i_rstfec_fec_tx_rst_n               => i_rstfec_fec_tx_rst_n,               --           i_rstfec_fec_tx_rst_n.data
			o_fec_rx_data                       => o_fec_rx_data,                       --                   o_fec_rx_data.data
			i_fec_clk                           => i_fec_clk,                           --                       i_fec_clk.clk
			i_xcvr_rx_data                      => i_xcvr_rx_data,                      --                  i_xcvr_rx_data.data
			o_xcvr_tx_data                      => o_xcvr_tx_data,                      --                  o_xcvr_tx_data.data
			i_pma_rx_sf                         => i_pma_rx_sf,                         --                     i_pma_rx_sf.data
			o_ch_lavmm_fec_addr_fec_wrap        => o_ch_lavmm_fec_addr_fec_wrap,        --                reconfig_fecwrap.address
			o_ch_lavmm_fec_be_fec_wrap          => o_ch_lavmm_fec_be_fec_wrap,          --                                .byteenable
			o_ch_lavmm_fec_read_fec_wrap        => o_ch_lavmm_fec_read_fec_wrap,        --                                .read
			o_ch_lavmm_fec_wdata_fec_wrap       => o_ch_lavmm_fec_wdata_fec_wrap,       --                                .writedata
			o_ch_lavmm_fec_write_fec_wrap       => o_ch_lavmm_fec_write_fec_wrap,       --                                .write
			i_ch_lavmm_fec_rdata_fec_wrap       => i_ch_lavmm_fec_rdata_fec_wrap,       --                                .readdata
			i_ch_lavmm_fec_rdata_valid_fec_wrap => i_ch_lavmm_fec_rdata_valid_fec_wrap, --                                .readdatavalid
			i_ch_lavmm_fec_waitreq_fec_wrap     => i_ch_lavmm_fec_waitreq_fec_wrap,     --                                .waitrequest
			o_ch_lavmm_fec_clk_fec_wrap         => o_ch_lavmm_fec_clk_fec_wrap,         --            reconfig_fecwrap_clk.clk
			o_ch_lavmm_fec_rstn_fec_wrap        => o_ch_lavmm_fec_rstn_fec_wrap,        --            reconfig_fecwrap_rst.reset
			i_ch_eth_fec_rx_async_fec_wrap      => i_ch_eth_fec_rx_async_fec_wrap,      --                     asyncdata_4.data
			i_ch_eth_fec_rx_direct_fec_wrap     => i_ch_eth_fec_rx_direct_fec_wrap,     --                     asyncdata_5.data
			o_ch_eth_fec_tx_async_fec_wrap      => o_ch_eth_fec_tx_async_fec_wrap,      --                     asyncdata_6.data
			o_ch_eth_fec_tx_direct_fec_wrap     => o_ch_eth_fec_tx_direct_fec_wrap,     --                     asyncdata_7.data
			o_rstfec_fec_csr_ret_fec_wrap       => o_rstfec_fec_csr_ret_fec_wrap,       --   o_rstfec_fec_csr_ret_fec_wrap.data
			i_fec_rx_rdy_n_fec_wrap             => i_fec_rx_rdy_n_fec_wrap,             --         i_fec_rx_rdy_n_fec_wrap.data
			o_rstfec_fec_rx_rst_n_fec_wrap      => o_rstfec_fec_rx_rst_n_fec_wrap,      --  o_rstfec_fec_rx_rst_n_fec_wrap.reset
			o_rstfec_fec_tx_rst_n_fec_wrap      => o_rstfec_fec_tx_rst_n_fec_wrap,      --  o_rstfec_fec_tx_rst_n_fec_wrap.reset
			o_rstfec_rx_fec_sfrz_n_fec_wrap     => o_rstfec_rx_fec_sfrz_n_fec_wrap,     -- o_rstfec_rx_fec_sfrz_n_fec_wrap.reset
			o_rstfec_tx_fec_sfrz_n_fec_wrap     => o_rstfec_tx_fec_sfrz_n_fec_wrap,     -- o_rstfec_tx_fec_sfrz_n_fec_wrap.reset
			i_fec_tx_data_mux_sel_fec_wrap      => i_fec_tx_data_mux_sel_fec_wrap,      --  i_fec_tx_data_mux_sel_fec_wrap.muxsel
			i_fec_rx_data_fec_wrap              => i_fec_rx_data_fec_wrap,              --          i_fec_rx_data_fec_wrap.data
			o_fec_i_tx_mux_data_fec_wrap        => o_fec_i_tx_mux_data_fec_wrap,        --    o_fec_i_tx_mux_data_fec_wrap.data
			o_xcvr_rx_data                      => o_xcvr_rx_data,                      --                  o_xcvr_rx_data.data
			i_xcvr_tx_data                      => i_xcvr_tx_data,                      --                  i_xcvr_tx_data.data
			o_pma_rx_sf                         => o_pma_rx_sf,                         --                     o_pma_rx_sf.data
			o_fec_tx_data_mux_sel               => o_fec_tx_data_mux_sel,               --           o_fec_tx_data_mux_sel.data
			i_fec_i_tx_mux_data                 => i_fec_i_tx_mux_data                  --             i_fec_i_tx_mux_data.data
		);

end architecture rtl; -- of jesd204b_core_one_lane_hal_fec_hal_2100_hmiwnzy
