# TCL File Generated by Component Editor 12.0
# Wed Aug 05 10:14:04 CDT 2015
# DO NOT MODIFY


# 
# tectonics_uart "tectonics_uart" v1.2
# Logic Tectonics 2015.08.05.10:14:04
# Tectonics UART Module
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module tectonics_uart
# 
set_module_property DESCRIPTION "Tectonics UART Module"
set_module_property NAME tectonics_uart
set_module_property VERSION 1.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols/Serial"
set_module_property AUTHOR "Logic Tectonics"
set_module_property DISPLAY_NAME tectonics_uart
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL tectonics_com_intfc_avl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file tectonics_com_intfc_avl.vhd VHDL      PATH ../../tectonics_com_intfc/rtl/tectonics_com_intfc_avl.vhd
add_fileset_file tectonics_com_intfc_avl_pkg.vhd VHDL  PATH ../../tectonics_com_intfc/rtl/tectonics_com_intfc_avl_pkg.vhd


# 
# parameters
# 
add_parameter g_vendor STRING altera
set_parameter_property g_vendor DEFAULT_VALUE altera
set_parameter_property g_vendor DISPLAY_NAME g_vendor
set_parameter_property g_vendor TYPE STRING
set_parameter_property g_vendor UNITS None
add_parameter g_arst_pol STD_LOGIC 1
set_parameter_property g_arst_pol DEFAULT_VALUE 1
set_parameter_property g_arst_pol DISPLAY_NAME g_arst_pol
set_parameter_property g_arst_pol TYPE STD_LOGIC
set_parameter_property g_arst_pol UNITS None
set_parameter_property g_arst_pol ALLOWED_RANGES 0:1
add_parameter g_tx_fifo_depth POSITIVE 2048
set_parameter_property g_tx_fifo_depth DEFAULT_VALUE 2048
set_parameter_property g_tx_fifo_depth DISPLAY_NAME g_tx_fifo_depth
set_parameter_property g_tx_fifo_depth TYPE POSITIVE
set_parameter_property g_tx_fifo_depth UNITS None
set_parameter_property g_tx_fifo_depth ALLOWED_RANGES 1:2147483647
add_parameter g_rx_fifo_depth POSITIVE 2048
set_parameter_property g_rx_fifo_depth DEFAULT_VALUE 2048
set_parameter_property g_rx_fifo_depth DISPLAY_NAME g_rx_fifo_depth
set_parameter_property g_rx_fifo_depth TYPE POSITIVE
set_parameter_property g_rx_fifo_depth UNITS None
set_parameter_property g_rx_fifo_depth ALLOWED_RANGES 1:2147483647
add_parameter g_tx_fifo_use_logic BOOLEAN false
set_parameter_property g_tx_fifo_use_logic DEFAULT_VALUE false
set_parameter_property g_tx_fifo_use_logic DISPLAY_NAME g_tx_fifo_use_logic
set_parameter_property g_tx_fifo_use_logic TYPE BOOLEAN
set_parameter_property g_tx_fifo_use_logic UNITS None
add_parameter g_rx_fifo_use_logic BOOLEAN false
set_parameter_property g_rx_fifo_use_logic DEFAULT_VALUE false
set_parameter_property g_rx_fifo_use_logic DISPLAY_NAME g_rx_fifo_use_logic
set_parameter_property g_rx_fifo_use_logic TYPE BOOLEAN
set_parameter_property g_rx_fifo_use_logic UNITS None


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset clock_reset
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 1
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 avl_slave_address address Input 8
add_interface_port avalon_slave_0 avl_slave_chipselect chipselect Input 1
add_interface_port avalon_slave_0 avl_slave_write write Input 1
add_interface_port avalon_slave_0 avl_slave_writedata writedata Input 32
add_interface_port avalon_slave_0 avl_slave_read read Input 1
add_interface_port avalon_slave_0 avl_slave_readdata readdata Output 32
add_interface_port avalon_slave_0 avl_slave_readdatavalid readdatavalid Output 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock_sink
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true

add_interface_port clock_reset arst reset Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink clk clk Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave_0
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset clock_reset
set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender avl_slave_irq irq Output 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end ser_out ser_out Output 1
add_interface_port conduit_end ser_in ser_in Input 1

