# TCL File Generated by Component Editor 24.3
# Sun Jan 05 17:31:31 CST 2025
# DO NOT MODIFY


# 
# jesd_12_chan_interface "JESD ADC 12 Channel IF" v1.0
# Logic Tectonics 2025.01.05.17:31:31
# Wrapper for 12 channels of ADCs through a JESD IF
# 

# 
# request TCL package from ACDS 24.3
# 
package require -exact qsys 24.3


# 
# module jesd_12_chan_interface
# 
set_module_property DESCRIPTION "Wrapper for 12 channels of ADCs through a JESD IF"
set_module_property NAME jesd_12_chan_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR "Logic Tectonics"
set_module_property DISPLAY_NAME "JESD ADC 12 Channel IF"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressGroup 0
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave bridgedAddressOffset ""
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave minimumResponseLatency 1
set_interface_property avalon_slave readLatency 1
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave transparentBridge false
set_interface_property avalon_slave waitrequestAllowance 0
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave dfhFeatureGuid 0
set_interface_property avalon_slave dfhGroupId 0
set_interface_property avalon_slave dfhParameterId ""
set_interface_property avalon_slave dfhParameterName ""
set_interface_property avalon_slave dfhParameterVersion ""
set_interface_property avalon_slave dfhParameterData ""
set_interface_property avalon_slave dfhParameterDataLength ""
set_interface_property avalon_slave dfhFeatureMajorVersion 0
set_interface_property avalon_slave dfhFeatureMinorVersion 0
set_interface_property avalon_slave dfhFeatureId 35
set_interface_property avalon_slave dfhFeatureType 3
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""
set_interface_property avalon_slave IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_slave SV_INTERFACE_TYPE ""
set_interface_property avalon_slave SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_slave address address Input 10
add_interface_port avalon_slave chipselect chipselect Input 1
add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave readdata readdata Output 32
add_interface_port avalon_slave waitrequest waitrequest Output 1
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""
set_interface_property clock_sink IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock_sink SV_INTERFACE_TYPE ""
set_interface_property clock_sink SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset_sink SV_INTERFACE_TYPE ""
set_interface_property reset_sink SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset_sink reset reset_n Input 1

