-- io_pll_sysref.vhd

-- Generated using ACDS version 25.1.1 125

library IEEE;
library altera_iopll_2000;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity io_pll_sysref is
	port (
		refclk     : in  std_logic := '0'; --     refclk.clk,    The reference clock source that drives the I/O PLL.
		locked     : out std_logic;        --     locked.export, The IOPLL IP core drives this port high when the PLL acquires lock. The port remains high as long as the I/O PLL is locked. The I/O PLL asserts the locked port when the phases and frequencies of the reference clock and feedback clock are the same or within the lock circuit tolerance. When the difference between the two clock signals exceeds the lock circuit tolerance, the I/O PLL loses lock.
		rst        : in  std_logic := '0'; --      reset.reset,  The asynchronous reset port for the output clocks. Drive this port high to reset all output clocks to the value of 0.
		permit_cal : in  std_logic := '0'; -- permit_cal.export, This is an input port for the downstream I/O PLL. Connect this permit_cal port to the locked output port of the upstream I/O PLL. Connecting this permit_cal port ensures that the cascaded I/O PLLs are calibrated in the correct order
		outclk_0   : out std_logic;        --    outclk0.clk,    Output clock Channel 0 from I/O PLL.
		outclk_1   : out std_logic;        --    outclk1.clk,    Output clock Channel 1 from I/O PLL.
		outclk_2   : out std_logic;        --    outclk2.clk,    Output clock Channel 2 from I/O PLL.
		outclk_3   : out std_logic;        --    outclk3.clk,    Output clock Channel 3 from I/O PLL.
		outclk_4   : out std_logic;        --    outclk4.clk,    Output clock Channel 4 from I/O PLL.
		outclk_5   : out std_logic         --    outclk5.clk,    Output clock Channel 5 from I/O PLL.
	);
end entity io_pll_sysref;

architecture rtl of io_pll_sysref is
	component io_pll_sysref_altera_iopll_2000_dk3q3xa_cmp is
		port (
			refclk     : in  std_logic := 'X'; -- clk
			locked     : out std_logic;        -- export
			rst        : in  std_logic := 'X'; -- reset
			permit_cal : in  std_logic := 'X'; -- export
			outclk_0   : out std_logic;        -- clk
			outclk_1   : out std_logic;        -- clk
			outclk_2   : out std_logic;        -- clk
			outclk_3   : out std_logic;        -- clk
			outclk_4   : out std_logic;        -- clk
			outclk_5   : out std_logic         -- clk
		);
	end component io_pll_sysref_altera_iopll_2000_dk3q3xa_cmp;

	for iopll_0 : io_pll_sysref_altera_iopll_2000_dk3q3xa_cmp
		use entity altera_iopll_2000.io_pll_sysref_altera_iopll_2000_dk3q3xa;
begin

	iopll_0 : component io_pll_sysref_altera_iopll_2000_dk3q3xa_cmp
		port map (
			refclk     => refclk,     --     refclk.clk
			locked     => locked,     --     locked.export
			rst        => rst,        --      reset.reset
			permit_cal => permit_cal, -- permit_cal.export
			outclk_0   => outclk_0,   --    outclk0.clk
			outclk_1   => outclk_1,   --    outclk1.clk
			outclk_2   => outclk_2,   --    outclk2.clk
			outclk_3   => outclk_3,   --    outclk3.clk
			outclk_4   => outclk_4,   --    outclk4.clk
			outclk_5   => outclk_5    --    outclk5.clk
		);

end architecture rtl; -- of io_pll_sysref
