-- alt_async_fifo_wr32_rd32_32_deep_dr_la.vhd

-- Generated using ACDS version 25.1.1 125

library IEEE;
library fifo_1941;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity alt_async_fifo_wr32_rd32_32_deep_dr_la is
	port (
		data    : in  std_logic_vector(31 downto 0) := (others => '0'); --  fifo_input.datain,  Data input of the memory.The data port is required for all FIFO operation.
		wrreq   : in  std_logic                     := '0';             --            .wrreq,   wrreq input signal to request for write operation.The wrreq signal is required for all FIFO operation.
		rdreq   : in  std_logic                     := '0';             --            .rdreq,   rdreq input signal to request for read operation.The rdreq signal is required for all FIFO operation.
		wrclk   : in  std_logic                     := '0';             --            .wrclk,   Positive-edge-triggered clock.
		rdclk   : in  std_logic                     := '0';             --            .rdclk,   Positive-edge-triggered clock.
		aclr    : in  std_logic                     := '0';             --            .aclr,    It is asynchronous reset.Assert this signal to clear all the output status ports, but the effect on the q output may vary for different FIFO configurations.
		q       : out std_logic_vector(31 downto 0);                    -- fifo_output.dataout, Data output of the memory. This port is required for all FIFO operation.
		rdusedw : out std_logic_vector(4 downto 0);                     --            .rdusedw, Show the number of words available for reading in the FIFO.
		wrusedw : out std_logic_vector(4 downto 0);                     --            .wrusedw, Show the number of words written into the FIFO.
		rdfull  : out std_logic;                                        --            .rdfull,   rdfull signal is a delayed version of the wrfull signal. However,the rdfull signal functions as a combinational output instead of a derived version of the wrfull signal.
		rdempty : out std_logic;                                        --            .rdempty, When rddmpty signal is asserted, the FIFO IP core is considered empty. You must always refer to the rdempty port to ensure whether or not a valid read request operation can be performed,regardless of the target device.
		wrfull  : out std_logic                                         --            .wrfull,  when wrfull signal is asserted, the FIFO IP core is considered full.You must always refer to the wrfull port to ensure whether or not a valid write request operation can be performed,regardless of the target device.
	);
end entity alt_async_fifo_wr32_rd32_32_deep_dr_la;

architecture rtl of alt_async_fifo_wr32_rd32_32_deep_dr_la is
	component alt_async_fifo_wr32_rd32_32_deep_dr_la_fifo_1941_4gmv4ey_cmp is
		port (
			data    : in  std_logic_vector(31 downto 0) := (others => 'X'); -- datain
			wrreq   : in  std_logic                     := 'X';             -- wrreq
			rdreq   : in  std_logic                     := 'X';             -- rdreq
			wrclk   : in  std_logic                     := 'X';             -- wrclk
			rdclk   : in  std_logic                     := 'X';             -- rdclk
			aclr    : in  std_logic                     := 'X';             -- aclr
			q       : out std_logic_vector(31 downto 0);                    -- dataout
			rdusedw : out std_logic_vector(4 downto 0);                     -- rdusedw
			wrusedw : out std_logic_vector(4 downto 0);                     -- wrusedw
			rdfull  : out std_logic;                                        -- rdfull
			rdempty : out std_logic;                                        -- rdempty
			wrfull  : out std_logic                                         -- wrfull
		);
	end component alt_async_fifo_wr32_rd32_32_deep_dr_la_fifo_1941_4gmv4ey_cmp;

	for fifo_0 : alt_async_fifo_wr32_rd32_32_deep_dr_la_fifo_1941_4gmv4ey_cmp
		use entity fifo_1941.alt_async_fifo_wr32_rd32_32_deep_dr_la_fifo_1941_4gmv4ey;
begin

	fifo_0 : component alt_async_fifo_wr32_rd32_32_deep_dr_la_fifo_1941_4gmv4ey_cmp
		port map (
			data    => data,    --  fifo_input.datain
			wrreq   => wrreq,   --            .wrreq
			rdreq   => rdreq,   --            .rdreq
			wrclk   => wrclk,   --            .wrclk
			rdclk   => rdclk,   --            .rdclk
			aclr    => aclr,    --            .aclr
			q       => q,       -- fifo_output.dataout
			rdusedw => rdusedw, --            .rdusedw
			wrusedw => wrusedw, --            .wrusedw
			rdfull  => rdfull,  --            .rdfull
			rdempty => rdempty, --            .rdempty
			wrfull  => wrfull   --            .wrfull
		);

end architecture rtl; -- of alt_async_fifo_wr32_rd32_32_deep_dr_la
