-- jesd204b_core.vhd

-- Generated using ACDS version 25.1.1 125

library IEEE;
library intel_jesd204b_gts_400;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity jesd204b_core is
	port (
		pma_cu_clk                     : in  std_logic                     := '0';             --                     pma_cu_clk.clk
		pll_refclk                     : in  std_logic                     := '0';             --                     pll_refclk.clk
		src_sss_grant                  : in  std_logic_vector(1 downto 0)  := (others => '0'); --                  src_sss_grant.src_rs_grant
		src_sss_req                    : out std_logic_vector(1 downto 0);                     --                    src_sss_req.src_rs_req
		o_refclk_bus_out               : out std_logic;                                        --               o_refclk_bus_out.refclk_bus_out
		jesd204_rx_rst_n               : in  std_logic                     := '0';             --               jesd204_rx_rst_n.reset_n
		rx_serial_data                 : in  std_logic_vector(1 downto 0)  := (others => '0'); --                 rx_serial_data.export
		rx_serial_data_n               : in  std_logic_vector(1 downto 0)  := (others => '0'); --               rx_serial_data_n.export
		rxphy_clk                      : out std_logic_vector(1 downto 0);                     --                      rxphy_clk.export
		jesd204_rx_rst_ack_n           : out std_logic;                                        --           jesd204_rx_rst_ack_n.export
		rx_locked_to_data              : out std_logic_vector(1 downto 0);                     --              rx_locked_to_data.export
		jesd204_rx_out_of_reset        : out std_logic;                                        --        jesd204_rx_out_of_reset.export
		jesd204_rx_avs_chipselect      : in  std_logic                     := '0';             --                 jesd204_rx_avs.chipselect
		jesd204_rx_avs_address         : in  std_logic_vector(9 downto 0)  := (others => '0'); --                               .address
		jesd204_rx_avs_read            : in  std_logic                     := '0';             --                               .read
		jesd204_rx_avs_readdata        : out std_logic_vector(31 downto 0);                    --                               .readdata
		jesd204_rx_avs_waitrequest     : out std_logic;                                        --                               .waitrequest
		jesd204_rx_avs_write           : in  std_logic                     := '0';             --                               .write
		jesd204_rx_avs_writedata       : in  std_logic_vector(31 downto 0) := (others => '0'); --                               .writedata
		jesd204_rx_int                 : out std_logic;                                        --                 jesd204_rx_int.irq
		jesd204_rx_link_data           : out std_logic_vector(63 downto 0);                    --                jesd204_rx_link.data
		jesd204_rx_link_valid          : out std_logic;                                        --                               .valid
		jesd204_rx_link_ready          : in  std_logic                     := '0';             --                               .ready
		jesd204_rx_dev_sync_n          : out std_logic;                                        --          jesd204_rx_dev_sync_n.export
		jesd204_rx_sysref              : in  std_logic                     := '0';             --              jesd204_rx_sysref.export
		jesd204_rx_somf                : out std_logic_vector(3 downto 0);                     --                jesd204_rx_somf.export
		jesd204_rx_csr_hd              : out std_logic;                                        --              jesd204_rx_csr_hd.export
		jesd204_rx_csr_cs              : out std_logic_vector(1 downto 0);                     --              jesd204_rx_csr_cs.export
		jesd204_rx_csr_l               : out std_logic_vector(4 downto 0);                     --               jesd204_rx_csr_l.export
		jesd204_rx_csr_k               : out std_logic_vector(4 downto 0);                     --               jesd204_rx_csr_k.export
		jesd204_rx_csr_n               : out std_logic_vector(4 downto 0);                     --               jesd204_rx_csr_n.export
		jesd204_rx_csr_np              : out std_logic_vector(4 downto 0);                     --              jesd204_rx_csr_np.export
		jesd204_rx_csr_s               : out std_logic_vector(4 downto 0);                     --               jesd204_rx_csr_s.export
		jesd204_rx_csr_cf              : out std_logic_vector(4 downto 0);                     --              jesd204_rx_csr_cf.export
		jesd204_rx_csr_f               : out std_logic_vector(7 downto 0);                     --               jesd204_rx_csr_f.export
		jesd204_rx_csr_m               : out std_logic_vector(7 downto 0);                     --               jesd204_rx_csr_m.export
		jesd204_rx_alldev_lane_aligned : in  std_logic                     := '0';             -- jesd204_rx_alldev_lane_aligned.export
		jesd204_rx_dev_lane_aligned    : out std_logic;                                        --    jesd204_rx_dev_lane_aligned.export
		jesd204_rx_sof                 : out std_logic_vector(3 downto 0);                     --                 jesd204_rx_sof.export
		jesd204_rx_frame_error         : in  std_logic                     := '0';             --         jesd204_rx_frame_error.export
		csr_rx_testmode                : out std_logic_vector(3 downto 0);                     --                csr_rx_testmode.export
		jesd204_rx_dlb_data            : in  std_logic_vector(63 downto 0) := (others => '0'); --            jesd204_rx_dlb_data.export
		jesd204_rx_dlb_data_valid      : in  std_logic_vector(1 downto 0)  := (others => '0'); --      jesd204_rx_dlb_data_valid.export
		jesd204_rx_dlb_kchar_data      : in  std_logic_vector(7 downto 0)  := (others => '0'); --      jesd204_rx_dlb_kchar_data.export
		jesd204_rx_dlb_errdetect       : in  std_logic_vector(7 downto 0)  := (others => '0'); --       jesd204_rx_dlb_errdetect.export
		jesd204_rx_dlb_disperr         : in  std_logic_vector(7 downto 0)  := (others => '0'); --         jesd204_rx_dlb_disperr.export
		jesd204_rx_avs_rst_n           : in  std_logic                     := '0';             --           jesd204_rx_avs_rst_n.reset_n
		jesd204_rx_avs_clk             : in  std_logic                     := '0';             --             jesd204_rx_avs_clk.clk
		rxlink_clk                     : in  std_logic                     := '0'              --                     rxlink_clk.clk,           Clock Input
	);
end entity jesd204b_core;

architecture rtl of jesd204b_core is
	component jesd204b_core_intel_jesd204b_gts_400_tfixbgi_cmp is
		generic (
			DEVICE_FAMILY          : string  := "";
			SUBCLASSV              : integer := 0;
			clocking_mode          : string  := "PMA";
			PCS_CONFIG             : string  := "JESD_PCS_CFG2";
			SER_SIZE               : integer := 4;
			PMA_WIDTH              : integer := 40;
			FK                     : integer := 64;
			L                      : integer := 4;
			M                      : integer := 8;
			F                      : integer := 4;
			N                      : integer := 16;
			N_PRIME                : integer := 16;
			K                      : integer := 16;
			S                      : integer := 1;
			SCR                    : integer := 1;
			CS                     : integer := 0;
			CF                     : integer := 0;
			HD                     : boolean := false;
			ECC_EN                 : boolean := true;
			ENABLE_PERFORMANCE     : boolean := true;
			PHADJ                  : integer := 0;
			ADJCNT                 : integer := 0;
			ADJDIR                 : integer := 0;
			TX_EFIFO_PIPE_EN       : boolean := false;
			RX_EFIFO_PIPE_EN       : boolean := false;
			DID                    : integer := 0;
			BID                    : integer := 0;
			JESDV                  : integer := 1;
			OPTIMIZE               : integer := 0;
			BIT_REVERSAL           : integer := 0;
			BYTE_REVERSAL          : integer := 0;
			RES1                   : integer := 0;
			RES2                   : integer := 0;
			LID0                   : integer := 0;
			FCHK0                  : integer := 0;
			LID1                   : integer := 1;
			FCHK1                  : integer := 0;
			LID2                   : integer := 2;
			FCHK2                  : integer := 0;
			LID3                   : integer := 3;
			FCHK3                  : integer := 0;
			LID4                   : integer := 4;
			FCHK4                  : integer := 0;
			LID5                   : integer := 5;
			FCHK5                  : integer := 0;
			LID6                   : integer := 6;
			FCHK6                  : integer := 0;
			LID7                   : integer := 7;
			FCHK7                  : integer := 0;
			ALIGNMENT_PATTERN      : integer := 658812;
			PULSE_WIDTH            : integer := 4;
			LS_FIFO_DEPTH          : integer := 256;
			LS_FIFO_WIDTHU         : integer := 8;
			AVST_WIDTH             : integer := 2;
			RECONFIG_ADDRESS_WIDTH : integer := 21;
			SUBCLASSV_2            : integer := 0;
			PCS_CONFIG_2           : string  := "JESD_PCS_CFG2";
			L_2                    : integer := 4;
			M_2                    : integer := 8;
			F_2                    : integer := 4;
			N_2                    : integer := 16;
			N_PRIME_2              : integer := 16;
			K_2                    : integer := 16;
			S_2                    : integer := 1;
			SCR_2                  : integer := 1;
			CS_2                   : integer := 0;
			CF_2                   : integer := 0;
			HD_2                   : boolean := false;
			ECC_EN_2               : boolean := true;
			PHADJ_2                : integer := 0;
			ADJCNT_2               : integer := 0;
			ADJDIR_2               : integer := 0;
			DID_2                  : integer := 0;
			BID_2                  : integer := 0;
			JESDV_2                : integer := 1;
			OPTIMIZE_2             : integer := 0;
			RES1_2                 : integer := 0;
			RES2_2                 : integer := 0;
			LID0_2                 : integer := 0;
			FCHK0_2                : integer := 0;
			LID1_2                 : integer := 1;
			FCHK1_2                : integer := 0;
			LID2_2                 : integer := 2;
			FCHK2_2                : integer := 0;
			LID3_2                 : integer := 3;
			FCHK3_2                : integer := 0;
			LID4_2                 : integer := 4;
			FCHK4_2                : integer := 0;
			LID5_2                 : integer := 5;
			FCHK5_2                : integer := 0;
			LID6_2                 : integer := 6;
			FCHK6_2                : integer := 0;
			LID7_2                 : integer := 7;
			FCHK7_2                : integer := 0;
			LS_FIFO_DEPTH_2        : integer := 256
		);
		port (
			pma_cu_clk                     : in  std_logic                     := 'X';             -- clk
			pll_refclk                     : in  std_logic                     := 'X';             -- clk
			src_sss_grant                  : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- src_rs_grant
			src_sss_req                    : out std_logic_vector(1 downto 0);                     -- src_rs_req
			o_refclk_bus_out               : out std_logic;                                        -- refclk_bus_out
			jesd204_rx_rst_n               : in  std_logic                     := 'X';             -- reset_n
			rx_serial_data                 : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- export
			rx_serial_data_n               : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- export
			rxphy_clk                      : out std_logic_vector(1 downto 0);                     -- export
			jesd204_rx_rst_ack_n           : out std_logic;                                        -- export
			rx_locked_to_data              : out std_logic_vector(1 downto 0);                     -- export
			jesd204_rx_out_of_reset        : out std_logic;                                        -- export
			jesd204_rx_avs_chipselect      : in  std_logic                     := 'X';             -- chipselect
			jesd204_rx_avs_address         : in  std_logic_vector(9 downto 0)  := (others => 'X'); -- address
			jesd204_rx_avs_read            : in  std_logic                     := 'X';             -- read
			jesd204_rx_avs_readdata        : out std_logic_vector(31 downto 0);                    -- readdata
			jesd204_rx_avs_waitrequest     : out std_logic;                                        -- waitrequest
			jesd204_rx_avs_write           : in  std_logic                     := 'X';             -- write
			jesd204_rx_avs_writedata       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			jesd204_rx_int                 : out std_logic;                                        -- irq
			jesd204_rx_link_data           : out std_logic_vector(63 downto 0);                    -- data
			jesd204_rx_link_valid          : out std_logic;                                        -- valid
			jesd204_rx_link_ready          : in  std_logic                     := 'X';             -- ready
			jesd204_rx_dev_sync_n          : out std_logic;                                        -- export
			jesd204_rx_sysref              : in  std_logic                     := 'X';             -- export
			jesd204_rx_somf                : out std_logic_vector(3 downto 0);                     -- export
			jesd204_rx_csr_hd              : out std_logic;                                        -- export
			jesd204_rx_csr_cs              : out std_logic_vector(1 downto 0);                     -- export
			jesd204_rx_csr_l               : out std_logic_vector(4 downto 0);                     -- export
			jesd204_rx_csr_k               : out std_logic_vector(4 downto 0);                     -- export
			jesd204_rx_csr_n               : out std_logic_vector(4 downto 0);                     -- export
			jesd204_rx_csr_np              : out std_logic_vector(4 downto 0);                     -- export
			jesd204_rx_csr_s               : out std_logic_vector(4 downto 0);                     -- export
			jesd204_rx_csr_cf              : out std_logic_vector(4 downto 0);                     -- export
			jesd204_rx_csr_f               : out std_logic_vector(7 downto 0);                     -- export
			jesd204_rx_csr_m               : out std_logic_vector(7 downto 0);                     -- export
			jesd204_rx_alldev_lane_aligned : in  std_logic                     := 'X';             -- export
			jesd204_rx_dev_lane_aligned    : out std_logic;                                        -- export
			jesd204_rx_sof                 : out std_logic_vector(3 downto 0);                     -- export
			jesd204_rx_frame_error         : in  std_logic                     := 'X';             -- export
			csr_rx_testmode                : out std_logic_vector(3 downto 0);                     -- export
			jesd204_rx_dlb_data            : in  std_logic_vector(63 downto 0) := (others => 'X'); -- export
			jesd204_rx_dlb_data_valid      : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- export
			jesd204_rx_dlb_kchar_data      : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- export
			jesd204_rx_dlb_errdetect       : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- export
			jesd204_rx_dlb_disperr         : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- export
			jesd204_rx_avs_rst_n           : in  std_logic                     := 'X';             -- reset_n
			jesd204_rx_avs_clk             : in  std_logic                     := 'X';             -- clk
			rxlink_clk                     : in  std_logic                     := 'X'              -- clk
		);
	end component jesd204b_core_intel_jesd204b_gts_400_tfixbgi_cmp;

	for intel_jesd204b_gts_0 : jesd204b_core_intel_jesd204b_gts_400_tfixbgi_cmp
		use entity intel_jesd204b_gts_400.jesd204b_core_intel_jesd204b_gts_400_tfixbgi;
begin

	intel_jesd204b_gts_0 : component jesd204b_core_intel_jesd204b_gts_400_tfixbgi_cmp
		generic map (
			DEVICE_FAMILY          => "Agilex 5",
			SUBCLASSV              => 1,
			clocking_mode          => "PMA",
			PCS_CONFIG             => "JESD_PCS_CFG2",
			SER_SIZE               => 4,
			PMA_WIDTH              => 40,
			FK                     => 64,
			L                      => 2,
			M                      => 2,
			F                      => 2,
			N                      => 8,
			N_PRIME                => 8,
			K                      => 32,
			S                      => 2,
			SCR                    => 1,
			CS                     => 0,
			CF                     => 0,
			HD                     => false,
			ECC_EN                 => true,
			ENABLE_PERFORMANCE     => true,
			PHADJ                  => 0,
			ADJCNT                 => 0,
			ADJDIR                 => 0,
			TX_EFIFO_PIPE_EN       => false,
			RX_EFIFO_PIPE_EN       => false,
			DID                    => 0,
			BID                    => 0,
			JESDV                  => 1,
			OPTIMIZE               => 0,
			BIT_REVERSAL           => 0,
			BYTE_REVERSAL          => 0,
			RES1                   => 0,
			RES2                   => 0,
			LID0                   => 0,
			FCHK0                  => 0,
			LID1                   => 1,
			FCHK1                  => 0,
			LID2                   => 2,
			FCHK2                  => 0,
			LID3                   => 3,
			FCHK3                  => 0,
			LID4                   => 4,
			FCHK4                  => 0,
			LID5                   => 5,
			FCHK5                  => 0,
			LID6                   => 6,
			FCHK6                  => 0,
			LID7                   => 7,
			FCHK7                  => 0,
			ALIGNMENT_PATTERN      => 658812,
			PULSE_WIDTH            => 5,
			LS_FIFO_DEPTH          => 32,
			LS_FIFO_WIDTHU         => 5,
			AVST_WIDTH             => 128,
			RECONFIG_ADDRESS_WIDTH => 19,
			SUBCLASSV_2            => 0,
			PCS_CONFIG_2           => "JESD_PCS_CFG2",
			L_2                    => 4,
			M_2                    => 8,
			F_2                    => 4,
			N_2                    => 16,
			N_PRIME_2              => 16,
			K_2                    => 16,
			S_2                    => 1,
			SCR_2                  => 1,
			CS_2                   => 0,
			CF_2                   => 0,
			HD_2                   => false,
			ECC_EN_2               => true,
			PHADJ_2                => 0,
			ADJCNT_2               => 0,
			ADJDIR_2               => 0,
			DID_2                  => 0,
			BID_2                  => 0,
			JESDV_2                => 1,
			OPTIMIZE_2             => 0,
			RES1_2                 => 0,
			RES2_2                 => 0,
			LID0_2                 => 0,
			FCHK0_2                => 0,
			LID1_2                 => 1,
			FCHK1_2                => 0,
			LID2_2                 => 2,
			FCHK2_2                => 0,
			LID3_2                 => 3,
			FCHK3_2                => 0,
			LID4_2                 => 4,
			FCHK4_2                => 0,
			LID5_2                 => 5,
			FCHK5_2                => 0,
			LID6_2                 => 6,
			FCHK6_2                => 0,
			LID7_2                 => 7,
			FCHK7_2                => 0,
			LS_FIFO_DEPTH_2        => 256
		)
		port map (
			pma_cu_clk                     => pma_cu_clk,                     --                     pma_cu_clk.clk
			pll_refclk                     => pll_refclk,                     --                     pll_refclk.clk
			src_sss_grant                  => src_sss_grant,                  --                  src_sss_grant.src_rs_grant
			src_sss_req                    => src_sss_req,                    --                    src_sss_req.src_rs_req
			o_refclk_bus_out               => o_refclk_bus_out,               --               o_refclk_bus_out.refclk_bus_out
			jesd204_rx_rst_n               => jesd204_rx_rst_n,               --               jesd204_rx_rst_n.reset_n
			rx_serial_data                 => rx_serial_data,                 --                 rx_serial_data.export
			rx_serial_data_n               => rx_serial_data_n,               --               rx_serial_data_n.export
			rxphy_clk                      => rxphy_clk,                      --                      rxphy_clk.export
			jesd204_rx_rst_ack_n           => jesd204_rx_rst_ack_n,           --           jesd204_rx_rst_ack_n.export
			rx_locked_to_data              => rx_locked_to_data,              --              rx_locked_to_data.export
			jesd204_rx_out_of_reset        => jesd204_rx_out_of_reset,        --        jesd204_rx_out_of_reset.export
			jesd204_rx_avs_chipselect      => jesd204_rx_avs_chipselect,      --                 jesd204_rx_avs.chipselect
			jesd204_rx_avs_address         => jesd204_rx_avs_address,         --                               .address
			jesd204_rx_avs_read            => jesd204_rx_avs_read,            --                               .read
			jesd204_rx_avs_readdata        => jesd204_rx_avs_readdata,        --                               .readdata
			jesd204_rx_avs_waitrequest     => jesd204_rx_avs_waitrequest,     --                               .waitrequest
			jesd204_rx_avs_write           => jesd204_rx_avs_write,           --                               .write
			jesd204_rx_avs_writedata       => jesd204_rx_avs_writedata,       --                               .writedata
			jesd204_rx_int                 => jesd204_rx_int,                 --                 jesd204_rx_int.irq
			jesd204_rx_link_data           => jesd204_rx_link_data,           --                jesd204_rx_link.data
			jesd204_rx_link_valid          => jesd204_rx_link_valid,          --                               .valid
			jesd204_rx_link_ready          => jesd204_rx_link_ready,          --                               .ready
			jesd204_rx_dev_sync_n          => jesd204_rx_dev_sync_n,          --          jesd204_rx_dev_sync_n.export
			jesd204_rx_sysref              => jesd204_rx_sysref,              --              jesd204_rx_sysref.export
			jesd204_rx_somf                => jesd204_rx_somf,                --                jesd204_rx_somf.export
			jesd204_rx_csr_hd              => jesd204_rx_csr_hd,              --              jesd204_rx_csr_hd.export
			jesd204_rx_csr_cs              => jesd204_rx_csr_cs,              --              jesd204_rx_csr_cs.export
			jesd204_rx_csr_l               => jesd204_rx_csr_l,               --               jesd204_rx_csr_l.export
			jesd204_rx_csr_k               => jesd204_rx_csr_k,               --               jesd204_rx_csr_k.export
			jesd204_rx_csr_n               => jesd204_rx_csr_n,               --               jesd204_rx_csr_n.export
			jesd204_rx_csr_np              => jesd204_rx_csr_np,              --              jesd204_rx_csr_np.export
			jesd204_rx_csr_s               => jesd204_rx_csr_s,               --               jesd204_rx_csr_s.export
			jesd204_rx_csr_cf              => jesd204_rx_csr_cf,              --              jesd204_rx_csr_cf.export
			jesd204_rx_csr_f               => jesd204_rx_csr_f,               --               jesd204_rx_csr_f.export
			jesd204_rx_csr_m               => jesd204_rx_csr_m,               --               jesd204_rx_csr_m.export
			jesd204_rx_alldev_lane_aligned => jesd204_rx_alldev_lane_aligned, -- jesd204_rx_alldev_lane_aligned.export
			jesd204_rx_dev_lane_aligned    => jesd204_rx_dev_lane_aligned,    --    jesd204_rx_dev_lane_aligned.export
			jesd204_rx_sof                 => jesd204_rx_sof,                 --                 jesd204_rx_sof.export
			jesd204_rx_frame_error         => jesd204_rx_frame_error,         --         jesd204_rx_frame_error.export
			csr_rx_testmode                => csr_rx_testmode,                --                csr_rx_testmode.export
			jesd204_rx_dlb_data            => jesd204_rx_dlb_data,            --            jesd204_rx_dlb_data.export
			jesd204_rx_dlb_data_valid      => jesd204_rx_dlb_data_valid,      --      jesd204_rx_dlb_data_valid.export
			jesd204_rx_dlb_kchar_data      => jesd204_rx_dlb_kchar_data,      --      jesd204_rx_dlb_kchar_data.export
			jesd204_rx_dlb_errdetect       => jesd204_rx_dlb_errdetect,       --       jesd204_rx_dlb_errdetect.export
			jesd204_rx_dlb_disperr         => jesd204_rx_dlb_disperr,         --         jesd204_rx_dlb_disperr.export
			jesd204_rx_avs_rst_n           => jesd204_rx_avs_rst_n,           --           jesd204_rx_avs_rst_n.reset_n
			jesd204_rx_avs_clk             => jesd204_rx_avs_clk,             --             jesd204_rx_avs_clk.clk
			rxlink_clk                     => rxlink_clk                      --                     rxlink_clk.clk
		);

end architecture rtl; -- of jesd204b_core
