// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`ifdef ALTERA_RESERVED_QIS
// See https://wiki.ith.intel.com/pages/viewpage.action?pageId=3466839469#SMHSSIMisc.Notes-__USE_SOF_SETTINGS__
`ifndef __TILE_IP_SIM_FLOW__
`define __USE_SOF_SETTINGS__
`endif
`endif

module shared_ptp #(
    parameter sm_pld_tx_demux_0__sel                = "SEL_UNUSED",
    parameter pld_chnl_rx_fifo_wr_clk_mux_0__sel    = "SEL_UNUSED",
    parameter pld_chnl_tx_fifo_rd_clk_mux_0__sel    = "SEL_UNUSED",
    parameter pld_rx_mux_0__sel                     = "SEL_UNUSED",
    parameter dr_enabled                            = "DR_ENABLED_DR_DISABLED",
    parameter duplex_mode                           = "DUPLEX_MODE_DUPLEX",
    parameter pld_channel_identifier                = "PLD_CHANNEL_IDENTIFIER_PTP",
    parameter rx_clkout1_divider                    = "RX_CLKOUT1_DIVIDER_DIV1",
    parameter rx_clkout2_divider                    = "RX_CLKOUT2_DIVIDER_DIV1",
    parameter rx_en                                 = "FALSE",
    parameter rx_fifo_mode                          = "RX_FIFO_MODE_PHASE_COMP",
    parameter rx_fifo_width                         = "RX_FIFO_WIDTH_DOUBLE_WIDTH",
    parameter rx_fifo_wr_clk_hz                     = 36'b000000000000000000000000000000000000,
    parameter rx_user1_clk_dynamic_mux              = "RX_USER1_CLK_DYNAMIC_MUX_UNUSED",
    parameter rx_user2_clk_dynamic_mux              = "RX_USER2_CLK_DYNAMIC_MUX_UNUSED",
    parameter sup_mode                              = "SUP_MODE_USER_MODE",
    parameter tx_clkout1_divider                    = "TX_CLKOUT1_DIVIDER_DIV1",
    parameter tx_clkout2_divider                    = "TX_CLKOUT2_DIVIDER_DIV1",
    parameter tx_en                                 = "FALSE",
    parameter tx_fifo_mode                          = "TX_FIFO_MODE_PHASE_COMP",
    parameter tx_fifo_rd_clk_hz                     = 36'b000000000000000000000000000000000000,
    parameter tx_fifo_width                         = "TX_FIFO_WIDTH_DOUBLE_WIDTH",
    parameter tx_user1_clk_dynamic_mux              = "TX_USER1_CLK_DYNAMIC_MUX_UNUSED",
    parameter tx_user2_clk_dynamic_mux              = "TX_USER2_CLK_DYNAMIC_MUX_UNUSED",
    parameter vc_rx_pldif_wm_en                     = "VC_RX_PLDIF_WM_EN_ENABLE",
    parameter ptp0_en                               = "PTP0_EN_ENABLE",
    parameter ptp0_sim_mode                         = "PTP0_SIM_MODE_ENABLE",
    parameter ptp0_sup_mode                         = "PTP0_SUP_MODE_USER_MODE",
    parameter ptp1_en                               = "PTP1_EN_ENABLE",
    parameter ptp1_sim_mode                         = "PTP1_SIM_MODE_ENABLE",
    parameter ptp1_sup_mode                         = "PTP1_SUP_MODE_USER_MODE",
    parameter device_die_type                       = "MAIN_SM7"
)
 (
    input [20:0] i_hio_lavmm_addr,
    input [31:0] i_hio_lavmm_wdata,
    input [31:0] i_ss_lavmm_pcie_rdata,
    input [39:0] sm_pld_rx_mux_0__i_eth,
    input [3:0] i_hio_lavmm_be,
    input [79:0] sm_pld_rx_mux_0__i_pcie,
    input [79:0] i_hio_txdata,
    input [79:0] i_hio_uxquad_async,
    input [79:0] i_hio_uxquad_async_pcie_mux,
    input [7:0] i_egress1_ptp_rx_data,
    input [8:0] i_ingress1_ptp_tx_intfc_ptp_data,
    input [8:0] i_ingress1_ptp_tx_intfc_ptp_data_ld,
    input [99:0] i_hio_txdata_async,
    input [9:0] i_hio_txdata_direct,
    input [9:0] i_hio_txdata_extra,
    input pld_chnl_rx_fifo_wr_clk_mux_0__i_eth_or_ptp,
    input pld_chnl_rx_fifo_wr_clk_mux_0__i_pcie,
    input i_hio_det_lat_rx_dl_clk,
    input i_hio_det_lat_rx_mux_select,
    input i_hio_det_lat_rx_sclk_flop,
    input i_hio_det_lat_rx_sclk_gen_clk,
    input i_hio_det_lat_rx_trig_flop,
    input i_hio_det_lat_sampling_clk,
    input i_hio_det_lat_tx_dl_clk,
    input i_hio_det_lat_tx_mux_select,
    input i_hio_det_lat_tx_sclk_flop,
    input i_hio_det_lat_tx_sclk_gen_clk,
    input i_hio_det_lat_tx_trig_flop,
    input i_hio_lavmm_clk,
    input i_hio_lavmm_read,
    input i_hio_lavmm_rstn,
    input i_hio_lavmm_write,
    input i_hio_pld_reset_clk_row,
    input i_hio_pld_rx_clk_in_row_clk,
    input i_hio_pld_tx_clk_in_row_clk,
    input i_hio_ptp_rst_n,
    input i_hio_rst_pld_adapter_rx_pld_rst_n,
    input i_hio_rst_pld_adapter_tx_pld_rst_n,
    input i_hio_rst_pld_ready,
    input i_hio_rxdata_fifo_rd_en,
    input i_hio_txdata_fifo_wr_en,
    input i_ss_lavmm_pcie_rdata_valid,
    input i_ss_lavmm_pcie_waitreq,
    input i_ss_user_rx_clk1_clk,
    input i_ss_user_rx_clk2_clk,
    input i_ss_user_tx_clk1_clk,
    input i_ss_user_tx_clk2_clk,
    input i_ingress1_ptp_tx_wa_ld,
    output [16:0] o_ss_lavmm_pcie_addr,
    output [2:0] k_user_rx_clk1_c0c1c2_sel,
    output [2:0] k_user_rx_clk2_c0c1c2_sel,
    output [2:0] k_user_tx_clk1_c0c1c2_sel,
    output [2:0] k_user_tx_clk2_c0c1c2_sel,
    output [3071:0] o_ptp_cfg_tx_asm_ch1,
    output [3071:0] o_ptp_cfg_tx_p2p_ch1,
    output [31:0] o_hio_lavmm_rdata,
    output [31:0] o_ss_lavmm_pcie_wdata,
    output [39:0] sm_pld_tx_demux_0__o_eth,
    output [3:0] o_ss_lavmm_pcie_be,
    output [49:0] o_hio_uxquad_async,
    output [79:0] sm_pld_tx_demux_0__o_pcie,
    output [79:0] o_hio_rxdata,
    output [7:0] o_ingress1_ptp_rx_intfc_ptp_data,
    output [8:0] o_egress1_ptp_tx_data,
    output [8:0] o_egress1_ptp_tx_data_ld,
    output [99:0] o_hio_rxdata_async,
    output [9:0] o_hio_rxdata_direct,
    output [9:0] o_hio_rxdata_extra,
    output o_hio_det_lat_rx_async_dl_sync,
    output o_hio_det_lat_rx_async_pulse,
    output o_hio_det_lat_rx_async_sample_sync,
    output o_hio_det_lat_rx_sclk_sample_sync,
    output o_hio_det_lat_rx_trig_sample_sync,
    output o_hio_det_lat_tx_async_dl_sync,
    output o_hio_det_lat_tx_async_pulse,
    output o_hio_det_lat_tx_async_sample_sync,
    output o_hio_det_lat_tx_sclk_sample_sync,
    output o_hio_det_lat_tx_trig_sample_sync,
    output o_hio_lavmm_rdata_valid,
    output o_hio_lavmm_waitreq,
    output o_hio_rxdata_fifo_rd_empty,
    output o_hio_rxdata_fifo_rd_full,
    output o_hio_rxdata_fifo_rd_pempty,
    output o_hio_rxdata_fifo_rd_pfull,
    output o_hio_txdata_fifo_wr_empty,
    output o_hio_txdata_fifo_wr_full,
    output o_hio_txdata_fifo_wr_pempty,
    output o_hio_txdata_fifo_wr_pfull,
    output o_hio_user_rx_clk1_clk,
    output o_hio_user_rx_clk2_clk,
    output o_hio_user_tx_clk1_clk,
    output o_hio_user_tx_clk2_clk,
    output o_hio_ux_chnl_refclk_mux,
    output o_hio_ux_tx_ch_ptr_smpl,
    output o_hio_xcvrif_rx_latency_pulse,
    output o_hio_xcvrif_tx_latency_pulse,
    output o_ss_lavmm_pcie_clk,
    output o_ss_lavmm_pcie_read,
    output o_ss_lavmm_pcie_rstn,
    output o_ss_lavmm_pcie_write,
    output o_ch1_ptp_mas_word_align,
    output o_egress1_ptp_tx_wa_ld,
    output o_ingress1_ptp_rx_dsk_marker,
// FMM Ports
    output o_ptp_ptpi_link
);

  generate
    if ((device_die_type == "MAIN_SM7") || (device_die_type == "MAIN_SM4") || (device_die_type == "MAIN_SM5")) begin : sm_block
    chptp #(
        .x_decoder_sm_pld_tx_demux_0__sel                       (sm_pld_tx_demux_0__sel            ),
        .x_mux_sm_pld_rx_mux_0__sel                             (pld_rx_mux_0__sel                 ),
        .x_mux_sm_hssi_pld_chnl_rx_fifo_wr_clk_mux_0__sel       (pld_chnl_rx_fifo_wr_clk_mux_0__sel),
        .x_mux_sm_hssi_pld_chnl_tx_fifo_rd_clk_mux_0__sel       (pld_chnl_tx_fifo_rd_clk_mux_0__sel),
        .x_std_sm_hssi_pld_chnl_dp_0__dr_enabled                (dr_enabled                        ),
        .x_std_sm_hssi_pld_chnl_dp_0__duplex_mode               (duplex_mode                       ),
        .x_std_sm_hssi_pld_chnl_dp_0__pld_channel_identifier    (pld_channel_identifier            ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_clkout1_divider        (rx_clkout1_divider                ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_clkout2_divider        (rx_clkout2_divider                ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_en                     (rx_en                             ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_fifo_mode              (rx_fifo_mode                      ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_fifo_width             (rx_fifo_width                     ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_fifo_wr_clk_hz         (rx_fifo_wr_clk_hz                 ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_user1_clk_dynamic_mux  (rx_user1_clk_dynamic_mux          ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_user2_clk_dynamic_mux  (rx_user2_clk_dynamic_mux          ),
        .x_std_sm_hssi_pld_chnl_dp_0__sup_mode                  (sup_mode                          ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_clkout1_divider        (tx_clkout1_divider                ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_clkout2_divider        (tx_clkout2_divider                ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_en                     (tx_en                             ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_fifo_mode              (tx_fifo_mode                      ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_fifo_rd_clk_hz         (tx_fifo_rd_clk_hz                 ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_fifo_width             (tx_fifo_width                     ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_user1_clk_dynamic_mux  (tx_user1_clk_dynamic_mux          ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_user2_clk_dynamic_mux  (tx_user2_clk_dynamic_mux          ),
        .x_std_sm_hssi_pld_chnl_dp_0__vc_rx_pldif_wm_en         (vc_rx_pldif_wm_en                 ),
        .x_std_sm_ptp_0__ptp0_en                                (ptp0_en                           ),
       `ifdef __USE_SOF_SETTINGS__
          .x_std_sm_ptp_0__ptp0_sim_mode                        ("PTP0_SIM_MODE_DISABLE"),
          .x_std_sm_ptp_0__ptp1_sim_mode                        ("PTP1_SIM_MODE_DISABLE"),
       `else
          .x_std_sm_ptp_0__ptp0_sim_mode                        (ptp0_sim_mode), 
          .x_std_sm_ptp_0__ptp1_sim_mode                        (ptp1_sim_mode),
       `endif 
        .x_std_sm_ptp_0__ptp0_sup_mode                          (ptp0_sup_mode                     ),
        .x_std_sm_ptp_0__ptp1_en                                (ptp1_en                           ),
        .x_std_sm_ptp_0__ptp1_sup_mode                          (ptp1_sup_mode                     )    
    ) chptp_inst (
        .x_mux_sm_pld_rx_mux_0__i_eth                                       (sm_pld_rx_mux_0__i_eth),
        .x_mux_sm_pld_rx_mux_0__i_pcie                                      (sm_pld_rx_mux_0__i_pcie),
        .x_decoder_sm_pld_tx_demux_0__o_eth                                 (sm_pld_tx_demux_0__o_eth),
        .x_decoder_sm_pld_tx_demux_0__o_pcie                                (sm_pld_tx_demux_0__o_pcie),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_addr                      (i_hio_lavmm_addr),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_wdata                     (i_hio_lavmm_wdata),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_lavmm_pcie_rdata                 (i_ss_lavmm_pcie_rdata),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_be                        (i_hio_lavmm_be),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_txdata                          (i_hio_txdata),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_uxquad_async                    (i_hio_uxquad_async),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_uxquad_async_pcie_mux           (i_hio_uxquad_async_pcie_mux),
        .x_std_sm_ptp_0__i_egress1_ptp_rx_data                              (i_egress1_ptp_rx_data),
        .x_std_sm_ptp_0__i_ingress1_ptp_tx_intfc_ptp_data                   (i_ingress1_ptp_tx_intfc_ptp_data),
        .x_std_sm_ptp_0__i_ingress1_ptp_tx_intfc_ptp_data_ld                (i_ingress1_ptp_tx_intfc_ptp_data_ld),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_txdata_async                    (i_hio_txdata_async),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_txdata_direct                   (i_hio_txdata_direct),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_txdata_extra                    (i_hio_txdata_extra),
        .x_mux_sm_hssi_pld_chnl_rx_fifo_wr_clk_mux_0__i_eth_or_ptp          (pld_chnl_rx_fifo_wr_clk_mux_0__i_eth_or_ptp),
        .x_mux_sm_hssi_pld_chnl_rx_fifo_wr_clk_mux_0__i_pcie                (pld_chnl_rx_fifo_wr_clk_mux_0__i_pcie),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_rx_dl_clk               (i_hio_det_lat_rx_dl_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_rx_mux_select           (i_hio_det_lat_rx_mux_select),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_rx_sclk_flop            (i_hio_det_lat_rx_sclk_flop),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_rx_sclk_gen_clk         (i_hio_det_lat_rx_sclk_gen_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_rx_trig_flop            (i_hio_det_lat_rx_trig_flop),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_sampling_clk            (i_hio_det_lat_sampling_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_tx_dl_clk               (i_hio_det_lat_tx_dl_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_tx_mux_select           (i_hio_det_lat_tx_mux_select),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_tx_sclk_flop            (i_hio_det_lat_tx_sclk_flop),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_tx_sclk_gen_clk         (i_hio_det_lat_tx_sclk_gen_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_tx_trig_flop            (i_hio_det_lat_tx_trig_flop),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_clk                       (i_hio_lavmm_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_read                      (i_hio_lavmm_read),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_rstn                      (i_hio_lavmm_rstn),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_write                     (i_hio_lavmm_write),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_pld_reset_clk_row               (i_hio_pld_reset_clk_row),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_pld_rx_clk_in_row_clk           (i_hio_pld_rx_clk_in_row_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_pld_tx_clk_in_row_clk           (i_hio_pld_tx_clk_in_row_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_ptp_rst_n                       (i_hio_ptp_rst_n),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_rst_pld_adapter_rx_pld_rst_n    (i_hio_rst_pld_adapter_rx_pld_rst_n),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_rst_pld_adapter_tx_pld_rst_n    (i_hio_rst_pld_adapter_tx_pld_rst_n),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_rst_pld_ready                   (i_hio_rst_pld_ready),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_rxdata_fifo_rd_en               (i_hio_rxdata_fifo_rd_en),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_txdata_fifo_wr_en               (i_hio_txdata_fifo_wr_en),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_lavmm_pcie_rdata_valid           (i_ss_lavmm_pcie_rdata_valid),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_lavmm_pcie_waitreq               (i_ss_lavmm_pcie_waitreq),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_user_rx_clk1_clk                 (i_ss_user_rx_clk1_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_user_rx_clk2_clk                 (i_ss_user_rx_clk2_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_user_tx_clk1_clk                 (i_ss_user_tx_clk1_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_user_tx_clk2_clk                 (i_ss_user_tx_clk2_clk),
        .x_std_sm_ptp_0__i_ingress1_ptp_tx_wa_ld                            (i_ingress1_ptp_tx_wa_ld),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_addr                  (o_ss_lavmm_pcie_addr),
        .x_std_sm_hssi_pld_chnl_dp_0__k_user_rx_clk1_c0c1c2_sel             (k_user_rx_clk1_c0c1c2_sel),
        .x_std_sm_hssi_pld_chnl_dp_0__k_user_rx_clk2_c0c1c2_sel             (k_user_rx_clk2_c0c1c2_sel),
        .x_std_sm_hssi_pld_chnl_dp_0__k_user_tx_clk1_c0c1c2_sel             (k_user_tx_clk1_c0c1c2_sel),
        .x_std_sm_hssi_pld_chnl_dp_0__k_user_tx_clk2_c0c1c2_sel             (k_user_tx_clk2_c0c1c2_sel),
        .x_std_sm_ptp_0__o_ptp_cfg_tx_asm_ch1                               (o_ptp_cfg_tx_asm_ch1),
        .x_std_sm_ptp_0__o_ptp_cfg_tx_p2p_ch1                               (o_ptp_cfg_tx_p2p_ch1),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_lavmm_rdata                     (o_hio_lavmm_rdata),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_wdata                 (o_ss_lavmm_pcie_wdata),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_be                    (o_ss_lavmm_pcie_be),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_uxquad_async                    (o_hio_uxquad_async),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata                          (o_hio_rxdata),
        .x_std_sm_ptp_0__o_ingress1_ptp_rx_intfc_ptp_data                   (o_ingress1_ptp_rx_intfc_ptp_data),
        .x_std_sm_ptp_0__o_egress1_ptp_tx_data                              (o_egress1_ptp_tx_data),
        .x_std_sm_ptp_0__o_egress1_ptp_tx_data_ld                           (o_egress1_ptp_tx_data_ld),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_async                    (o_hio_rxdata_async),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_direct                   (o_hio_rxdata_direct),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_extra                    (o_hio_rxdata_extra),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_rx_async_dl_sync        (o_hio_det_lat_rx_async_dl_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_rx_async_pulse          (o_hio_det_lat_rx_async_pulse),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_rx_async_sample_sync    (o_hio_det_lat_rx_async_sample_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_rx_sclk_sample_sync     (o_hio_det_lat_rx_sclk_sample_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_rx_trig_sample_sync     (o_hio_det_lat_rx_trig_sample_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_tx_async_dl_sync        (o_hio_det_lat_tx_async_dl_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_tx_async_pulse          (o_hio_det_lat_tx_async_pulse),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_tx_async_sample_sync    (o_hio_det_lat_tx_async_sample_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_tx_sclk_sample_sync     (o_hio_det_lat_tx_sclk_sample_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_tx_trig_sample_sync     (o_hio_det_lat_tx_trig_sample_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_lavmm_rdata_valid               (o_hio_lavmm_rdata_valid),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_lavmm_waitreq                   (o_hio_lavmm_waitreq),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_fifo_rd_empty            (o_hio_rxdata_fifo_rd_empty),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_fifo_rd_full             (o_hio_rxdata_fifo_rd_full),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_fifo_rd_pempty           (o_hio_rxdata_fifo_rd_pempty),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_fifo_rd_pfull            (o_hio_rxdata_fifo_rd_pfull),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_txdata_fifo_wr_empty            (o_hio_txdata_fifo_wr_empty),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_txdata_fifo_wr_full             (o_hio_txdata_fifo_wr_full),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_txdata_fifo_wr_pempty           (o_hio_txdata_fifo_wr_pempty),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_txdata_fifo_wr_pfull            (o_hio_txdata_fifo_wr_pfull),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_user_rx_clk1_clk                (o_hio_user_rx_clk1_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_user_rx_clk2_clk                (o_hio_user_rx_clk2_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_user_tx_clk1_clk                (o_hio_user_tx_clk1_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_user_tx_clk2_clk                (o_hio_user_tx_clk2_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_ux_chnl_refclk_mux              (o_hio_ux_chnl_refclk_mux),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_ux_tx_ch_ptr_smpl               (o_hio_ux_tx_ch_ptr_smpl),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_xcvrif_rx_latency_pulse         (o_hio_xcvrif_rx_latency_pulse),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_xcvrif_tx_latency_pulse         (o_hio_xcvrif_tx_latency_pulse),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_clk                   (o_ss_lavmm_pcie_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_read                  (o_ss_lavmm_pcie_read),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_rstn                  (o_ss_lavmm_pcie_rstn),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_write                 (o_ss_lavmm_pcie_write),
        .x_std_sm_ptp_0__o_ch1_ptp_mas_word_align                           (o_ch1_ptp_mas_word_align),
        .x_std_sm_ptp_0__o_egress1_ptp_tx_wa_ld                             (o_egress1_ptp_tx_wa_ld),
        .x_std_sm_ptp_0__o_ingress1_ptp_rx_dsk_marker                       (o_ingress1_ptp_rx_dsk_marker),
        .x_std_sm_ptp_s_0__o_ptp_ptpi_link                                  (o_ptp_ptpi_link)   
    );
    end else begin : fmm_block
    chptp #(
        .x_decoder_fmm_pld_tx_demux_0__sel                      (sm_pld_tx_demux_0__sel            ),
        .x_mux_fmm_pld_rx_mux_0__sel                            (pld_rx_mux_0__sel                 ),
        .x_mux_sm_hssi_pld_chnl_rx_fifo_wr_clk_mux_0__sel       (pld_chnl_rx_fifo_wr_clk_mux_0__sel),
        .x_mux_sm_hssi_pld_chnl_tx_fifo_rd_clk_mux_0__sel       (pld_chnl_tx_fifo_rd_clk_mux_0__sel),
        .x_std_sm_hssi_pld_chnl_dp_0__dr_enabled                (dr_enabled                        ),
        .x_std_sm_hssi_pld_chnl_dp_0__duplex_mode               (duplex_mode                       ),
        .x_std_sm_hssi_pld_chnl_dp_0__pld_channel_identifier    (pld_channel_identifier            ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_clkout1_divider        (rx_clkout1_divider                ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_clkout2_divider        (rx_clkout2_divider                ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_en                     (rx_en                             ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_fifo_mode              (rx_fifo_mode                      ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_fifo_width             (rx_fifo_width                     ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_fifo_wr_clk_hz         (rx_fifo_wr_clk_hz                 ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_user1_clk_dynamic_mux  (rx_user1_clk_dynamic_mux          ),
        .x_std_sm_hssi_pld_chnl_dp_0__rx_user2_clk_dynamic_mux  (rx_user2_clk_dynamic_mux          ),
        .x_std_sm_hssi_pld_chnl_dp_0__sup_mode                  (sup_mode                          ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_clkout1_divider        (tx_clkout1_divider                ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_clkout2_divider        (tx_clkout2_divider                ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_en                     (tx_en                             ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_fifo_mode              (tx_fifo_mode                      ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_fifo_rd_clk_hz         (tx_fifo_rd_clk_hz                 ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_fifo_width             (tx_fifo_width                     ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_user1_clk_dynamic_mux  (tx_user1_clk_dynamic_mux          ),
        .x_std_sm_hssi_pld_chnl_dp_0__tx_user2_clk_dynamic_mux  (tx_user2_clk_dynamic_mux          ),
        .x_std_sm_hssi_pld_chnl_dp_0__vc_rx_pldif_wm_en         (vc_rx_pldif_wm_en                 ),
        .x_std_sm_ptp_0__ptp0_en                                (ptp0_en                           ),
       `ifdef __USE_SOF_SETTINGS__
          .x_std_sm_ptp_0__ptp0_sim_mode                        ("PTP0_SIM_MODE_DISABLE"),
          .x_std_sm_ptp_0__ptp1_sim_mode                        ("PTP1_SIM_MODE_DISABLE"),
       `else
          .x_std_sm_ptp_0__ptp0_sim_mode                        (ptp0_sim_mode), 
          .x_std_sm_ptp_0__ptp1_sim_mode                        (ptp1_sim_mode),
       `endif       
        .x_std_sm_ptp_0__ptp0_sup_mode                          (ptp0_sup_mode                     ),
        .x_std_sm_ptp_0__ptp1_en                                (ptp1_en                           ),
        .x_std_sm_ptp_0__ptp1_sup_mode                          (ptp1_sup_mode                     )    
    ) chptp_inst (
        .x_mux_fmm_pld_rx_mux_0__i_eth                                      (sm_pld_rx_mux_0__i_eth),
        .x_decoder_fmm_pld_tx_demux_0__o_eth                                (sm_pld_tx_demux_0__o_eth),
        .x_decoder_fmm_pld_tx_demux_0__o_pcie                               (sm_pld_tx_demux_0__o_pcie),
        .x_std_sm_ptp_0__i_egress0_ptp_rx_data                              (i_egress0_ptp_rx_data),
        .x_std_sm_ptp_0__i_ingress0_ptp_tx_intfc_ptp_data                   (i_ingress0_ptp_tx_intfc_ptp_data),
        .x_std_sm_ptp_0__i_ingress0_ptp_tx_intfc_ptp_data_ld                (i_ingress0_ptp_tx_intfc_ptp_data_ld),
        .x_std_sm_ptp_0__i_ingress0_ptp_tx_wa_ld                            (i_ingress0_ptp_tx_wa_ld),
        .x_std_sm_ptp_0__o_ptp_cfg_tx_asm_ch0                               (o_ptp_cfg_tx_asm_ch0),
        .x_std_sm_ptp_0__o_ptp_cfg_tx_p2p_ch0                               (o_ptp_cfg_tx_p2p_ch0),
        .x_std_sm_ptp_0__o_ingress0_ptp_rx_intfc_ptp_data                   (o_ingress0_ptp_rx_intfc_ptp_data),
        .x_std_sm_ptp_0__o_egress0_ptp_tx_data                              (o_egress0_ptp_tx_data),
        .x_std_sm_ptp_0__o_egress0_ptp_tx_data_ld                           (o_egress0_ptp_tx_data_ld),
        .x_std_sm_ptp_0__o_ch0_ptp_mas_word_align                           (o_ch0_ptp_mas_word_align),
        .x_std_sm_ptp_0__o_egress0_ptp_tx_wa_ld                             (o_egress0_ptp_tx_wa_ld),
        .x_std_sm_ptp_0__o_ingress0_ptp_rx_dsk_marker                       (o_ingress0_ptp_rx_dsk_marker),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_addr                      (i_hio_lavmm_addr),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_wdata                     (i_hio_lavmm_wdata),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_lavmm_pcie_rdata                 (i_ss_lavmm_pcie_rdata),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_be                        (i_hio_lavmm_be),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_txdata                          (i_hio_txdata),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_uxquad_async                    (i_hio_uxquad_async),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_uxquad_async_pcie_mux           (i_hio_uxquad_async_pcie_mux),
        .x_std_sm_ptp_0__i_egress1_ptp_rx_data                              (i_egress1_ptp_rx_data),
        .x_std_sm_ptp_0__i_ingress1_ptp_tx_intfc_ptp_data                   (i_ingress1_ptp_tx_intfc_ptp_data),
        .x_std_sm_ptp_0__i_ingress1_ptp_tx_intfc_ptp_data_ld                (i_ingress1_ptp_tx_intfc_ptp_data_ld),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_txdata_async                    (i_hio_txdata_async),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_txdata_direct                   (i_hio_txdata_direct),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_txdata_extra                    (i_hio_txdata_extra),
        .x_mux_sm_hssi_pld_chnl_rx_fifo_wr_clk_mux_0__i_eth_or_ptp          (pld_chnl_rx_fifo_wr_clk_mux_0__i_eth_or_ptp),
        .x_mux_sm_hssi_pld_chnl_rx_fifo_wr_clk_mux_0__i_pcie                (pld_chnl_rx_fifo_wr_clk_mux_0__i_pcie),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_rx_dl_clk               (i_hio_det_lat_rx_dl_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_rx_mux_select           (i_hio_det_lat_rx_mux_select),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_rx_sclk_flop            (i_hio_det_lat_rx_sclk_flop),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_rx_sclk_gen_clk         (i_hio_det_lat_rx_sclk_gen_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_rx_trig_flop            (i_hio_det_lat_rx_trig_flop),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_sampling_clk            (i_hio_det_lat_sampling_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_tx_dl_clk               (i_hio_det_lat_tx_dl_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_tx_mux_select           (i_hio_det_lat_tx_mux_select),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_tx_sclk_flop            (i_hio_det_lat_tx_sclk_flop),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_tx_sclk_gen_clk         (i_hio_det_lat_tx_sclk_gen_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_det_lat_tx_trig_flop            (i_hio_det_lat_tx_trig_flop),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_clk                       (i_hio_lavmm_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_read                      (i_hio_lavmm_read),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_rstn                      (i_hio_lavmm_rstn),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_lavmm_write                     (i_hio_lavmm_write),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_pld_reset_clk_row               (i_hio_pld_reset_clk_row),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_pld_rx_clk_in_row_clk           (i_hio_pld_rx_clk_in_row_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_pld_tx_clk_in_row_clk           (i_hio_pld_tx_clk_in_row_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_ptp_rst_n                       (i_hio_ptp_rst_n),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_rst_pld_adapter_rx_pld_rst_n    (i_hio_rst_pld_adapter_rx_pld_rst_n),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_rst_pld_adapter_tx_pld_rst_n    (i_hio_rst_pld_adapter_tx_pld_rst_n),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_rst_pld_ready                   (i_hio_rst_pld_ready),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_rxdata_fifo_rd_en               (i_hio_rxdata_fifo_rd_en),
        .x_std_sm_hssi_pld_chnl_dp_0__i_hio_txdata_fifo_wr_en               (i_hio_txdata_fifo_wr_en),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_lavmm_pcie_rdata_valid           (i_ss_lavmm_pcie_rdata_valid),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_lavmm_pcie_waitreq               (i_ss_lavmm_pcie_waitreq),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_user_rx_clk1_clk                 (i_ss_user_rx_clk1_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_user_rx_clk2_clk                 (i_ss_user_rx_clk2_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_user_tx_clk1_clk                 (i_ss_user_tx_clk1_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__i_ss_user_tx_clk2_clk                 (i_ss_user_tx_clk2_clk),
        .x_std_sm_ptp_0__i_ingress1_ptp_tx_wa_ld                            (i_ingress1_ptp_tx_wa_ld),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_addr                  (o_ss_lavmm_pcie_addr),
        .x_std_sm_hssi_pld_chnl_dp_0__k_user_rx_clk1_c0c1c2_sel             (k_user_rx_clk1_c0c1c2_sel),
        .x_std_sm_hssi_pld_chnl_dp_0__k_user_rx_clk2_c0c1c2_sel             (k_user_rx_clk2_c0c1c2_sel),
        .x_std_sm_hssi_pld_chnl_dp_0__k_user_tx_clk1_c0c1c2_sel             (k_user_tx_clk1_c0c1c2_sel),
        .x_std_sm_hssi_pld_chnl_dp_0__k_user_tx_clk2_c0c1c2_sel             (k_user_tx_clk2_c0c1c2_sel),
        .x_std_sm_ptp_0__o_ptp_cfg_tx_asm_ch1                               (o_ptp_cfg_tx_asm_ch1),
        .x_std_sm_ptp_0__o_ptp_cfg_tx_p2p_ch1                               (o_ptp_cfg_tx_p2p_ch1),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_lavmm_rdata                     (o_hio_lavmm_rdata),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_wdata                 (o_ss_lavmm_pcie_wdata),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_be                    (o_ss_lavmm_pcie_be),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_uxquad_async                    (o_hio_uxquad_async),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata                          (o_hio_rxdata),
        .x_std_sm_ptp_0__o_ingress1_ptp_rx_intfc_ptp_data                   (o_ingress1_ptp_rx_intfc_ptp_data),
        .x_std_sm_ptp_0__o_egress1_ptp_tx_data                              (o_egress1_ptp_tx_data),
        .x_std_sm_ptp_0__o_egress1_ptp_tx_data_ld                           (o_egress1_ptp_tx_data_ld),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_async                    (o_hio_rxdata_async),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_direct                   (o_hio_rxdata_direct),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_extra                    (o_hio_rxdata_extra),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_rx_async_dl_sync        (o_hio_det_lat_rx_async_dl_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_rx_async_pulse          (o_hio_det_lat_rx_async_pulse),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_rx_async_sample_sync    (o_hio_det_lat_rx_async_sample_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_rx_sclk_sample_sync     (o_hio_det_lat_rx_sclk_sample_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_rx_trig_sample_sync     (o_hio_det_lat_rx_trig_sample_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_tx_async_dl_sync        (o_hio_det_lat_tx_async_dl_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_tx_async_pulse          (o_hio_det_lat_tx_async_pulse),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_tx_async_sample_sync    (o_hio_det_lat_tx_async_sample_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_tx_sclk_sample_sync     (o_hio_det_lat_tx_sclk_sample_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_det_lat_tx_trig_sample_sync     (o_hio_det_lat_tx_trig_sample_sync),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_lavmm_rdata_valid               (o_hio_lavmm_rdata_valid),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_lavmm_waitreq                   (o_hio_lavmm_waitreq),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_fifo_rd_empty            (o_hio_rxdata_fifo_rd_empty),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_fifo_rd_full             (o_hio_rxdata_fifo_rd_full),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_fifo_rd_pempty           (o_hio_rxdata_fifo_rd_pempty),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_rxdata_fifo_rd_pfull            (o_hio_rxdata_fifo_rd_pfull),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_txdata_fifo_wr_empty            (o_hio_txdata_fifo_wr_empty),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_txdata_fifo_wr_full             (o_hio_txdata_fifo_wr_full),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_txdata_fifo_wr_pempty           (o_hio_txdata_fifo_wr_pempty),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_txdata_fifo_wr_pfull            (o_hio_txdata_fifo_wr_pfull),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_user_rx_clk1_clk                (o_hio_user_rx_clk1_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_user_rx_clk2_clk                (o_hio_user_rx_clk2_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_user_tx_clk1_clk                (o_hio_user_tx_clk1_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_user_tx_clk2_clk                (o_hio_user_tx_clk2_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_ux_chnl_refclk_mux              (o_hio_ux_chnl_refclk_mux),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_ux_tx_ch_ptr_smpl               (o_hio_ux_tx_ch_ptr_smpl),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_xcvrif_rx_latency_pulse         (o_hio_xcvrif_rx_latency_pulse),
        .x_std_sm_hssi_pld_chnl_dp_0__o_hio_xcvrif_tx_latency_pulse         (o_hio_xcvrif_tx_latency_pulse),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_clk                   (o_ss_lavmm_pcie_clk),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_read                  (o_ss_lavmm_pcie_read),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_rstn                  (o_ss_lavmm_pcie_rstn),
        .x_std_sm_hssi_pld_chnl_dp_0__o_ss_lavmm_pcie_write                 (o_ss_lavmm_pcie_write),
        .x_std_sm_ptp_0__o_ch1_ptp_mas_word_align                           (o_ch1_ptp_mas_word_align),
        .x_std_sm_ptp_0__o_egress1_ptp_tx_wa_ld                             (o_egress1_ptp_tx_wa_ld),
        .x_std_sm_ptp_0__o_ingress1_ptp_rx_dsk_marker                       (o_ingress1_ptp_rx_dsk_marker),
        .x_std_sm_ptp_s_0__o_ptp_ptpi_link                                  (o_ptp_ptpi_link)   
    );  
    end
  endgenerate
endmodule

