-- jesd204b_core_one_lane_hal_pcs_hal_2100_ij4zeoi.vhd

-- Generated using ACDS version 25.1.1 125

library IEEE;
library pcs_hal_2100;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity jesd204b_core_one_lane_hal_pcs_hal_2100_ij4zeoi is
	generic (
		ch_pcs_l_duplex_mode_atom      : string := "DUPLEX_MODE_RX_ONLY_SIMPLEX";
		ch_pcs_l_loopback_mode_atom    : string := "LOOPBACK_MODE_NO_LOOPBACK";
		ch_pcs_dr_enabled_atom         : string := "DR_ENABLED_DR_ENABLED";
		ch_pcs_l_rate_mode_atom        : string := "RATE_MODE_RATE_25G";
		ch_pcs_l_sup_mode_atom         : string := "SUP_MODE_USER_MODE";
		ch_pcs_l_sim_mode_atom         : string := "SIM_MODE_ENABLE";
		ch_pcs_l_tx_en_atom            : string := "FALSE";
		ch_pcs_l_rx_en_atom            : string := "FALSE";
		ch_pcs_l_fec_spec_atom         : string := "FEC_SPEC_DISABLED";
		ch_pcs_tx_dyn_mux_atom         : string := "TX_DYN_MUX_UNUSED";
		ch_pcs_rx_dyn_mux_atom         : string := "RX_DYN_MUX_UNUSED";
		ch_pcs_l_pcs_ber_mon_mode_atom : string := "PCS_BER_MON_MODE_BER_25G";
		ch_pcs_l_tx_pcs_mode_atom      : string := "TX_PCS_MODE_DISABLED";
		ch_pcs_l_rx_pcs_mode_atom      : string := "RX_PCS_MODE_DISABLED";
		ch_pcs_l_fec_mode_atom         : string := "FEC_MODE_DISABLED";
		ch_pcs_l_fec_tx_en_atom        : string := "FALSE";
		ch_pcs_l_fec_rx_en_atom        : string := "FALSE"
	);
	port (
		o_ch_lavmm_epcs_rdata              : out std_logic_vector(31 downto 0);                    --             reconfig.readdata,      Stats Snapshot
		o_ch_lavmm_epcs_rdata_valid        : out std_logic;                                        --                     .readdatavalid, RX PFC
		o_ch_lavmm_epcs_waitreq            : out std_logic;                                        --                     .waitrequest,   CSR access address
		i_ch_lavmm_epcs_addr               : in  std_logic_vector(19 downto 0) := (others => '0'); --                     .address,       RX error bits asserted on the EOP cycle
		i_ch_lavmm_epcs_be                 : in  std_logic_vector(3 downto 0)  := (others => '0'); --                     .byteenable,    Stats Snapshot
		i_ch_lavmm_epcs_read               : in  std_logic                     := '0';             --                     .read,          CSR access address
		i_ch_lavmm_epcs_wdata              : in  std_logic_vector(31 downto 0) := (others => '0'); --                     .writedata,     Stats Snapshot
		i_ch_lavmm_epcs_write              : in  std_logic                     := '0';             --                     .write,         RX PFC
		i_ch_lavmm_epcs_clk                : in  std_logic                     := '0';             --         reconfig_clk.clk,           RX PFC
		i_ch_lavmm_epcs_rstn               : in  std_logic                     := '0';             --         reconfig_rst.reset,         RX error bits asserted on the EOP cycle
		i_pcs_tx_clk                       : in  std_logic                     := '0';             --         i_pcs_tx_clk.clk,           CSR access address
		i_pcs_rx_clk                       : in  std_logic                     := '0';             --         i_pcs_rx_clk.clk,           RX error bits asserted on the EOP cycle
		i_hssi_async_dir_eth_pcs_tx_async  : in  std_logic_vector(7 downto 0)  := (others => '0'); --          asyncdata_0.data,          Stats Snapshot
		i_hssi_async_dir_eth_pcs_tx_direct : in  std_logic                     := '0';             --          asyncdata_1.data,          RX PFC
		o_hssi_async_dir_eth_pcs_rx_async  : out std_logic_vector(13 downto 0);                    --          asyncdata_2.data,          CSR access address
		o_hssi_async_dir_eth_pcs_rx_direct : out std_logic;                                        --          asyncdata_3.data,          RX error bits asserted on the EOP cycle
		i_ehip_rx_rst_n                    : in  std_logic                     := '0';             --        reset_path_rx.data,          Stats Snapshot
		i_ehip_tx_rst_n                    : in  std_logic                     := '0';             --        reset_path_tx.data,          RX PFC
		o_rstepcs_rx_pcs_fully_aligned     : out std_logic;                                        -- rx_pcs_fully_aligned.status,        CSR access address
		i_ehip_signal_ok                   : in  std_logic                     := '0';             --       ehip_signal_ok.data,          RX error bits asserted on the EOP cycle
		i_t03f_sfreeze_1_tx_pcs_sfrz_n     : in  std_logic                     := '0';             --        tx_pcs_sfrz_n.reset,         RX error bits asserted on the EOP cycle
		i_sfreeze_2_r03f_rx_pcs_sfrz_n     : in  std_logic                     := '0';             --        rx_pcs_sfrz_n.reset,         RX error bits asserted on the EOP cycle
		o_pcs_tx_data                      : out std_logic_vector(42 downto 0);                    --        o_pcs_tx_data.data,          RX error bits asserted on the EOP cycle
		o_pcs_rx_mii_data                  : out std_logic_vector(42 downto 0);                    --    o_pcs_rx_mii_data.data,          RX error bits asserted on the EOP cycle
		o_pcs_rx_data                      : out std_logic_vector(42 downto 0);                    --        o_pcs_rx_data.data,          CSR access address
		o_tx_mux_sel                       : out std_logic;                                        --         o_tx_mux_sel.data,          RX error bits asserted on the EOP cycle
		o_rx_mux_sel                       : out std_logic;                                        --         o_rx_mux_sel.data,          RX error bits asserted on the EOP cycle
		i_pcs_tx_data_mux                  : in  std_logic_vector(42 downto 0) := (others => '0'); --    i_pcs_tx_data_mux.data,          RX error bits asserted on the EOP cycle
		i_pcs_rx_data_mux                  : in  std_logic_vector(42 downto 0) := (others => '0')  --    i_pcs_rx_data_mux.data,          RX error bits asserted on the EOP cycle
	);
end entity jesd204b_core_one_lane_hal_pcs_hal_2100_ij4zeoi;

architecture rtl of jesd204b_core_one_lane_hal_pcs_hal_2100_ij4zeoi is
	component jesd204b_core_pcs_hal_2100_i6srn2q_cmp is
		generic (
			ch_pcs_l_duplex_mode_atom      : string := "";
			ch_pcs_l_loopback_mode_atom    : string := "";
			ch_pcs_dr_enabled_atom         : string := "";
			ch_pcs_l_rate_mode_atom        : string := "";
			ch_pcs_l_sup_mode_atom         : string := "";
			ch_pcs_l_sim_mode_atom         : string := "";
			ch_pcs_l_tx_en_atom            : string := "";
			ch_pcs_l_rx_en_atom            : string := "";
			ch_pcs_l_fec_spec_atom         : string := "";
			ch_pcs_tx_dyn_mux_atom         : string := "TX_DYN_MUX_UNUSED";
			ch_pcs_rx_dyn_mux_atom         : string := "RX_DYN_MUX_UNUSED";
			ch_pcs_l_pcs_ber_mon_mode_atom : string := "PCS_BER_MON_MODE_DISABLED";
			ch_pcs_l_tx_pcs_mode_atom      : string := "TX_PCS_MODE_DISABLED";
			ch_pcs_l_rx_pcs_mode_atom      : string := "RX_PCS_MODE_DISABLED";
			ch_pcs_l_fec_mode_atom         : string := "FEC_MODE_DISABLED";
			ch_pcs_l_fec_tx_en_atom        : string := "FALSE";
			ch_pcs_l_fec_rx_en_atom        : string := "FALSE"
		);
		port (
			o_ch_lavmm_epcs_rdata              : out std_logic_vector(31 downto 0);                    -- readdata
			o_ch_lavmm_epcs_rdata_valid        : out std_logic;                                        -- readdatavalid
			o_ch_lavmm_epcs_waitreq            : out std_logic;                                        -- waitrequest
			i_ch_lavmm_epcs_addr               : in  std_logic_vector(19 downto 0) := (others => 'X'); -- address
			i_ch_lavmm_epcs_be                 : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			i_ch_lavmm_epcs_read               : in  std_logic                     := 'X';             -- read
			i_ch_lavmm_epcs_wdata              : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			i_ch_lavmm_epcs_write              : in  std_logic                     := 'X';             -- write
			i_ch_lavmm_epcs_clk                : in  std_logic                     := 'X';             -- clk
			i_ch_lavmm_epcs_rstn               : in  std_logic                     := 'X';             -- reset
			i_pcs_tx_clk                       : in  std_logic                     := 'X';             -- clk
			i_pcs_rx_clk                       : in  std_logic                     := 'X';             -- clk
			i_hssi_async_dir_eth_pcs_tx_async  : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- data
			i_hssi_async_dir_eth_pcs_tx_direct : in  std_logic                     := 'X';             -- data
			o_hssi_async_dir_eth_pcs_rx_async  : out std_logic_vector(13 downto 0);                    -- data
			o_hssi_async_dir_eth_pcs_rx_direct : out std_logic;                                        -- data
			i_ehip_rx_rst_n                    : in  std_logic                     := 'X';             -- data
			i_ehip_tx_rst_n                    : in  std_logic                     := 'X';             -- data
			o_rstepcs_rx_pcs_fully_aligned     : out std_logic;                                        -- status
			i_ehip_signal_ok                   : in  std_logic                     := 'X';             -- data
			i_t03f_sfreeze_1_tx_pcs_sfrz_n     : in  std_logic                     := 'X';             -- reset
			i_sfreeze_2_r03f_rx_pcs_sfrz_n     : in  std_logic                     := 'X';             -- reset
			o_pcs_tx_data                      : out std_logic_vector(42 downto 0);                    -- data
			o_pcs_rx_mii_data                  : out std_logic_vector(42 downto 0);                    -- data
			o_pcs_rx_data                      : out std_logic_vector(42 downto 0);                    -- data
			o_tx_mux_sel                       : out std_logic;                                        -- data
			o_rx_mux_sel                       : out std_logic;                                        -- data
			i_pcs_tx_data_mux                  : in  std_logic_vector(42 downto 0) := (others => 'X'); -- data
			i_pcs_rx_data_mux                  : in  std_logic_vector(42 downto 0) := (others => 'X')  -- data
		);
	end component jesd204b_core_pcs_hal_2100_i6srn2q_cmp;

	for pcs_hal_top : jesd204b_core_pcs_hal_2100_i6srn2q_cmp
		use entity pcs_hal_2100.jesd204b_core_pcs_hal_2100_i6srn2q;
begin

	ch_pcs_l_duplex_mode_atom_check : if ch_pcs_l_duplex_mode_atom /= "DUPLEX_MODE_RX_ONLY_SIMPLEX" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_loopback_mode_atom_check : if ch_pcs_l_loopback_mode_atom /= "LOOPBACK_MODE_NO_LOOPBACK" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_dr_enabled_atom_check : if ch_pcs_dr_enabled_atom /= "DR_ENABLED_DR_ENABLED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_rate_mode_atom_check : if ch_pcs_l_rate_mode_atom /= "RATE_MODE_RATE_25G" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_sup_mode_atom_check : if ch_pcs_l_sup_mode_atom /= "SUP_MODE_USER_MODE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_sim_mode_atom_check : if ch_pcs_l_sim_mode_atom /= "SIM_MODE_ENABLE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_tx_en_atom_check : if ch_pcs_l_tx_en_atom /= "FALSE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_rx_en_atom_check : if ch_pcs_l_rx_en_atom /= "FALSE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_fec_spec_atom_check : if ch_pcs_l_fec_spec_atom /= "FEC_SPEC_DISABLED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_tx_dyn_mux_atom_check : if ch_pcs_tx_dyn_mux_atom /= "TX_DYN_MUX_UNUSED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_rx_dyn_mux_atom_check : if ch_pcs_rx_dyn_mux_atom /= "RX_DYN_MUX_UNUSED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_pcs_ber_mon_mode_atom_check : if ch_pcs_l_pcs_ber_mon_mode_atom /= "PCS_BER_MON_MODE_BER_25G" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_tx_pcs_mode_atom_check : if ch_pcs_l_tx_pcs_mode_atom /= "TX_PCS_MODE_DISABLED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_rx_pcs_mode_atom_check : if ch_pcs_l_rx_pcs_mode_atom /= "RX_PCS_MODE_DISABLED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_fec_mode_atom_check : if ch_pcs_l_fec_mode_atom /= "FEC_MODE_DISABLED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_fec_tx_en_atom_check : if ch_pcs_l_fec_tx_en_atom /= "FALSE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ch_pcs_l_fec_rx_en_atom_check : if ch_pcs_l_fec_rx_en_atom /= "FALSE" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	pcs_hal_top : component jesd204b_core_pcs_hal_2100_i6srn2q_cmp
		generic map (
			ch_pcs_l_duplex_mode_atom      => "DUPLEX_MODE_RX_ONLY_SIMPLEX",
			ch_pcs_l_loopback_mode_atom    => "LOOPBACK_MODE_NO_LOOPBACK",
			ch_pcs_dr_enabled_atom         => "DR_ENABLED_DR_ENABLED",
			ch_pcs_l_rate_mode_atom        => "RATE_MODE_RATE_25G",
			ch_pcs_l_sup_mode_atom         => "SUP_MODE_USER_MODE",
			ch_pcs_l_sim_mode_atom         => "SIM_MODE_ENABLE",
			ch_pcs_l_tx_en_atom            => "FALSE",
			ch_pcs_l_rx_en_atom            => "FALSE",
			ch_pcs_l_fec_spec_atom         => "FEC_SPEC_DISABLED",
			ch_pcs_tx_dyn_mux_atom         => "TX_DYN_MUX_UNUSED",
			ch_pcs_rx_dyn_mux_atom         => "RX_DYN_MUX_UNUSED",
			ch_pcs_l_pcs_ber_mon_mode_atom => "PCS_BER_MON_MODE_BER_25G",
			ch_pcs_l_tx_pcs_mode_atom      => "TX_PCS_MODE_DISABLED",
			ch_pcs_l_rx_pcs_mode_atom      => "RX_PCS_MODE_DISABLED",
			ch_pcs_l_fec_mode_atom         => "FEC_MODE_DISABLED",
			ch_pcs_l_fec_tx_en_atom        => "FALSE",
			ch_pcs_l_fec_rx_en_atom        => "FALSE"
		)
		port map (
			o_ch_lavmm_epcs_rdata              => o_ch_lavmm_epcs_rdata,              --             reconfig.readdata
			o_ch_lavmm_epcs_rdata_valid        => o_ch_lavmm_epcs_rdata_valid,        --                     .readdatavalid
			o_ch_lavmm_epcs_waitreq            => o_ch_lavmm_epcs_waitreq,            --                     .waitrequest
			i_ch_lavmm_epcs_addr               => i_ch_lavmm_epcs_addr,               --                     .address
			i_ch_lavmm_epcs_be                 => i_ch_lavmm_epcs_be,                 --                     .byteenable
			i_ch_lavmm_epcs_read               => i_ch_lavmm_epcs_read,               --                     .read
			i_ch_lavmm_epcs_wdata              => i_ch_lavmm_epcs_wdata,              --                     .writedata
			i_ch_lavmm_epcs_write              => i_ch_lavmm_epcs_write,              --                     .write
			i_ch_lavmm_epcs_clk                => i_ch_lavmm_epcs_clk,                --         reconfig_clk.clk
			i_ch_lavmm_epcs_rstn               => i_ch_lavmm_epcs_rstn,               --         reconfig_rst.reset
			i_pcs_tx_clk                       => i_pcs_tx_clk,                       --         i_pcs_tx_clk.clk
			i_pcs_rx_clk                       => i_pcs_rx_clk,                       --         i_pcs_rx_clk.clk
			i_hssi_async_dir_eth_pcs_tx_async  => i_hssi_async_dir_eth_pcs_tx_async,  --          asyncdata_0.data
			i_hssi_async_dir_eth_pcs_tx_direct => i_hssi_async_dir_eth_pcs_tx_direct, --          asyncdata_1.data
			o_hssi_async_dir_eth_pcs_rx_async  => o_hssi_async_dir_eth_pcs_rx_async,  --          asyncdata_2.data
			o_hssi_async_dir_eth_pcs_rx_direct => o_hssi_async_dir_eth_pcs_rx_direct, --          asyncdata_3.data
			i_ehip_rx_rst_n                    => i_ehip_rx_rst_n,                    --        reset_path_rx.data
			i_ehip_tx_rst_n                    => i_ehip_tx_rst_n,                    --        reset_path_tx.data
			o_rstepcs_rx_pcs_fully_aligned     => o_rstepcs_rx_pcs_fully_aligned,     -- rx_pcs_fully_aligned.status
			i_ehip_signal_ok                   => i_ehip_signal_ok,                   --       ehip_signal_ok.data
			i_t03f_sfreeze_1_tx_pcs_sfrz_n     => i_t03f_sfreeze_1_tx_pcs_sfrz_n,     --        tx_pcs_sfrz_n.reset
			i_sfreeze_2_r03f_rx_pcs_sfrz_n     => i_sfreeze_2_r03f_rx_pcs_sfrz_n,     --        rx_pcs_sfrz_n.reset
			o_pcs_tx_data                      => o_pcs_tx_data,                      --        o_pcs_tx_data.data
			o_pcs_rx_mii_data                  => o_pcs_rx_mii_data,                  --    o_pcs_rx_mii_data.data
			o_pcs_rx_data                      => o_pcs_rx_data,                      --        o_pcs_rx_data.data
			o_tx_mux_sel                       => o_tx_mux_sel,                       --         o_tx_mux_sel.data
			o_rx_mux_sel                       => o_rx_mux_sel,                       --         o_rx_mux_sel.data
			i_pcs_tx_data_mux                  => i_pcs_tx_data_mux,                  --    i_pcs_tx_data_mux.data
			i_pcs_rx_data_mux                  => i_pcs_rx_data_mux                   --    i_pcs_rx_data_mux.data
		);

end architecture rtl; -- of jesd204b_core_one_lane_hal_pcs_hal_2100_ij4zeoi
